import {axleReviewSchema,calculateAxles,type AxleReviewInput} from '../../../packages/domain/src/axle.ts';
export type AxlePair={loadId:string;truckId:string;trailerId:string};
export type AxleHistory={id:string;revision:number;reviewed_by:string;recorded_at:string;body:{input:AxleReviewInput;result:ReturnType<typeof calculateAxles>;document:{id:string;version:number;sha256:string}}};
export type AxleReview=AxlePair&{history:AxleHistory[];proof:{required:boolean;eligible:boolean;reasons:string[];note?:string;result?:ReturnType<typeof calculateAxles>}};
export type AxleSource={id:string;load_id:string;version:number;sha256:string;status:string;media_type:string;extraction?:{filename?:string}};
export type AxleSnapshot=AxlePair&{truckVersion:number;trailerVersion:number;loadVersion:number;weightLb:number;historyId:string;documents:AxleSource[]};
export type AxleDraft={snapshot:AxleSnapshot;values:Record<string,string>;documentId:string;sourceNote:string;reason:string};
export const axleFields=[['tractorWheelbaseM','Tractor wheelbase (m)'],['fifthWheelFromSteerM','Fifth wheel from steer group (m)'],['trailerSpanM','Kingpin to trailer group (m)'],['cargoCgFromKingpinM','Cargo centre from kingpin (m)'],['emptySteer','Empty steer group (kg)'],['emptyDrive','Empty drive group (kg)'],['emptyTrailer','Empty trailer group (kg)'],['limitSteer','Configured steer limit (kg)'],['limitDrive','Configured drive limit (kg)'],['limitTrailer','Configured trailer limit (kg)'],['grossLimitKg','Configured gross limit (kg)'],['driveAxles','Equalized drive axle count'],['trailerAxles','Equalized trailer axle count']] as const;
export function previousAxleValues(input:AxleReviewInput){const c=input.configuration;return Object.fromEntries(Object.entries({...c,cargoCgFromKingpinM:input.cargoCgFromKingpinM,emptySteer:c.emptyKg.steer,emptyDrive:c.emptyKg.drive,emptyTrailer:c.emptyKg.trailer,limitSteer:c.limitsKg.steer,limitDrive:c.limitsKg.drive,limitTrailer:c.limitsKg.trailer}).map(([k,v])=>[k,String(v)]));}
export function axleDraftInput(draft:AxleDraft){const n=(key:string)=>draft.values[key]?.trim()?Number(draft.values[key]):NaN,s=draft.snapshot,doc=s.documents.find(d=>d.id===draft.documentId);return axleReviewSchema.safeParse({loadId:s.loadId,truckId:s.truckId,trailerId:s.trailerId,expectedLoadVersion:s.loadVersion,expectedTrailerVersion:s.trailerVersion,documentId:draft.documentId,expectedDocumentVersion:doc?.version,configuration:{tractorWheelbaseM:n('tractorWheelbaseM'),fifthWheelFromSteerM:n('fifthWheelFromSteerM'),trailerSpanM:n('trailerSpanM'),emptyKg:{steer:n('emptySteer'),drive:n('emptyDrive'),trailer:n('emptyTrailer')},limitsKg:{steer:n('limitSteer'),drive:n('limitDrive'),trailer:n('limitTrailer')},grossLimitKg:n('grossLimitKg'),driveAxles:n('driveAxles'),trailerAxles:n('trailerAxles'),equalizedGroups:true},cargoCgFromKingpinM:n('cargoCgFromKingpinM'),sourceNote:draft.sourceNote,reason:draft.reason,acknowledgeModeledLoads:true});}
export function axleDraftCurrent(draft:AxleDraft,current:AxleSnapshot|null){if(!current)return false;const old=draft.snapshot;for(const key of ['loadId','truckId','trailerId','loadVersion','truckVersion','trailerVersion','weightLb','historyId'] as const)if(old[key]!==current[key])return false;const source=old.documents.find(d=>d.id===draft.documentId),now=current.documents.find(d=>d.id===draft.documentId);return !!source&&!!now&&now.status==='stored'&&now.version===source.version&&now.sha256===source.sha256&&now.load_id===old.loadId;}
export const axleSourceKey=(source:{id:string;version:number;sha256:string})=>`${source.id}:${source.version}:${source.sha256}`;
export function axleReviewCommand(draft:AxleDraft,current:AxleSnapshot|null,openedSource:string,ack:boolean){const parsed=axleDraftInput(draft),doc=draft.snapshot.documents.find(d=>d.id===draft.documentId);if(!parsed.success||!ack||!doc||openedSource!==axleSourceKey(doc)||!axleDraftCurrent(draft,current))return null;return {body:parsed.data,version:draft.snapshot.truckVersion};}
export {calculateAxles};
