import React,{useEffect,useRef,useState} from 'react';
import {Alert,AppState,Pressable,StyleSheet,Switch,TextInput,View} from 'react-native';
import {Text,colors} from './Design';
import {openBillingSource} from './billing-source';
import {axleFields,axleDraftInput,axleDraftCurrent,axleReviewCommand,axleSourceKey,previousAxleValues,calculateAxles,type AxlePair,type AxleReview,type AxleDraft,type AxleSnapshot,type AxleSource} from './axle-review';
import type {Api,State} from './api';
import type {Queue,Command} from './queue';
type Props={api:Api;queue:Queue|null;state:State;commands:Command[];online:boolean;send:(path:string,body:unknown,version:number,label:string)=>Promise<void>};
const kg=(n:number)=>new Intl.NumberFormat('en-CA',{maximumFractionDigits:1}).format(n)+' kg';
const at=(v:string)=>v?new Date(v).toLocaleString('en-CA',{timeZone:'America/Toronto'})+' ET':'Not downloaded';
function Result({result}:{result:ReturnType<typeof calculateAxles>}){return <View style={s.section}><Text style={s.label}>{result.eligible?'Within configured weight limits':'Configured weight limit exceeded'}</Text><Text style={s.body}>Gross {kg(result.grossKg)} / {kg(result.grossLimitKg)} · {result.grossWithinLimit?'within limit':'over limit'}</Text>{result.groups.map(g=><View key={g.id} style={s.group}><Text style={s.label}>{g.id} group</Text><Text style={g.withinLimit?s.body:s.warning}>{kg(g.loadedKg)} / {kg(g.limitKg)} · {g.withinLimit?'within limit':'over limit'}</Text></View>)}<Text style={s.small}>{result.note}</Text></View>;}
export function AxleReviews({api,queue,state,commands,online,send}:Props){
 const [open,setOpen]=useState(false),[pair,setPair]=useState<AxlePair>({loadId:'',truckId:'',trailerId:''}),[picker,setPicker]=useState<keyof AxlePair|null>(null),[data,setData]=useState<AxleReview|null>(null),[fresh,setFresh]=useState(false),[savedAt,setSavedAt]=useState(''),[draft,setDraft]=useState<AxleDraft|null>(null),[ack,setAck]=useState(false),[openedSource,setOpenedSource]=useState(''),[opening,setOpening]=useState(false),[message,setMessage]=useState(''),[refresh,setRefresh]=useState(0),[history,setHistory]=useState(false);
 const dispatcher=api.identity.role==='dispatcher',load=state.loads.find(l=>l.id===pair.loadId),truck=state.resources.find(r=>r.kind==='truck'&&r.id===pair.truckId),trailer=state.resources.find(r=>r.kind==='trailer'&&r.id===pair.trailerId),key='axle:'+JSON.stringify(pair);
 const documents=(state.documents??[]).filter(d=>d.load_id===pair.loadId&&d.status==='stored'&&d.sha256) as AxleSource[];
 const current:AxleSnapshot|null=load&&truck&&trailer&&load.weightLb&&data?{...pair,truckVersion:truck.version,trailerVersion:trailer.version,loadVersion:load.version,weightLb:load.weightLb,historyId:data.history[0]?.id??'',documents}:null;
 const pending=commands.some(c=>c.path==='/api/review-axles'&&c.status==='pending'&&(()=>{try{return JSON.parse(c.body).truckId===pair.truckId;}catch{return true;}})());
 const ready=online&&fresh&&Date.now()-Date.parse(savedAt)<6000&&!opening&&!pending&&!!current;
 const latest=useRef({draft,current,ready,savedAt,openedSource,ack,commands});latest.current={draft,current,ready,savedAt,openedSource,ack,commands};
 useEffect(()=>{let active=true;if(!queue||!open)return;void queue.draft('axle-selection').then(v=>{if(active&&v)setPair(JSON.parse(v));}).catch(()=>{});return()=>{active=false;};},[queue,open]);
 useEffect(()=>{let active=true,running=false;setData(null);setFresh(false);setSavedAt('');setDraft(null);setAck(false);setOpenedSource('');setMessage('');if(!open||!queue||!load||!truck||!trailer)return;
 async function fetchReview(){if(running||AppState.currentState!=='active')return;running=true;try{const r=await api.request('/api/axle-review?'+Object.entries(pair).map(([k,v])=>k+'='+encodeURIComponent(v)).join('&'));if(r.status!==200){if([401,403,404].includes(r.status)){await queue!.saveDraft(key,'');await queue!.saveDraft(key+':draft','');if(active){setData(null);setDraft(null);}}throw new Error(r.body.error?.message??`HTTP ${r.status}`);}if(r.body.loadId!==pair.loadId||r.body.truckId!==pair.truckId||r.body.trailerId!==pair.trailerId)throw new Error('Axle review scope mismatch');const saved=new Date().toISOString();await queue!.saveDraft(key,JSON.stringify({data:r.body,savedAt:saved}));if(active){setData(r.body);setFresh(true);setSavedAt(saved);setMessage(m=>m.startsWith('Evidence unavailable:')?'':m);}}catch(e){if(active){setFresh(false);setMessage('Evidence unavailable: '+String(e)+'. Saved history remains dated.');}}finally{running=false;}}
 void(async()=>{try{const cached=await queue.draft(key),savedDraft=await queue.draft(key+':draft');if(active&&cached){const c=JSON.parse(cached);if(c.data.loadId===pair.loadId&&c.data.truckId===pair.truckId&&c.data.trailerId===pair.trailerId){setData(c.data);setSavedAt(c.savedAt);}}if(active&&savedDraft&&dispatcher)setDraft(JSON.parse(savedDraft));}catch{}await fetchReview();})();const timer=setInterval(()=>void fetchReview(),2000),listener=AppState.addEventListener('change',v=>{if(v==='active')void fetchReview();else if(active)setFresh(false);});return()=>{active=false;clearInterval(timer);listener.remove();};
 },[api,queue,open,key,!!load,!!truck,!!trailer,dispatcher,refresh]);
 useEffect(()=>{if(!draft||!queue)return;const input=axleDraftInput(draft);if(!input.success)return;const confirmed=commands.find(c=>c.path==='/api/review-axles'&&c.status==='synchronized'&&c.expectedVersion===draft.snapshot.truckVersion&&c.body===JSON.stringify(input.data));if(confirmed){setDraft(null);setAck(false);void queue.saveDraft(key+':draft','').catch(e=>setMessage('Saved draft cleanup failed: '+String(e)));setMessage('Assessment synchronized. Review current screening and retained history; dispatch approval remains separate.');}},[commands,draft,queue,key]);
 function choose(next:AxlePair){setPair(next);setPicker(null);void queue?.saveDraft('axle-selection',JSON.stringify(next)).catch(e=>setMessage('Selection not saved: '+String(e)));}
 function edit(next:AxleDraft|null){setDraft(next);setAck(false);void queue?.saveDraft(key+':draft',next?JSON.stringify(next):'').catch(e=>setMessage('Draft not saved: '+String(e)));}
 function button(label:string,action:()=>void,disabled=false){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={action} style={[s.button,disabled&&{opacity:.4}]}><Text style={s.action}>{label}</Text></Pressable>;}
 async function source(doc:AxleSource){setOpening(true);setMessage('');try{await openBillingSource(api,{...doc,filename:doc.extraction?.filename});setOpenedSource(axleSourceKey(doc));setMessage('Source bytes verified. Confirm only after reviewing the document.');}catch(e){setMessage('Source could not open: '+String(e));}finally{setOpening(false);}}
 function confirm(){if(!draft||!ready)return;const action=axleReviewCommand(draft,current,openedSource,ack);if(!action)return;Alert.alert('Record axle assessment?',`${pair.loadId} · ${pair.truckId} + ${pair.trailerId}. This requires assessments for subsequent loads on this truck. Failed results block this combination. Dispatch approval remains separate.`,[{text:'Keep reviewing',style:'cancel'},{text:'Record assessment',onPress:()=>{const now=latest.current,next=now.draft&&axleReviewCommand(now.draft,now.current,now.openedSource,now.ack);if(!now.ready||Date.now()-Date.parse(now.savedAt)>6000||AppState.currentState!=='active'||JSON.stringify(next)!==JSON.stringify(action)){setMessage('Evidence changed. Refresh and start a current review.');return;}void send('/api/review-axles',action.body,action.version,'Record axle assessment '+pair.loadId).then(()=>{setAck(false);setMessage('Assessment saved to Activity. It remains pending until the server confirms it.');setRefresh(v=>v+1);}).catch(e=>setMessage(String(e)));}}]);}
 const parsed=draft&&axleDraftInput(draft);let result:ReturnType<typeof calculateAxles>|undefined;if(parsed?.success)try{result=calculateAxles(parsed.data.configuration,draft!.snapshot.weightLb,parsed.data.cargoCgFromKingpinM);}catch{}
 const doc=draft?.snapshot.documents.find(d=>d.id===draft.documentId),stale=!!draft&&!!draft.documentId&&!axleDraftCurrent(draft,current);
 const assigned=state.assignments.filter(a=>['offered','accepted','completed'].includes(a.status));
 return <View style={s.card}><Text style={s.heading}>Axle loading evidence</Text>{button(open?'Close axle review':'Open axle review',()=>setOpen(!open))}{open?<><Text style={s.body}>Compare gross and axle-group weight using source-reviewed configuration. Static calculations do not certify legal clearance.</Text>{dispatcher?<>{(['loadId','truckId','trailerId'] as const).map(k=><View key={k}>{button(`Choose ${k==='loadId'?'load':k==='truckId'?'truck':'trailer'} · ${pair[k]||'none'}`,()=>setPicker(picker===k?null:k))}{picker===k?(k==='loadId'?state.loads:state.resources.filter(r=>r.kind===(k==='truckId'?'truck':'trailer'))).map(r=><View key={r.id}>{button(`Select ${r.id}`,()=>choose({...pair,[k]:r.id}))}</View>):null}</View>)}</>:assigned.map(a=><View key={a.id}>{button(`${a.loadId} · ${a.truckId} · ${a.trailerId}`,()=>choose({loadId:a.loadId,truckId:a.truckId,trailerId:a.trailerId}))}</View>)}{!dispatcher&&!assigned.length?<Text>No assigned load evidence available.</Text>:null}{savedAt?<Text style={s.small}>Downloaded {at(savedAt)} · {online&&fresh?'Synchronized':'Cached; reconnect before recording'}</Text>:null}{message?<Text accessibilityLiveRegion="polite" style={s.warning}>{message}</Text>:null}{!online?<Text style={s.warning}>Offline. Saved drafts and history remain on this device.</Text>:null}
 {data?<><Text style={s.label}>{online&&fresh?'Current':'Cached'} screening · {data.proof.eligible?'eligible under supported checks':'held for review'}</Text>{data.proof.reasons.map(r=><Text key={r} style={s.warning}>{r}</Text>)}{data.proof.note?<Text style={s.small}>{data.proof.note}</Text>:null}{data.proof.result?<Result result={data.proof.result}/>:null}{button(history?'Hide assessment history':`Show assessment history (${data.history.length})`,()=>setHistory(!history))}{history?data.history.map(h=>{const source=documents.find(d=>d.id===h.body.document.id&&d.version===h.body.document.version&&d.sha256===h.body.document.sha256);return <View key={h.id} style={s.section}><Text style={s.label}>Revision {h.revision} · {h.body.result.eligible?'configured limits passed':'configured limit exceeded'}</Text><Text>{h.body.input.reason}</Text><Text>{h.body.input.sourceNote}</Text><Text style={s.small}>{h.reviewed_by} · {at(h.recorded_at)} · source v{h.body.document.version}</Text><Text selectable style={s.small}>SHA256 {h.body.document.sha256}</Text>{source?button('Open revision '+h.revision+' source',()=>void sourceOpen(source),!online||opening):<Text style={s.warning}>Current source revision differs; original identity is retained.</Text>}<Result result={h.body.result}/></View>; }):null}
 {dispatcher&&!draft?<>{!documents.length?<Text style={s.warning}>Upload a same-load supporting source on dispatcher web first.</Text>:null}{button('Start axle assessment',()=>{if(current)edit({snapshot:current,values:{},documentId:'',sourceNote:'',reason:''});},!ready||!documents.length)}</>:null}</>:null}
 {dispatcher&&draft?<View style={s.section}><Text style={s.label}>Saved assessment draft · {draft.snapshot.loadId}</Text><Text style={s.small}>{draft.snapshot.weightLb.toLocaleString('en-CA')} lb stored payload. Empty masses describe the coupled combination once. Equalized groups only; cargo and fifth wheel must stay within supported spans.</Text>{button('Discard draft & use current evidence',()=>{edit(null);setOpenedSource('');})}{data?.history[0]?button('Copy previous inputs for rechecking',()=>edit({...draft,values:previousAxleValues(data.history[0].body.input)}),!ready):null}{draft.snapshot.documents.map(d=><View key={d.id}>{button(`${d.id===draft.documentId?'Selected source':'Select source'} · ${d.extraction?.filename??d.id} · v${d.version}`,()=>{edit({...draft,documentId:d.id});setOpenedSource('');})}</View>)}{doc?<><Text selectable style={s.small}>SHA256 {doc.sha256}</Text>{button(opening?'Opening source…':'Open assessment source',()=>void sourceOpen(doc),!online||opening||stale)}</>:null}{axleFields.map(([k,label])=><View key={k} style={s.field}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} keyboardType="decimal-pad" value={draft.values[k]??''} onChangeText={text=>edit({...draft,values:{...draft.values,[k]:text}})} style={s.input}/></View>)}<Text style={s.label}>Source evidence note</Text><TextInput accessibilityLabel="Axle source evidence note" multiline style={s.note} value={draft.sourceNote} onChangeText={sourceNote=>edit({...draft,sourceNote})}/><Text style={s.label}>Assessment reason</Text><TextInput accessibilityLabel="Axle assessment reason" multiline style={s.note} value={draft.reason} onChangeText={reason=>edit({...draft,reason})}/>{result?<Result result={result}/>:<Text style={s.warning}>Complete valid geometry, positive masses, whole axle counts1–3 and substantive source/reason notes to calculate.</Text>}{stale?<Text style={s.warning}>Evidence changed since this draft. Discard it and review current versions.</Text>:null}<Text style={s.warning}>Recording activates required assessments for subsequent loads on this truck. Changing configuration invalidates earlier assessments. Failed results are retained and block dispatch.</Text><View style={s.toggle}><Switch accessibilityLabel="Confirm axle source review" value={ack} disabled={!ready||stale||!doc||openedSource!==axleSourceKey(doc)} onValueChange={setAck}/><Text style={[s.body,{flex:1}]}>I reviewed the source and equalized configuration. These are modeled loads, not scale measurements or legal clearance.</Text></View>{doc&&openedSource!==axleSourceKey(doc)?<Text style={s.warning}>Open the current source before confirming review.</Text>:null}{button('Review axle recording',confirm,!ready||!axleReviewCommand(draft,current,openedSource,ack))}</View>:null}{pending?<Text style={s.warning}>Axle assessment pending. The original command survives app restart and reconnect.</Text>:null}</>:null}</View>;
 function sourceOpen(doc:AxleSource){return source(doc);}
}
const s=StyleSheet.create({card:{padding:20,borderRadius:16,backgroundColor:colors.white,gap:14},heading:{fontSize:21,fontWeight:'700'},label:{fontSize:15,fontWeight:'700',lineHeight:23},body:{fontSize:14,lineHeight:22},small:{fontSize:12,lineHeight:19,color:colors.muted},warning:{fontSize:13,lineHeight:21,color:colors.orangeInk},button:{minHeight:48,padding:12,backgroundColor:colors.amber,borderRadius:8,justifyContent:'center'},action:{fontSize:14,fontWeight:'600',color:colors.ink},section:{gap:12,paddingTop:16,borderTopWidth:1,borderTopColor:colors.border},group:{gap:6,padding:10,borderWidth:1,borderColor:colors.border,borderRadius:8},field:{gap:6},input:{minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:8,padding:12},note:{minHeight:90,borderWidth:1,borderColor:colors.border,borderRadius:8,padding:12,textAlignVertical:'top'},toggle:{flexDirection:'row',gap:10,alignItems:'center'}});
