import React,{useEffect,useRef,useState} from 'react';
import {Alert,AppState,Pressable,StyleSheet,Switch,TextInput,View} from 'react-native';
import {Text,colors} from './Design';
import {billingApproval,billingDecision,sourceKey,type BillingReview} from './billing-review';
import {openBillingSource} from './billing-source';
import type {Api,State} from './api';
import type {Queue,Command} from './queue';
const time=(at?:string|null)=>at?new Date(at).toLocaleString('en-CA',{timeZone:'America/Toronto',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+' ET':'Unavailable';
const money=(cents:number,currency='CAD')=>new Intl.NumberFormat('en-CA',{style:'currency',currency}).format(cents/100);
type Props={api:Api;queue:Queue|null;state:State;commands:Command[];online:boolean;send:(path:string,body:unknown,version:number,label:string)=>Promise<void>};
export function BillingReviews({api,queue,state,commands,online,send}:Props){
 const [open,setOpen]=useState(false),[selected,setSelected]=useState(''),[data,setData]=useState<BillingReview|null>(null),[savedAt,setSavedAt]=useState(''),[fresh,setFresh]=useState(false),[message,setMessage]=useState(''),[note,setNote]=useState(''),[ack,setAck]=useState(false),[openedSource,setOpenedSource]=useState(''),[opening,setOpening]=useState(false),[refresh,setRefresh]=useState(0);
 const latest=useRef({data,online,fresh,savedAt,note,ack,openedSource,commands});latest.current={data,online,fresh,savedAt,note,ack,openedSource,commands};
 const visit=state.visits.find(v=>v.id===selected),dispatcher=api.identity.role==='dispatcher';
 useEffect(()=>{let active=true,running=false;setData(null);setFresh(false);setSavedAt('');setNote('');setAck(false);setOpenedSource('');setMessage('');if(!dispatcher||!open||!visit||!queue)return;const key=`billing-review:${selected}`;
 async function load(){if(running||AppState.currentState!=='active')return;running=true;try{const result=await api.request(`/api/visit-time-review?visitId=${selected}`);if(result.status!==200){if([401,403,404].includes(result.status)){await queue!.saveDraft(key,'');if(active)setData(null);}throw new Error(result.body.error?.message??`HTTP ${result.status}`);}if(result.body.visit?.id!==selected)throw new Error('Visit evidence scope mismatch');const at=new Date().toISOString();await queue!.saveDraft(key,JSON.stringify({data:result.body,savedAt:at}));if(active){setData(result.body);setSavedAt(at);setFresh(true);setMessage(old=>old.startsWith('Evidence unavailable:')?'':old);}}catch(e){if(active){setFresh(false);setMessage(`Evidence unavailable: ${e instanceof Error?e.message:String(e)}. Saved history remains dated.`);}}finally{running=false;}}
 void(async()=>{try{const saved=await queue.draft(key);if(saved){const cached=JSON.parse(saved);if(active&&cached.data.visit.id===selected){setData(cached.data);setSavedAt(cached.savedAt);}}const draft=await queue.draft(`billing-note:${selected}`);if(active)setNote(draft);}catch{}await load();})();
 const timer=setInterval(()=>{void load();},2000),listener=AppState.addEventListener('change',v=>{if(v==='active')void load();else if(active)setFresh(false);});return()=>{active=false;clearInterval(timer);listener.remove();};
 },[api,queue,open,selected,!!visit,dispatcher,refresh]);
 const decision=data?billingDecision(data):null,pending=commands.some(c=>c.status==='pending'&&c.path==='/api/approve-invoice'&&data?.invoices.some(i=>c.body.includes(i.id)));
 const ready=online&&fresh&&!pending&&!opening&&!!visit;
 function button(label:string,onPress:()=>void,disabled=false){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={[s.button,disabled&&{opacity:.4}]}><Text style={s.action}>{label}</Text></Pressable>;}
 function confirm(){if(!data)return;const fingerprint=data.fingerprint,body=billingApproval(data,note,ack,openedSource),invoice=decision?.invoice;if(!body||!invoice||!ready)return;
 Alert.alert('Approve detention revision?',`${data.visit.load_id} · ${money(invoice.body.amountCents,invoice.body.currency)} · revision ${invoice.revision}\n${decision?.correction?'Reviewed document times supersede GPS for billing.':'Billing uses observed GPS samples.'}\nPrior invoices remain historical revisions. This does not issue payment.`,[{text:'Keep reviewing',style:'cancel'},{text:'Approve revision',onPress:()=>{const now=latest.current,currentBody=now.data&&billingApproval(now.data,now.note,now.ack,now.openedSource),queued=now.commands.some(c=>c.status==='pending'&&c.path==='/api/approve-invoice'&&c.body.includes(invoice.id));if(!now.online||!now.fresh||Date.now()-Date.parse(now.savedAt)>6000||AppState.currentState!=='active'||now.data?.fingerprint!==fingerprint||!currentBody||JSON.stringify(currentBody)!==JSON.stringify(body)||queued){setMessage('Evidence changed. Refresh and review the latest draft.');return;}void send('/api/approve-invoice',body,invoice.revision,`Approve detention revision ${invoice.revision}`).then(()=>{setAck(false);setRefresh(v=>v+1);}).catch(e=>setMessage(String(e)));}}]);}
 if(!dispatcher)return null;
 return <View style={s.card}><Text style={s.heading}>Detention evidence & billing</Text>{button(open?'Close billing review':'Open billing review',()=>setOpen(!open))}{open?<><Text style={s.body}>Review the visit and its configured terms. Correct conflicting times on dispatcher web; approve the resulting draft here.</Text>{state.visits.map(v=><View key={v.id}>{button(`${v.load_id} · ${v.stop_id} · ${time(v.arrival)}${selected===v.id?' · Selected':''}`,()=>setSelected(v.id))}</View>)}{!state.visits.length?<Text>No observed visits yet.</Text>:null}{selected?<Text style={s.small}>Downloaded {time(savedAt)} · {online&&fresh?'Synchronized':'Saved history; reconnect before approval'}</Text>:null}{!online?<Text style={s.warning}>Offline. History remains available; approval needs current evidence.</Text>:null}{message?<Text accessibilityLiveRegion="polite" style={s.warning}>{message}</Text>:null}{data&&decision?<>
 <View style={s.evidence}><Text style={s.label}>Original GPS observations</Text><Text style={s.body}>{time(data.visit.arrival)} → {time(data.visit.departure)}</Text><Text selectable style={s.small}>Samples: {data.visit.arrival_event} → {data.visit.departure_event??'No departure'}</Text><Text style={s.warning}>GPS samples do not certify exact boundary crossing times.</Text></View>
 {decision.correction?<View style={s.evidence}><Text style={s.label}>Reviewed document times</Text><Text style={s.body}>{time(data.effective.arrivalAt)} → {time(data.effective.departureAt)}</Text><Text style={s.body}>{decision.correction.body.reason}</Text><Text style={s.body}>{decision.correction.body.sourceNote}</Text><Text style={s.small}>{decision.source?.filename} · source v{decision.source?.version}{'\n'}Reviewed by {decision.correction.body.reviewedBy} · {time(decision.correction.body.recordedAt)}</Text><Text selectable style={s.small}>SHA256 {decision.source?.sha256}</Text>{button(opening?'Opening source…':'Open supporting source',()=>{const source=decision.source;if(!source)return;setOpening(true);setMessage('');void openBillingSource(api,source).then(()=>{setOpenedSource(sourceKey(source));setMessage('Source bytes verified. Confirm below only after reviewing the document.');}).catch(e=>setMessage(`Source could not open: ${String(e)}. Review remains incomplete.`)).finally(()=>setOpening(false));},!ready||!decision.source)}</View>:null}
 {decision.invoice?<View style={s.evidence}><Text style={s.label}>{decision.invoice.status==='approved'?'Approved':'Draft'} revision {decision.invoice.revision} · {money(decision.invoice.body.amountCents,decision.invoice.body.currency)}</Text><Text style={s.body}>{decision.invoice.body.dwellMinutes} reviewed minutes · {decision.invoice.body.billableMinutes} billable minutes</Text><Text style={s.body}>{decision.invoice.body.contract?.free_minutes} free minutes · {money(decision.invoice.body.contract?.rate_cents_per_hour??0,decision.invoice.body.currency)} / hour</Text><Text style={s.small}>Confident exit and return are separate visits. Free time applies to each observed visit. Prior approved revisions are history, not additive charges.</Text></View>:null}
 {decision.invoice?.status==='draft'?<><Text style={s.label}>Evidence review note</Text><TextInput accessibilityLabel="Billing evidence review note" multiline style={s.input} value={note} onChangeText={text=>{setNote(text);void queue?.saveDraft(`billing-note:${selected}`,text).catch(e=>setMessage(`Note not saved: ${String(e)}`));}}/><View style={s.toggle}><Switch accessibilityLabel="Confirm billing evidence review" value={ack} onValueChange={setAck} disabled={!ready}/><Text style={[s.body,{flex:1}]}>I reviewed GPS uncertainty, same-stop evidence and configured terms{decision.correction?', plus the corrected document times and supporting source':''}.</Text></View>{decision.source&&openedSource!==sourceKey(decision.source)?<Text style={s.warning}>Open and review the supporting source before approval.</Text>:null}{decision.reasons.map(r=><Text key={r} style={s.warning}>{r}</Text>)}{button('Review billing approval',confirm,!ready||!billingApproval(data,note,ack,openedSource))}</>:null}
 {pending?<Text style={s.warning}>Billing approval pending. The saved command remains here until the server confirms it.</Text>:null}<Text style={s.label}>Retained invoice history</Text>{data.invoices.map(i=><Text key={i.id} style={s.body}>{i.status} · revision {i.revision} · {money(i.body.amountCents,i.body.currency)} · {i.body.precision==='reviewed_document_times'?'document times':'GPS observations'}</Text>)}<Text style={s.small}>{data.history.length} retained time correction(s). Originals and prior approvals are preserved.</Text>
 </>:null}</>:null}</View>;
}
const s=StyleSheet.create({card:{padding:20,borderRadius:16,backgroundColor:colors.white,gap:14},heading:{fontSize:21,fontWeight:'700'},label:{fontSize:15,fontWeight:'700',lineHeight:23},body:{fontSize:14,lineHeight:22},small:{fontSize:12,lineHeight:19,color:colors.muted},warning:{fontSize:13,lineHeight:21,color:colors.orangeInk},button:{minHeight:48,padding:12,backgroundColor:colors.amber,borderRadius:8,justifyContent:'center'},action:{fontSize:14,fontWeight:'600',color:colors.ink},evidence:{gap:10,paddingTop:16,borderTopWidth:1,borderTopColor:colors.border},input:{minHeight:100,borderWidth:1,borderColor:colors.border,borderRadius:8,padding:12,textAlignVertical:'top'},toggle:{flexDirection:'row',gap:10,alignItems:'center'}});
