import React,{useEffect,useRef,useState} from 'react';
import {Alert,AppState,Pressable,StyleSheet,View} from 'react-native';
import {Text,colors} from './Design';
import {ClosureMap} from './ClosureMap';
import {closureDecision,type ClosureReview} from './closure-review';
import type {Api,State} from './api';import type {Queue,Command} from './queue';
const time=(at?:string)=>at?new Date(at).toLocaleString('en-CA',{timeZone:'America/Toronto',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+' ET':'Unavailable';
type Props={api:Api;queue:Queue|null;state:State;commands:Command[];online:boolean;send:(path:string,body:unknown,version:number,label:string)=>Promise<void>};
export function ClosureReviews({api,queue,state,commands,online,send}:Props){
 const [open,setOpen]=useState(false),[selected,setSelected]=useState(''),[data,setData]=useState<ClosureReview|null>(null),[savedAt,setSavedAt]=useState(''),[fresh,setFresh]=useState(false),[message,setMessage]=useState(''),[refresh,setRefresh]=useState(0);
 const trips=state.assignments.filter(t=>t.status==='accepted'),trip=trips.find(t=>t.id===selected),dispatcher=api.identity.role==='dispatcher';
 const current=useRef({data,state,fresh,online});current.current={data,state,fresh,online};
 useEffect(()=>{let active=true,running=false;setData(null);setFresh(false);setSavedAt('');setMessage('');if(!open||!trip||!queue)return;const key=`closure-review:${trip.id}`;
 async function load(){if(running||AppState.currentState!=='active')return;running=true;try{const result=await api.request(`/api/route-reviews?assignmentId=${trip!.id}`);if(result.status!==200){if([401,403,404].includes(result.status)){await queue!.saveDraft(key,'');if(active)setData(null);}throw new Error(result.body.error?.message??`HTTP ${result.status}`);}if(result.body.assignmentId!==trip!.id)throw new Error('Trip evidence scope mismatch');const at=new Date().toISOString();await queue!.saveDraft(key,JSON.stringify({data:result.body,savedAt:at}));if(active){setData(result.body);setSavedAt(at);setFresh(true);setMessage('');}}catch(e){if(active){setFresh(false);setMessage(`Route update unavailable: ${e instanceof Error?e.message:String(e)}. Saved evidence remains dated.`);}}finally{running=false;}}
 void(async()=>{try{const saved=await queue.draft(key);if(saved){const cached=JSON.parse(saved);if(active&&cached.data.assignmentId===trip.id){setData(cached.data);setSavedAt(cached.savedAt);}}}catch{}await load();})();const timer=setInterval(()=>{void load();},2000);const listener=AppState.addEventListener('change',v=>{if(v==='active')void load();});return()=>{active=false;clearInterval(timer);listener.remove();};
 },[open,selected,!!trip,queue,api,refresh]);
 const pending=commands.some(c=>c.status==='pending'&&['/api/approve-route','/api/rehearse-route','/api/acknowledge-route'].includes(c.path)&&(c.body.includes(selected)||data?.revisions.some(r=>c.body.includes(r.id))));
 const ready=online&&fresh&&!pending&&!!trip;
 function action(label:string,fn:()=>void,disabled=false){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={fn} style={[s.button,disabled&&{opacity:.4}]}><Text style={s.action}>{label}</Text></Pressable>;}
 function confirm(r:ClosureReview['revisions'][number],receipt:boolean){Alert.alert(receipt?'Confirm route receipt?':'Approve route revision?',`${trip?.loadId} · ${trip?.driverId} / ${trip?.truckId}\n${r.body.drivingMinutes??'?'} min driving · ${r.body.dutyMinutes??'?'} min on duty\n${r.body.hasToll?'Includes toll segments; charges not estimated.':''}\n${receipt?'Confirm you received and reviewed this route. Receipt does not start navigation.':'The server rechecks current constraints. Driver receipt remains separate.'}`,[{text:'Keep reviewing',style:'cancel'},{text:receipt?'Confirm receipt':'Approve revision',onPress:()=>{const now=current.current,latest=now.data?.revisions.find(x=>x.id===r.id),decision=now.data&&latest?closureDecision(now.data,now.state,latest):null;if(!now.online||!now.fresh||latest?.revision!==r.revision||!(receipt?decision?.canReceive:decision?.canApprove)){setMessage('Evidence changed. Refresh and review the latest revision.');return;}void send(receipt?'/api/acknowledge-route':'/api/approve-route',receipt?{routeRevisionId:r.id,acknowledgeReceipt:true}:{routeRevisionId:r.id,acknowledgeModeledRoute:true},r.revision,receipt?'Confirm route receipt':'Approve route revision').then(()=>setRefresh(v=>v+1));}}]);}
 return <View style={s.card}><Text style={s.heading}>Road closures & route reviews</Text>{action(open?'Close route reviews':'Open route reviews',()=>setOpen(!open))}{open?<><Text style={s.body}>{dispatcher?'Choose an accepted trip. Record new sourced closures on dispatcher web, then rehearse and approve here.':'Review the dispatcher response for your accepted trip.'}</Text>{trips.map(t=><View key={t.id}>{action(`${t.loadId} · ${t.driverId} · ${t.truckId}${selected===t.id?' · Selected':''}`,()=>setSelected(t.id))}</View>)}{!trips.length?<Text>No accepted trips.</Text>:null}{selected?<Text style={s.small}>Downloaded {time(savedAt)} · {fresh&&online?'Synchronized':'Saved evidence; reconnect before acting'}</Text>:null}{message?<Text accessibilityLiveRegion="polite" style={s.warning}>{message}</Text>:null}{data&&trip?<><Text style={s.label}>{data.closures.length} retained closure observations</Text>{data.closures.map(c=><View key={c.id} style={s.evidence}><Text style={s.body}>{c.reason}</Text><Text style={s.small}>{time(c.observed_at)} · Source: {c.source_ref}</Text></View>)}{dispatcher&&data.closures.length?action('Rehearse remaining route',()=>void send('/api/rehearse-route',{assignmentId:trip.id},trip.version,'Rehearse remaining route').then(()=>setRefresh(v=>v+1)),!ready):null}{data.revisions.map(r=>{const decision=closureDecision(data,state,r);return <View key={r.id} style={s.evidence}><Text style={s.label}>{r.status==='unresolved'?'No feasible revision':r.status==='approved'?'Approved route revision':'Proposed route revision'} · r{r.revision}</Text>{r.body.drivingMinutes!==undefined?<Text style={s.body}>{r.body.drivingMinutes} min driving · {r.body.dutyMinutes} min on duty{ '\n'}Complete {time(r.body.completionAt)}</Text>:null}{r.body.route?<ClosureMap route={r.body.route}/>:null}{r.body.hasToll?<Text style={s.warning}>Includes toll segments. Charges are not estimated.</Text>:null}{r.body.reasons.map((reason,i)=><Text key={i} style={s.warning}>{reason}</Text>)}{decision.stale?<Text style={s.warning}>Evidence changed. This revision requires another dispatcher review.</Text>:null}{decision.receipt?<Text style={s.success}>Driver receipt recorded {time(decision.receipt.acknowledged_at)}. Adoption and execution remain separate.</Text>:null}{dispatcher&&r.status==='pending'?action('Review route approval',()=>confirm(r,false),!ready||!decision.canApprove):null}{!dispatcher&&decision.canReceive?action('Review route receipt',()=>confirm(r,true),!ready):null}</View>;})}</>:null}{pending?<Text accessibilityLiveRegion="polite" style={s.warning}>Route action pending. It remains saved until the server confirms it.</Text>:null}</>:null}</View>;
}
const s=StyleSheet.create({card:{padding:20,borderRadius:16,backgroundColor:colors.white,gap:14},heading:{fontSize:21,fontWeight:'700'},label:{fontSize:15,fontWeight:'700',lineHeight:23},body:{fontSize:14,lineHeight:22},small:{fontSize:12,lineHeight:19,color:colors.muted},warning:{fontSize:13,lineHeight:21,color:colors.orangeInk},success:{fontSize:14,lineHeight:22,color:colors.success},button:{minHeight:48,padding:12,backgroundColor:colors.amber,borderRadius:8,justifyContent:'center'},action:{fontSize:14,fontWeight:'600',color:colors.ink},evidence:{gap:10,paddingTop:16,borderTopWidth:1,borderTopColor:colors.border}});
