import React,{useEffect,useState} from 'react';
import {AccessibilityInfo,Image,StyleSheet,Text as NativeText,View,type TextProps} from 'react-native';
export function useReducedMotion(){const [reduced,setReduced]=useState(true);useEffect(()=>{void AccessibilityInfo.isReduceMotionEnabled().then(setReduced);const listener=AccessibilityInfo.addEventListener('reduceMotionChanged',setReduced);return()=>listener.remove();},[]);return reduced;}
export function Text({style,...props}:TextProps){const flat=StyleSheet.flatten(style);const weight=String(flat?.fontWeight??'400');const fontFamily=flat?.fontFamily??(weight==='700'||weight==='800'?'Manrope-Bold':weight==='600'?'Manrope-SemiBold':weight==='500'?'Manrope-Medium':'Manrope-Regular');return <NativeText {...props} style={[{fontFamily,color:'#191B1D'},style,{fontFamily,fontWeight:'normal'}]}/>;}
export const colors={bg:'#F5F3ED',ivory:'#F5F3ED',white:'#FFFFFF',ink:'#191B1D',muted:'#666962',primary:'#191B1D',border:'#DCDDD5',amber:'#F5E8DB',orange:'#E65C32',orangeInk:'#AC3716',red:'#A23B30',success:'#2E6754'};
export function facilityLabel(name:string,synthetic=false){return synthetic?name.replace(/\s*·\s*demo location$/i,''):name;}
export function OrderedStop({index,title,name,time,synthetic=false,last=false,children}:{index:number;title:string;name:string;time?:string;synthetic?:boolean;last?:boolean;children?:React.ReactNode}){return <View style={{flexDirection:'row',gap:12}}><View style={{width:26,alignItems:'center'}}><View style={{width:26,height:26,borderRadius:13,borderWidth:1,borderColor:colors.orange,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:11,color:colors.orangeInk,fontFamily:'IBMPlexMono'}}>{String(index+1).padStart(2,'0')}</Text></View>{!last?<View style={{width:1,flex:1,backgroundColor:colors.orange,opacity:.45}}/>:null}</View><View style={{flex:1,paddingBottom:last?0:14,marginBottom:last?0:14,borderBottomWidth:last?0:1,borderBottomColor:colors.border,gap:6}}><View style={{flexDirection:'row',alignItems:'baseline',justifyContent:'space-between',gap:8}}><Text style={{fontSize:14,fontWeight:'700',flex:1}}>{title}</Text>{time?<Text style={{fontSize:11,lineHeight:16,color:colors.muted,textAlign:'right',maxWidth:128}}>{time}</Text>:null}</View><Text accessibilityLabel={name} style={{fontSize:16,lineHeight:22}}>{facilityLabel(name,synthetic)}</Text>{children}</View></View>}
export function Brand({compact=false}:{compact?:boolean}){return <View style={s.brand}><View style={{backgroundColor:colors.ink,padding:compact?0:5,borderRadius:6}}><Image accessible={false} source={require('../assets/roadstar-mark.png')} style={{width:27,height:30}}/></View><Text style={[s.word,{color:compact?colors.ivory:colors.ink}]}>RoadStar</Text></View>}
export function SectionHeading({eyebrow,title,detail}:{eyebrow:string;title:string;detail?:string}){return <View style={{gap:5}}><Text style={s.eyebrow}>{eyebrow}</Text><Text key={title} style={[s.title,{alignSelf:'stretch'}]}>{title}</Text>{detail?<Text style={s.detail}>{detail}</Text>:null}</View>}
export function RouteRail({pickup,delivery,dark=false,completedPickup=false}:{pickup:string;delivery:string;dark?:boolean;completedPickup?:boolean}){return <View style={{gap:0}}>{[pickup,delivery].map((name,i)=><View key={i} style={s.stop}><View style={s.rail}><View style={[s.dot,i===0?{backgroundColor:completedPickup?'#78A38C':colors.orange}:null]}/>{i===0?<View style={s.line}/>:null}</View><View style={{flex:1,paddingBottom:i===0?24:0,gap:4}}><Text style={[s.caption,{color:dark?'#B5B7B2':colors.muted}]}>{i===0?'01 / ORIGIN':'02 / DESTINATION'}</Text><Text style={[s.place,{color:dark?colors.ivory:colors.ink}]}>{name}</Text></View></View>)}</View>}
const s=StyleSheet.create({brand:{flexDirection:'row',alignItems:'center',gap:11,minHeight:36},mark:{width:27,height:30,overflow:'hidden'},routeA:{position:'absolute',left:4,top:2,width:5,height:29,backgroundColor:colors.orange,transform:[{skewX:'-20deg'}]},routeB:{position:'absolute',left:16,top:1,width:5,height:20,backgroundColor:colors.orange,transform:[{rotate:'40deg'}]},routeC:{position:'absolute',left:18,top:14,width:5,height:19,backgroundColor:colors.orange,transform:[{rotate:'-35deg'}]},word:{fontSize:21,fontWeight:'700',letterSpacing:-1},eyebrow:{fontSize:10,fontWeight:'700',letterSpacing:2,color:colors.orangeInk},title:{fontSize:26,lineHeight:32,fontWeight:'700',letterSpacing:-1.2,color:colors.ink},detail:{fontSize:13,color:colors.muted},stop:{flexDirection:'row',gap:14},rail:{width:14,alignItems:'center'},dot:{height:12,width:12,borderRadius:6,borderWidth:2,borderColor:colors.orange,marginTop:3},line:{width:2,flex:1,backgroundColor:'#666962',marginTop:5,marginBottom:4},caption:{fontSize:9,letterSpacing:1.5,fontWeight:'600'},place:{fontSize:18,lineHeight:24,fontWeight:'600',letterSpacing:-.3}});
