import React,{useEffect,useState} from 'react';
import {Pressable,View,StyleSheet} from 'react-native';
import {Text,colors} from './Design';
import type {Api,State} from './api';
import type {Queue} from './queue';
import {mileagePath,mileageMatches} from '../../../packages/domain/src/tracking';
import type {MileageReport} from '../../../packages/domain/src/tracking';
const km=(value:number|null)=>value===null?'Unknown':`${value.toLocaleString('en-CA',{maximumFractionDigits:2})} km`;
const when=(value:string)=>new Date(value).toLocaleString('en-CA',{timeZone:'America/Toronto',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
export function Mileage({api,queue,state}:{api:Api;queue:Queue|null;state:State}){
 const [selection,setSelection]=useState(''),[expanded,setExpanded]=useState(false),[report,setReport]=useState<MileageReport|null>(null),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0);
 const choices=[...state.assignments.map(a=>({value:`assignment:${a.id}`,label:`Trip ${a.loadId} · ${a.truckId} · ${a.id.slice(0,8)}`})),...(state.workSessions??[]).map(s=>({value:`session:${s.id}`,label:`Session ${s.started_at?when(s.started_at):s.id.slice(0,8)} ET · ${s.ended_at?'Ended':'Active'}`}))];
 const allowed=choices.some(c=>c.value===selection);
 useEffect(()=>{let active=true;setReport(null);setMessage('');if(!selection||!allowed||!queue)return;setLoading(true);void(async()=>{
  try{const saved=await queue.draft(`mileage:${selection}`);if(saved){const cached=JSON.parse(saved);if(active&&mileageMatches(cached,selection))setReport(cached);}
   const result=await api.request(`/api/${mileagePath(selection)}`);if(result.status!==200)throw new Error(result.body.error?.message??`HTTP ${result.status}`);if(!mileageMatches(result.body,selection))throw new Error('Report scope mismatch');await queue.saveDraft(`mileage:${selection}`,JSON.stringify(result.body));if(active){setReport(result.body);setMessage('Downloaded report. Refresh to include newer synchronized observations.');}
  }catch(error){if(active)setMessage(`Report unavailable: ${error instanceof Error?error.message:String(error)}. Any saved report below remains dated; pending observations are not included.`);}finally{if(active)setLoading(false);}
 })();return()=>{active=false;};},[selection,allowed,queue,api,refresh]);
 const visible=allowed&&report&&mileageMatches(report,selection)?report:null;
 return <View style={s.card}><Text style={s.heading}>Trip & session mileage</Text><Text style={s.body}>Recorded distance and coverage for your trips and explicit work sessions.</Text><Pressable accessibilityRole="button" onPress={()=>setExpanded(!expanded)} style={s.button}><Text style={s.action}>{choices.find(c=>c.value===selection)?.label??'Choose mileage report'} {expanded?'−':'+'}</Text></Pressable>{expanded?<View>{choices.length?choices.map(c=><Pressable key={c.value} accessibilityRole="button" onPress={()=>{setSelection(c.value);setExpanded(false);}} style={s.button}><Text style={s.body}>{c.label}</Text></Pressable>):<Text style={s.body}>No trips or work sessions are available.</Text>}</View>:null}
 {selection?<Pressable accessibilityRole="button" accessibilityState={{disabled:loading}} disabled={loading} onPress={()=>setRefresh(n=>n+1)} style={s.button}><Text style={s.action}>{loading?'Refreshing mileage…':'Refresh mileage'}</Text></Pressable>:null}{message?<Text accessibilityLiveRegion="polite" style={s.small}>{message}</Text>:null}
 {visible?<><Text style={s.small}>Report as of {when(visible.asOf)} ET · {visible.samples} retained samples</Text>{visible.evidencePolicy==='occurrence-ordered-v2'?<Text style={s.small}>Occurrence-ordered report · {visible.lateSamples??0} late samples retained. Usable intervals include late evidence; current GPS and source observations are unchanged. {visible.timestampConflictSamples??0} equal-time samples excluded.</Text>:null}{visible.startedAt?<Text style={s.small}>Session {when(visible.startedAt)} → {visible.endedAt?when(visible.endedAt):'Active at report time'} ET</Text>:null}{visible.samples?<><Text style={s.metric}>Odometer increments {km(visible.odometerKm)}</Text><Text style={s.body}>GPS chord estimate {km(visible.gpsChordKm)}</Text>{visible.legs.map(l=><View key={l.assignmentId} style={s.leg}><Text style={s.action}>{l.loadId} · {l.truckId}</Text><Text style={s.small}>{l.provenance.join(', ')} · {l.samples} samples</Text><Text style={s.body}>Odometer {km(l.odometerKm)} · GPS {km(l.gpsChordKm)}</Text><Text style={s.small}>{(l.observedSeconds/60).toFixed(1)} min linked · {l.unlinkedIntervals} excluded intervals · {l.missingOdometerIntervals} linked intervals without usable odometer</Text></View>)}</>:<Text style={s.body}>No retained samples. Distance is unknown.</Text>}<Text style={s.small}>All retained samples at report time. Gaps and unrecorded travel remain unknown. GPS chords are estimates, not road mileage. Trips are never joined. Work sessions are tracking boundaries, not certified HOS shifts.</Text></>:null}
 </View>;
}
const s=StyleSheet.create({card:{backgroundColor:colors.ivory,borderRadius:16,padding:20,gap:12},heading:{fontSize:20,fontWeight:'700',color:colors.ink},body:{fontSize:14,lineHeight:21,color:colors.ink},small:{fontSize:12,lineHeight:19,color:colors.ink},action:{fontSize:14,fontWeight:'600',color:colors.primary},button:{minHeight:48,justifyContent:'center',paddingVertical:10},metric:{fontSize:18,fontWeight:'700',color:colors.ink},leg:{borderTopWidth:1,borderTopColor:colors.ink,paddingTop:12,gap:6}});
