import React,{useState} from 'react';
import {Pressable,StyleSheet,View} from 'react-native';
import {Text,colors} from './Design';
import {driverHeadroom} from '../../../packages/domain/src/open-visit';
import type {State} from './api';
const when=(at:string|null)=>at?new Date(at).toLocaleString('en-CA',{timeZone:'America/Toronto',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+' ET':'Unavailable';
const money=(cents:number,currency='CAD')=>new Intl.NumberFormat('en-CA',{style:'currency',currency}).format(cents/100);
export function OpenDockExposure({state,dispatcher,online,savedAt}:{state:State;dispatcher:boolean;online:boolean;savedAt:string}){
 const [sources,setSources]=useState<Record<string,boolean>>({});
 if(!dispatcher)return null;
 const estimates=state.openVisitEstimates;
 return <View style={s.card}><Text style={s.eyebrow}>OPEN DOCK VISITS</Text><Text style={s.title}>Waiting & duty headroom</Text><Text style={s.small}>Downloaded {when(savedAt)}. Estimates end at recorded GPS evidence.</Text>{!online?<Text accessibilityLiveRegion="polite" style={s.warning}>Offline · saved observation only. Amounts and HOS are not updating. Reconnect to check current evidence.</Text>:null}{estimates===undefined?<Text style={s.body}>Open-visit estimates are unavailable in this snapshot. Refresh when connected.</Text>:!estimates.length?<Text style={s.body}>No open dock visits in this snapshot.</Text>:estimates.map(e=>{const visit=state.visits.find(v=>v.id===e.visitId),driver=state.resources.find(r=>r.id===e.driverId);return <View key={e.visitId} style={s.evidence}><Text style={s.label}>{visit?.load_id??'Shipment'} · {visit?.stop_id??'Stop'}</Text><Text style={s.warning}>{driverHeadroom(driver?.budget)}</Text><Text style={s.small}>{driver?.provenance==='synthetic'?'Synthetic scenario · ':''}Driver {e.driverId}. On-duty waiting consumes HOS headroom.</Text>{e.status==='estimate'?<><Text style={s.amount}>{online?'Provisional detention':'Saved provisional detention'} · {money(e.amountCents!,e.currency)}</Text><Text style={s.body}>{e.dwellMinutes} observed minutes · {e.billableMinutes} beyond the {e.contract?.freeMinutes}-minute allowance.</Text><Text style={s.small}>{e.contract?.id} v{e.contract?.version} · {money(e.contract!.rateCentsPerHour,e.currency)} per hour</Text></>:<Text style={s.label}>Detention estimate held</Text>}<Text style={s.body}>{e.reason}</Text><Text style={s.small}>Evidence through {when(e.evidenceAt)} · {e.evidenceAgeSeconds??'Unknown'} seconds old at the snapshot.</Text><Text style={s.small}>This estimate creates no invoice or departure. Billing approval is separate.</Text><Pressable accessibilityRole="button" accessibilityLabel={sources[e.visitId]?'Hide open-visit sources':'Show open-visit sources'} onPress={()=>setSources(v=>({...v,[e.visitId]:!v[e.visitId]}))} style={s.button}><Text style={s.label}>{sources[e.visitId]?'Hide open-visit sources':'Show open-visit sources'}</Text></Pressable>{sources[e.visitId]?<><Text selectable style={s.small}>Arrival: {e.arrivalEvent}</Text><Text selectable style={s.small}>Latest: {e.evidenceId??'Unavailable'}</Text><Text style={s.small}>Visit remains open. No observed departure.</Text></>:null}</View>;})}</View>;
}
const s=StyleSheet.create({card:{padding:20,borderRadius:16,backgroundColor:colors.white,gap:12},eyebrow:{fontSize:10,letterSpacing:1.5,color:colors.orangeInk},title:{fontSize:21,fontWeight:'700',lineHeight:28},label:{fontSize:14,fontWeight:'700',lineHeight:22},amount:{fontSize:18,fontWeight:'700',lineHeight:27},body:{fontSize:14,lineHeight:22},small:{fontSize:12,lineHeight:19,color:colors.muted},warning:{fontSize:14,lineHeight:22,color:colors.orangeInk},evidence:{gap:10,paddingTop:16,borderTopWidth:1,borderTopColor:colors.border},button:{minHeight:48,padding:12,borderRadius:8,backgroundColor:colors.amber,justifyContent:'center'}});
