import React,{useRef,useState} from 'react';
import {Alert,Modal,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View} from 'react-native';
import type {State} from './api';
import type {Command} from './queue';
import {groupIntent,nextGroupStop,stopCompleted,planIssue,planIntent,plannedTime,type Intent,type TripGroup,type PlanningRun} from './planning';
import {reviewedFacilityNotes} from './facilities';
type Send=(path:string,body:unknown,version:number,label:string)=>Promise<void>;
function Action({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={[styles.button,disabled?{opacity:.45}:null]}><Text style={styles.buttonText}>{label}</Text></Pressable>}
function dispatch(intent:Intent,send:Send){return send(intent.path,intent.body,intent.version,intent.label);}
export function GroupManifest({group,state,commands,send}:{group:TripGroup;state:State;commands:Command[];send:Send}){
 const latest=useRef(state);latest.current=state;const [error,setError]=useState('');const next=nextGroupStop(group,state.stopCompletions??[]);const own=state.actor?.role==='driver'&&state.actor.driverId===group.driver_id;
 const memberIds=new Set(group.body.stops.map(s=>s.assignmentId));const activity=commands.filter(c=>{try{return memberIds.has(JSON.parse(c.body).assignmentId);}catch{return false;}});const pending=activity.some(c=>c.status==='pending');
 function review(action:'accept'|'reject'|'complete'){try{const intent=groupIntent(latest.current,group.id,action);const reviewed={groupVersion:group.version,assignmentId:intent.body.assignmentId,assignmentVersion:intent.version,stopId:intent.body.stopId};setError('');Alert.alert(action==='complete'?'Complete next manifest stop?':`${action==='accept'?'Accept':'Reject'} entire manifest?`,action==='complete'?`${next?.loadId} · ${next?.stop} · ${next?.point.name}. This is a manual execution event, not a detention billing timestamp.`:`This response applies to all ${new Set(group.body.stops.map(s=>s.loadId)).size} loads and every ordered stop. Offline responses remain pending until the server confirms them.`,[{text:'Cancel',style:'cancel'},{text:action==='complete'?'Complete next stop':action==='accept'?'Accept all loads':'Reject all loads',onPress:()=>{try{void dispatch(groupIntent(latest.current,group.id,action,reviewed),send).catch(e=>setError(String(e)));}catch(e){setError(String(e));}}}]);}catch(e){setError(String(e));}}
 return <View style={styles.card}><Text style={styles.eyebrow}>Shared route · one manifest</Text><Text style={styles.title}>{new Set(group.body.stops.map(s=>s.loadId)).size} loads · {group.body.stops.length} ordered stops</Text><Text style={styles.strong}>{group.status} · revision {group.version}</Text><Text>{group.body.driverId} · Truck {group.body.truckId} · Trailer {group.body.trailerId}</Text><Text style={styles.small}>{group.body.provenance} · {group.body.routingEvidence}{'\n'}{group.body.drivingMinutes} modeled driving minutes · {group.body.dutyMinutes} modeled duty minutes</Text><Text selectable style={styles.small}>Manifest {group.id} · {(state.manifests??[]).filter(m=>m.body.groupId===group.id).length} downloaded member records</Text>
 {group.status==='offered'?<><Text style={styles.body}>Review the complete sequence. Acceptance or rejection applies to every load in this manifest.</Text>{own?<><Action label={pending?'Manifest response pending':'Accept entire manifest'} disabled={pending} onPress={()=>review('accept')}/><Action label="Reject entire manifest" disabled={pending} onPress={()=>review('reject')}/></>:null}</>:null}
 {group.status==='accepted'&&next?<View style={styles.stop}><Text style={styles.eyebrow}>Next action</Text><Text style={styles.title}>{next.stop==='pickup'?'Pick up':'Deliver'} {next.loadId}</Text><Text>{next.point.name}</Text>{own?<Action label={pending?'Manifest action pending':'Review next stop completion'} disabled={pending} onPress={()=>review('complete')}/>:null}</View>:null}
 {group.status==='completed'?<Text style={styles.body}>All stops completed. This downloaded manifest remains available for reference.</Text>:null}
 {group.body.stops.map((stop,index)=>{const done=stopCompleted(stop,state.stopCompletions??[]),notes=reviewedFacilityNotes(state.facilityNotes??[],stop.loadId,stop.stopId);return <View style={styles.stop} key={`${stop.assignmentId}:${stop.stopId}`}><Text style={styles.strong}>{index+1}. {stop.loadId} · {stop.stop}</Text><Text>{stop.point.name}</Text><Text style={styles.small}>{done?'Completed':group.status==='accepted'&&next===stop?'Next stop':'Awaiting execution'}</Text>{notes.map((note,i)=><View key={i}><Text style={styles.strong}>Reviewed arrival instructions</Text><Text>{note.instructions}</Text><Text selectable style={styles.small}>Source {note.document_id??'unavailable'} · Reviewed by {note.reviewed_by}</Text></View>)}</View>;})}
 {(group.body.assumptions??[]).map((assumption,i)=><Text key={i} style={styles.small}>Assumption: {assumption}</Text>)}{error?<Text accessibilityRole="alert" style={styles.error}>{error}</Text>:null}{activity.slice(-4).map(c=><Text key={c.id} style={c.status==='failed'?styles.error:styles.small}>{c.label} · {c.status}{c.error?` · ${c.error}`:''}</Text>)}<Text style={styles.small}>Pending commands retain the original ID and version. Failed actions require a fresh review of the manifest.</Text></View>;
}
export function PlanningRecords({state,commands,send}:{state:State;commands:Command[];send:Send}){
 const [review,setReview]=useState<PlanningRun|null>(null),[ack,setAck]=useState(false),[error,setError]=useState('');const latest=useRef(state);latest.current=state;
 const issue=review?planIssue(state,review):null;const pending=commands.some(c=>c.status==='pending'&&c.path==='/api/approve-plan'&&c.body.includes(review?.id??'__none__'));
 function approve(){if(!review)return;try{const intent=planIntent(latest.current,review);void dispatch(intent,send).catch(e=>setError(String(e)));setReview(null);}catch(e){setError(String(e));}}
 return <><Text style={styles.title}>Shared-route planning records</Text><Text style={styles.body}>Review vehicle pairings, ordered stops and unresolved loads. The planning board creates proposals; mobile dispatchers approve them here.</Text>{!(state.planningRuns??[]).length?<Text style={styles.small}>No downloaded planning records.</Text>:null}{[...(state.planningRuns??[])].sort((a,b)=>(b.created_at??'').localeCompare(a.created_at??'')).map(run=><View key={run.id} style={styles.card}><Text style={styles.title}>{run.result.routes.length} routes · {run.result.infeasible_loads.length} unresolved inputs</Text><Text>{run.status} · revision {run.version}</Text><Text style={styles.small}>{plannedTime(run.input.now)} · scenario clock</Text><Action label={run.status==='proposal'?'Review planning proposal':'Review planning record'} onPress={()=>{setAck(false);setError('');setReview(run);}}/>{commands.filter(c=>c.path==='/api/approve-plan'&&c.body.includes(run.id)).slice(-2).map(c=><Text key={c.id} style={c.status==='failed'?styles.error:styles.small}>{c.status}{c.error?` · ${c.error}`:''}</Text>)}</View>)}
 <Modal visible={!!review} animationType="slide" onRequestClose={()=>setReview(null)}><SafeAreaView style={styles.modal}><ScrollView contentContainerStyle={styles.content}>{review?<><Action label="Close planning review" onPress={()=>setReview(null)}/><Text style={styles.title}>Review shared-route {review.status==='proposal'?'proposal':'record'}</Text><Text>{review.status} · revision {review.version} · scenario appointments in Eastern time</Text>{review.result.routes.map((route,i)=>{const vehicle=review.input.vehicles.find(v=>v.id===route.vehicle_id);return <View style={styles.card} key={`${route.vehicle_id}:${i}`}><Text style={styles.title}>Route {i+1}</Text><Text>{vehicle?.driverId??'Unknown driver'} · {vehicle?.truckId??'Unknown truck'} · {vehicle?.trailerId??'Unknown trailer'}</Text><Text style={styles.small}>{route.driving_minutes} modeled driving minutes · {route.duty_minutes} modeled duty minutes</Text>{route.stops.map((stop,index)=><View style={styles.stop} key={`${stop.load_id}:${index}`}><Text style={styles.strong}>{index+1}. {stop.load_id} · {stop.stop}</Text><Text>{state.loads.find(l=>l.id===stop.load_id)?.[stop.stop].name??'Stop unavailable'}</Text><Text style={styles.small}>{plannedTime(review.input.now,stop.minute)}</Text></View>)}</View>;})}{review.result.infeasible_loads.map((item,i)=><Text key={i} style={styles.error}>Unresolved {item.load_id??item.vehicle_id??'input'}: {item.reason}</Text>)}<Text style={styles.small}>Unresolved loads remain unassigned. A bounded search does not prove that no alternative exists.</Text><Text style={styles.strong}>Evidence and modeled assumptions</Text><Text selectable style={styles.small}>{review.result.routing_evidence??'Truck-route evidence unavailable'}{'\n'}{review.result.input_hash??'Input hash unavailable'}</Text>{(review.result.assumptions??[]).map((a,i)=><Text key={i} style={styles.small}>• {a}</Text>)}<Text style={styles.small}>Supplied service duration is split between pickup and delivery.</Text>{review.status==='proposal'?<><Pressable accessibilityRole="checkbox" accessibilityState={{checked:ack}} onPress={()=>setAck(!ack)} style={styles.stop}><Text style={styles.strong}>{ack?'☑':'☐'} I reviewed vehicle pairings, ordered stops, unresolved loads and modeled assumptions.</Text></Pressable>{issue?<Text style={styles.error}>{issue}</Text>:null}<Action label={pending?'Approval pending':'Approve plan and offer manifests'} disabled={!ack||!!issue||pending} onPress={approve}/><Text style={styles.small}>Approval remains pending until the server rechecks current versions, resource commitments and truck-route evidence atomically. Drivers must accept the resulting manifests.</Text></>:null}{error?<Text accessibilityRole="alert" style={styles.error}>{error}</Text>:null}</>:null}</ScrollView></SafeAreaView></Modal></>;
}
const styles=StyleSheet.create({card:{padding:16,gap:12,backgroundColor:'#fff',borderColor:'#c8d3de',borderWidth:1,borderRadius:8},title:{fontSize:20,fontWeight:'700',color:'#20364c'},body:{fontSize:16,lineHeight:24,color:'#20364c'},strong:{fontSize:14,fontWeight:'600',color:'#20364c'},small:{fontSize:13,lineHeight:19,color:'#5c6d7e'},eyebrow:{fontSize:14,fontWeight:'700',color:'#145b8d'},stop:{padding:12,gap:5,backgroundColor:'#f2f5f8',borderRadius:6},button:{minHeight:48,padding:14,borderRadius:8,backgroundColor:'#145b8d',alignItems:'center',justifyContent:'center'},buttonText:{fontSize:15,fontWeight:'600',color:'#fff'},error:{fontSize:13,lineHeight:19,color:'#a32b2b'},modal:{flex:1,backgroundColor:'#f2f5f8',paddingTop:32,paddingBottom:16},content:{padding:20,gap:16,paddingBottom:40}});
