import React from 'react';
import {Alert,Pressable,StyleSheet,View} from 'react-native';
import {Text,colors} from './Design';
import {recoveryState} from './recovery';
import type {State} from './api';
import type {Screening} from '../../../packages/domain/src/index';
const time=(at?:string)=>at&&Number.isFinite(Date.parse(at))?new Date(at).toLocaleString('en-CA',{timeZone:'America/Toronto',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+' ET':'Unavailable';
function Outcome({label,proof,unavailable}:{label:string;proof?:Screening;unavailable?:string}){return <View style={s.outcome}><Text style={s.label}>{label}</Text>{proof?.timing?<><Text style={s.body}>Pickup {time(proof.timing.pickupReadyAt)}</Text><Text style={[s.title,{color:proof.timing.pickupLateMinutes?colors.orangeInk:colors.ink}]}>{proof.timing.pickupLateMinutes?`${proof.timing.pickupLateMinutes} min late`:'On time'}</Text><Text style={s.small}>Complete {time(proof.timing.completionAt)}</Text>{!proof.eligible?<Text style={s.warning}>Constraints block this plan.</Text>:null}</>:<Text style={s.small}>{unavailable??'Timing unavailable'}</Text>}{proof?.reasons.map((reason,i)=><Text key={i} style={s.warning}>{reason}</Text>)}</View>}
export function RecoveryCard({proposal:p,state,pending,onApprove}:{proposal:State['proposals'][number];state:State;pending:boolean;onApprove:()=>void}){
 const {load,previous,resulting,stale,canApprove}=recoveryState(p,state),comparison=p.body.comparison;
 const approve=()=>Alert.alert('Approve recovery?',`${p.load_id}: ${previous?.driverId??'Unassigned'} → ${p.body.driverId}\nTruck ${p.body.truckId} · Trailer ${p.body.trailerId}\n\nApply revision ${p.revision}? The server rechecks reservations and evidence. This creates an offer; the driver accepts separately.`,[{text:'Keep reviewing',style:'cancel'},{text:'Approve revision',onPress:onApprove}]);
 return <View style={s.card}><Text style={s.eyebrow}>{stale?'STALE':p.status.toUpperCase()} · REVISION {p.revision}</Text><Text style={s.heading}>{p.load_id}</Text><Text style={s.small}>{load?.customer??'Load unavailable'} · {load?.provenance??'Unknown source'}</Text>
 <View style={s.assignment}><Text style={s.label}>{p.status==='approved'?'BEFORE':'CURRENT ASSIGNMENT'}</Text><Text style={s.title}>{previous?.driverId??'Unassigned'}</Text><Text style={s.small}>{previous?`${previous.truckId} · ${previous.trailerId}`:'No current assignment'}</Text></View>
 <View style={[s.assignment,s.proposed]}><Text style={s.label}>{p.status==='approved'?'APPROVED DRIVER':'PROPOSED DRIVER'}</Text><Text style={s.title}>{p.body.driverId??'Unavailable'}</Text><Text style={s.small}>{p.body.truckId} · {p.body.trailerId}</Text></View>
 <Text style={s.body}>{p.body.reason??'Resource reassignment'}</Text><Text style={s.small}>Load window {time(load?.startAt)} → {time(load?.endAt)}</Text>
 {comparison?<><Text style={s.label}>SAME PICKUP WINDOW · MODELED OUTCOME</Text><Outcome label="Current plan" proof={comparison.current} unavailable={comparison.currentUnavailable??'No assigned baseline'}/><Outcome label="Replacement" proof={comparison.proposed}/><Text style={s.small}>Evaluated {time(comparison.evaluatedAt)}. Assumes stated travel/service times and preceding delivery positions. This is not a live ETA or measured savings.</Text></>:<Text style={s.warning}>No timing comparison attached. Review available evidence.</Text>}
 <Text style={s.label}>{p.body.proof?.eligible?'Declared constraints passed':'Feasibility needs review'}</Text><Text style={s.small}>{p.body.proof?.routingEvidence==='valhalla-truck'?'Valhalla truck-route estimate':'Planning estimate'} · {p.body.proof?.deadheadKm??'Unknown'} km deadhead</Text><Text style={s.small}>{p.body.proof?.note??'No route proof attached.'}</Text>{(p.body.assumptions??[]).map((a:string,i:number)=><Text key={i} style={s.small}>Assumption: {a}</Text>)}
 {stale?<Text accessibilityLiveRegion="polite" style={s.warning}>The load or resource evidence changed after rehearsal. Prepare a new proposal from the web planning board.</Text>:null}
 {p.status==='pending'?<><Text style={s.body}>Approval creates a new offer. Driver acceptance is still required.</Text><Pressable accessibilityRole="button" accessibilityState={{disabled:!canApprove||pending}} disabled={!canApprove||pending} onPress={approve} style={[s.button,(!canApprove||pending)&&{opacity:.45}]}><Text style={s.buttonText}>{pending?'Approval pending':'Review and approve'}</Text></Pressable></>:<Text accessibilityLiveRegion="polite" style={s.result}>{resulting?.status==='accepted'?'Driver accepted the replacement trip.':resulting?.status==='offered'?'Offer issued · awaiting driver acceptance.':'Review retained with its original evidence.'}</Text>}
 </View>;
}
const s=StyleSheet.create({card:{padding:20,borderRadius:16,backgroundColor:colors.white,gap:14},heading:{fontSize:28,fontWeight:'700'},eyebrow:{fontSize:10,fontWeight:'700',letterSpacing:1.5,color:colors.orangeInk},label:{fontSize:12,fontWeight:'700',lineHeight:19},title:{fontSize:22,fontWeight:'700'},body:{fontSize:14,lineHeight:22},small:{fontSize:12,lineHeight:19,color:colors.muted},warning:{fontSize:13,lineHeight:20,color:colors.orangeInk},assignment:{borderWidth:1,borderColor:colors.border,borderRadius:10,padding:16,gap:7},proposed:{backgroundColor:colors.amber,borderLeftWidth:3,borderLeftColor:colors.orange},outcome:{paddingVertical:12,gap:6,borderBottomWidth:1,borderBottomColor:colors.border},button:{minHeight:48,backgroundColor:colors.orange,borderRadius:8,alignItems:'center',justifyContent:'center',padding:12},buttonText:{fontSize:14,fontWeight:'700'},result:{fontSize:15,lineHeight:23,fontWeight:'600',color:colors.success}});
