import React,{useEffect,useRef,useState}from'react';
import{Alert,AppState,KeyboardAvoidingView,Modal,Platform,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Switch,TextInput,View}from'react-native';
import{Text,colors}from'./Design';import{sourceKey,type BillingReview}from'./billing-review';import{openBillingSource}from'./billing-source';import{correctionBody,correctionCommand,utcInput,type VisitCorrectionDraft}from'./visit-correction';import type{Api}from'./api';import type{Queue,Command}from'./queue';
type Props={api:Api;queue:Queue|null;data:BillingReview;commands:Command[];online:boolean;fresh:boolean;savedAt:string;send:(path:string,body:unknown,version:number,label:string)=>Promise<void>;onSourceViewed:(key:string)=>void;onRecorded:()=>void};
export function VisitCorrection(p:Props){
 const[draft,setDraft]=useState<VisitCorrectionDraft|null>(null),[open,setOpen]=useState(false),[ack,setAck]=useState(false),[opened,setOpened]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const writes=useRef(Promise.resolve()),latest=useRef({p,draft,ack,opened});latest.current={p,draft,ack,opened};const key=`visit-correction:${p.data.visit.id}`;
 useEffect(()=>{let active=true;setDraft(null);setOpen(false);setAck(false);setOpened('');void p.queue?.draft(key).then(raw=>{if(raw){const saved=JSON.parse(raw);if(active&&saved.snapshot?.visit.id===p.data.visit.id)setDraft(saved);}}).catch(e=>setMessage('Saved correction unavailable: '+String(e)));return()=>{active=false;};},[p.queue,key]);
 function edit(next:VisitCorrectionDraft|null){setDraft(next);setAck(false);if(p.queue)writes.current=writes.current.catch(()=>{}).then(()=>p.queue!.saveDraft(key,next?JSON.stringify(next):'')).catch(e=>setMessage('Correction not saved on this device: '+String(e)));}
 const pending=p.commands.some(c=>c.path==='/api/correct-visit-times'&&c.status==='pending'&&c.body.includes(p.data.visit.id));
 useEffect(()=>{if(!draft)return;const body=correctionBody(draft);if(!body)return;const done=p.commands.find(c=>c.path==='/api/correct-visit-times'&&c.status==='synchronized'&&c.expectedVersion===draft.snapshot.expectedVersion&&c.body===JSON.stringify(body));if(done){edit(null);setOpen(false);setMessage('Correction synchronized. Review the new billing draft separately; GPS and prior invoices remain retained.');p.onRecorded();}},[p.commands,draft]);
 const ready=p.online&&p.fresh&&!busy&&!pending&&!!p.data.visit.departure&&!p.data.visit.superseded_by&&!p.data.reviewRequired&&Number.isInteger(p.data.expectedVersion),stale=!!draft&&draft.snapshot.fingerprint!==p.data.fingerprint;
 function button(label:string,action:()=>void,disabled=false){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={action} style={[s.button,disabled&&{opacity:.4}]}><Text style={s.action}>{label}</Text></Pressable>;}
 function begin(){if(!draft&&!ready)return;if(!draft)edit({snapshot:p.data,documentId:'',arrival:utcInput(p.data.effective.arrivalAt),departure:utcInput(p.data.effective.departureAt),sourceNote:'',reason:''});setOpened('');setAck(false);setOpen(true);setMessage('');}
 async function viewSource(){const source=draft?.snapshot.documents.find(d=>d.id===draft.documentId);if(!source)return;setBusy(true);try{await openBillingSource(p.api,source);const k=sourceKey(source);setOpened(k);p.onSourceViewed(k);setMessage('Source bytes verified. Review the ticket and enter its same-stop times.');}catch(e){setMessage('Source review incomplete: '+String(e));}finally{setBusy(false);}}
 function confirm(){if(!draft||!ready)return;const command=correctionCommand(draft,p.data,opened,ack);if(!command)return;const fixed=JSON.stringify(draft);
 Alert.alert('Record reviewed dock times?',`${draft.snapshot.visit.load_id} · ${draft.snapshot.visit.stop_id}\nArrival ${draft.arrival} UTC\nDeparture ${draft.departure} UTC\n\nKeep original GPS and invoice history. Prepare a new draft; billing approval is separate.`,[{text:'Keep reviewing',style:'cancel'},{text:'Record correction',onPress:()=>{const n=latest.current,current=n.draft&&correctionCommand(n.draft,n.p.data,n.opened,n.ack);if(!n.p.online||!n.p.fresh||Date.now()-Date.parse(n.p.savedAt)>6000||AppState.currentState!=='active'||!current||JSON.stringify(n.draft)!==fixed||n.p.commands.some(c=>c.status==='pending'&&c.path==='/api/correct-visit-times'&&c.body.includes(n.p.data.visit.id))){setMessage('Evidence changed. Refresh the correction evidence and review again.');return;}setBusy(true);void n.p.send('/api/correct-visit-times',current.body,current.version,`Correct dock times ${n.p.data.visit.load_id}`).then(()=>setMessage('Correction requested. Check its synchronized, pending or failed status below.')).catch(e=>setMessage(String(e))).finally(()=>setBusy(false));}}]);
 }
 const failed=p.commands.filter(c=>c.path==='/api/correct-visit-times'&&c.status==='failed'&&c.body.includes(p.data.visit.id)).at(-1);
 return <View style={s.section}><Text style={s.heading}>Documented dock times</Text><Text style={s.body}>Resolve a conflict using a stored shipment ticket. This changes billing times, not GPS or duty history.</Text>{button(draft?'Resume saved correction':'Review documented times',begin,busy||pending||(!draft&&(!ready||!p.data.documents.length)))}{!p.data.visit.departure?<Text style={s.small}>A closed visit is required before correcting its times.</Text>:null}{p.data.reviewRequired?<Text style={s.warning}>Reconcile late GPS before correcting times.</Text>:null}{pending?<Text style={s.warning}>Correction pending. Its original evidence and version remain queued.</Text>:null}{failed?<Text style={s.warning}>Correction failed: {failed.error}. The original command remains in Activity.</Text>:null}{message&&!open?<Text style={s.warning}>{message}</Text>:null}
 <Modal visible={open} animationType="slide" onRequestClose={()=>{if(!busy)setOpen(false);}}><SafeAreaView style={s.safe}><StatusBar barStyle="dark-content"/><View style={s.top}><Text style={s.heading}>Review dock times</Text>{button('Close correction',()=>setOpen(false),busy)}</View><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':'height'}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">{draft?<>
 <Text style={s.label}>{draft.snapshot.visit.load_id} · {draft.snapshot.visit.stop_id}</Text><Text style={s.small}>Original GPS: {utcInput(draft.snapshot.visit.arrival)} → {utcInput(draft.snapshot.visit.departure!)} UTC</Text><Text style={s.small}>Choose and open the supporting ticket for this stop.</Text>{draft.snapshot.documents.map(doc=>button(`${draft.documentId===doc.id?'Selected':'Choose'} ${doc.filename??'shipment document'} · v${doc.version}`,()=>{edit({...draft,documentId:doc.id});setOpened('');},!ready))}{button(busy?'Opening source…':'Open correction source',()=>void viewSource(),!ready||!draft.documentId)}
 <Text style={s.small}>Enter date and time in UTC: YYYY-MM-DD HH:mm:ss. The original GPS record remains unchanged.</Text>{([['arrival','Reviewed arrival UTC'],['departure','Reviewed departure UTC'],['sourceNote','Document evidence note'],['reason','Reason for correction']] as const).map(([field,label])=><View key={field} style={{gap:6}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} value={draft[field]} editable={!busy&&!pending} onChangeText={v=>edit({...draft,[field]:v})} multiline={field==='sourceNote'||field==='reason'} autoCapitalize="none" style={[s.input,(field==='sourceNote'||field==='reason')&&{minHeight:90,textAlignVertical:'top'}]}/></View>)}
 {stale?<><Text accessibilityLiveRegion="polite" style={s.warning}>Evidence changed. Saved inputs remain; refresh the source and invoice history, reopen the document and acknowledge again.</Text>{button('Refresh correction evidence',()=>{edit({...draft,snapshot:p.data});setOpened('');},!ready)}</>:null}{!p.online?<Text style={s.warning}>Offline. Your draft remains saved; reconnect before recording.</Text>:null}
 <View style={s.toggle}><Switch accessibilityLabel="Confirm same-stop correction evidence" value={ack} onValueChange={setAck} disabled={!ready||stale}/><Text style={[s.body,{flex:1}]}>I reviewed this same-stop source, conflicting GPS times and correction reason.</Text></View>{message?<Text accessibilityLiveRegion="polite" style={s.warning}>{message}</Text>:null}{button('Review correction',confirm,!ready||!correctionCommand(draft,p.data,opened,ack))}<Text style={s.small}>Recording prepares a new detention draft. It does not approve billing or certify a boundary crossing.</Text>
 </>:null}</ScrollView></KeyboardAvoidingView></SafeAreaView></Modal></View>;
}
const s=StyleSheet.create({section:{gap:12,paddingTop:14,borderTopWidth:1,borderTopColor:colors.border},safe:{flex:1,backgroundColor:colors.ivory,paddingTop:Platform.OS==='android'?(StatusBar.currentHeight??24):0,paddingBottom:Platform.OS==='android'?24:0},top:{padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},content:{padding:20,gap:16,paddingBottom:50},heading:{fontSize:20,fontWeight:'700',lineHeight:27},label:{fontSize:14,fontWeight:'700',lineHeight:22},body:{fontSize:14,lineHeight:22},small:{fontSize:12,lineHeight:19,color:colors.muted},warning:{fontSize:13,lineHeight:21,color:colors.orangeInk},button:{minHeight:48,padding:12,borderRadius:8,backgroundColor:colors.amber,justifyContent:'center'},action:{fontSize:14,fontWeight:'600'},input:{borderWidth:1,borderColor:colors.border,borderRadius:8,padding:12,minHeight:48,backgroundColor:colors.white,fontSize:14},toggle:{flexDirection:'row',gap:10,alignItems:'center'}});
