import {writeFile} from 'node:fs/promises';
import {requireRouteAxles} from '../services/api/src/axles.ts';
import {fixtures,milton,london} from '../services/api/src/fixtures.ts';
import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {pool,migrate} from '../services/api/src/db.ts';import {Store} from '../services/api/src/store.ts';import {createApi} from '../services/api/src/server.ts';import {Files} from '../services/api/src/files.ts';
const db=pool(process.env.TEST_DATABASE_URL),s=new Store(db);before(()=>migrate(db));after(()=>db.end());const cmd=(expectedVersion=1)=>({key:randomUUID(),expectedVersion});
const configuration={tractorWheelbaseM:4,fifthWheelFromSteerM:3.8,trailerSpanM:10,emptyKg:{steer:5000,drive:5000,trailer:4000},limitsKg:{steer:6500,drive:18000,trailer:14000},grossLimitKg:40000,driveAxles:2,trailerAxles:2,equalizedGroups:true as const};
const pair={loadId:'RS-1042',driverId:'D-01',truckId:'T-101',trailerId:'V-101'};
async function setup(){const carrierId='axle-'+randomUUID();await s.seed(carrierId);const dispatcher=await s.membership('demo-dispatcher',carrierId),driver=await s.membership('demo-driver-1',carrierId);const document:any=await s.document(dispatcher,cmd(),{loadId:pair.loadId,mediaType:'application/pdf',kind:'other',filename:'synthetic-axle-source.pdf'});const bytes=Buffer.from('%PDF-1.4\n% Synthetic configuration and cargo-position evidence for integration verification only.\n%%EOF\n');await s.uploadDocument(dispatcher,cmd(),document.id,bytes,'application/pdf',new Files());const input={loadId:pair.loadId,truckId:pair.truckId,trailerId:pair.trailerId,documentId:document.id,expectedDocumentVersion:2,expectedLoadVersion:1,expectedTrailerVersion:1,configuration,cargoCgFromKingpinM:8,reason:'Synthetic reviewed cargo placement before dispatch.',sourceNote:'Synthetic scale tare, configuration limits and loading diagram.',acknowledgeModeledLoads:true as const};return {carrierId,dispatcher,driver,input};}
test('source-bound gross-pass/axle-fail review blocks direct and batch dispatch and preserves immutable revisions',{skip:!process.env.ROAD_ROUTING_TEST_URL},async()=>{
 const f=await setup(),app=createApi(s,{localDemo:true}),key=cmd(),headers={authorization:'Bearer demo-dispatcher','x-carrier-id':f.carrierId,'idempotency-key':key.key,'if-match':'1'};
 try{const request={method:'POST' as const,url:'/api/review-axles',headers,payload:f.input};const first=await app.inject(request);assert.equal(first.statusCode,200,first.body);const bad=first.json();assert.equal(bad.body.result.grossWithinLimit,true);assert.equal(bad.body.result.eligible,false);assert.deepEqual((await app.inject(request)).json(),bad);await assert.rejects(s.dispatch(f.dispatcher,cmd(),pair),{code:'INELIGIBLE'});
 const noPlan:any=await s.optimize(f.dispatcher,cmd(0),{loadIds:[pair.loadId],vehicles:[pair]});assert.equal(noPlan.result.routes.length,0);assert.ok(noPlan.result.infeasible_loads.some((r:any)=>r.reason.includes('trailer axle-group')));assert.equal((await s.snapshot(f.dispatcher)).assignments.length,0);
 const good:any=await s.reviewAxles(f.dispatcher,cmd(2),{...f.input,cargoCgFromKingpinM:5});assert.equal(good.body.result.eligible,true);assert.equal(good.revision,2);const review=await s.axleReview(f.dispatcher,pair.loadId,pair.truckId,pair.trailerId);assert.equal(review.history.length,2);assert.deepEqual(review.history[1].body,bad.body);assert.equal(review.proof.eligible,true);
 const plan:any=await s.optimize(f.dispatcher,cmd(0),{loadIds:[pair.loadId],vehicles:[pair]});assert.equal(plan.result.routes.length,1);await db.query('UPDATE documents SET version=version+1 WHERE carrier_id=$1 AND id=$2',[f.carrierId,f.input.documentId]);await assert.rejects(s.approvePlan(f.dispatcher,cmd(),{planId:plan.id}),{code:'AXLE_INELIGIBLE'});assert.equal((await s.snapshot(f.dispatcher)).assignments.length,0);const revised:any=await s.reviewAxles(f.dispatcher,cmd(3),{...f.input,expectedDocumentVersion:3,cargoCgFromKingpinM:5});const fresh:any=await s.optimize(f.dispatcher,cmd(0),{loadIds:[pair.loadId],vehicles:[pair]});const approved:any=await s.approvePlan(f.dispatcher,cmd(),{planId:fresh.id});assert.equal(approved.groups[0].axleAssessments[0].assessmentId,revised.id);
 await db.query('UPDATE documents SET version=version+1 WHERE carrier_id=$1 AND id=$2',[f.carrierId,f.input.documentId]);await assert.rejects(s.respond(f.driver,cmd(),{assignmentId:approved.groups[0].stops[0].assignmentId,action:'accept'}),{code:'AXLE_INELIGIBLE'});assert.equal((await s.snapshot(f.driver)).assignments[0].status,'offered');if(process.env.AXLE_EVIDENCE_FILE)await writeFile(process.env.AXLE_EVIDENCE_FILE,JSON.stringify({verifiedAt:new Date().toISOString(),carrierId:f.carrierId,bad,good,revised,approved,finalReview:await s.axleReview(f.dispatcher,pair.loadId,pair.truckId,pair.trailerId),checks:['Gross passes while trailer group fails','Bad review blocks direct and real-road batch dispatch','Repeated review retains original revision','Corrected cargo position permits a separately approved manifest','Changing source alone blocks batch approval and driver acceptance'],limits:['Synthetic API integration source bytes; document rendering and review interface not verified','Configured static limits are not Ontario legal clearance','Native and cloud rollout pending']},null,2)+'\n');
 }finally{await app.close();}
});
test('axle reviews reject unauthorized, stale and mismatched source evidence; changed source invalidates a pending approval',async()=>{
 const f=await setup(),other=await setup();await assert.rejects(async()=>s.reviewAxles(f.driver,cmd(),f.input),{code:'FORBIDDEN'});await assert.rejects(s.reviewAxles(f.dispatcher,cmd(),{...f.input,documentId:other.input.documentId}),{code:'STALE_SOURCE'});await assert.rejects(s.reviewAxles(f.dispatcher,cmd(2),f.input),{code:'STALE_EVIDENCE'});await assert.rejects(s.axleReview(f.driver,pair.loadId,pair.truckId,pair.trailerId),{code:'FORBIDDEN'});
 await s.reviewAxles(f.dispatcher,cmd(),{...f.input,cargoCgFromKingpinM:5});const p:any=await s.propose(f.dispatcher,cmd(),pair);await db.query('UPDATE documents SET version=version+1 WHERE carrier_id=$1 AND id=$2',[f.carrierId,f.input.documentId]);await assert.rejects(s.approve(f.dispatcher,cmd(),{proposalId:p.id}),{code:'INELIGIBLE'});assert.equal((await s.snapshot(f.dispatcher)).assignments.length,0);
 const stale=await s.axleReview(f.dispatcher,pair.loadId,pair.truckId,pair.trailerId);assert.equal(stale.proof.eligible,false);
});
test('batch planning cannot bypass declared axle clearance even with a complete truck routing profile',{skip:!process.env.ROAD_ROUTING_TEST_URL},async()=>{
 const f=await setup();await db.query("UPDATE resources SET body=jsonb_set(body,'{axleClearance}','\"unknown\"'),version=version+1 WHERE carrier_id=$1 AND id='T-101'",[f.carrierId]);const p:any=await s.optimize(f.dispatcher,cmd(0),{loadIds:[pair.loadId],vehicles:[pair]});assert.equal(p.result.routes.length,0);assert.ok(p.result.infeasible_loads.some((r:any)=>r.reason.includes('axle clearance')));
});

test('valid same-payload assessment survives offer/accept status versions but not changed physical payload',async()=>{
 const f=await setup();await s.reviewAxles(f.dispatcher,cmd(),{...f.input,cargoCgFromKingpinM:5});const trip:any=await s.dispatch(f.dispatcher,cmd(),pair);await s.respond(f.driver,cmd(),{assignmentId:trip.id,action:'accept'});assert.equal((await s.axleReview(f.driver,pair.loadId,pair.truckId,pair.trailerId)).proof.eligible,true);await assert.rejects(s.axleReview(f.driver,pair.loadId,'T-102',pair.trailerId),{code:'FORBIDDEN'});
 await db.query("UPDATE loads SET body=jsonb_set(body,'{weightLb}','33000'),version=version+1 WHERE carrier_id=$1 AND id=$2",[f.carrierId,pair.loadId]);assert.equal((await s.axleReview(f.dispatcher,pair.loadId,pair.truckId,pair.trailerId)).proof.eligible,false);
});
test('competing reviews retain one immutable revision and never overwrite each other',async()=>{
 const f=await setup(),results=await Promise.allSettled([s.reviewAxles(f.dispatcher,cmd(),f.input),s.reviewAxles(f.dispatcher,cmd(),{...f.input,cargoCgFromKingpinM:5})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const rejected=results.find(r=>r.status==='rejected');assert.equal(rejected?.reason.code,'STALE_EVIDENCE');assert.equal((await s.axleReview(f.dispatcher,pair.loadId,pair.truckId,pair.trailerId)).history.length,1);
});

test('real road LTL planning and approval both enforce combined axle capacity',{skip:!process.env.ROAD_ROUTING_TEST_URL},async()=>{
 const f=await setup(),base=fixtures().loads[0],ids=['RS-1042','RS-1044'],cfg={...configuration,limitsKg:{...configuration.limitsKg,trailer:10500}},docs=[f.input.documentId];
 for(const [i,id] of ids.entries()){const load={...base,id,weightLb:i?9000:10000,pallets:8,mode:'LTL',serviceMinutes:0};await db.query('UPDATE loads SET body=$3 WHERE carrier_id=$1 AND id=$2',[f.carrierId,id,JSON.stringify(load)]);await db.query('DELETE FROM stops WHERE carrier_id=$1 AND load_id=$2',[f.carrierId,id]);for(const [order,p] of [milton,london].entries())await db.query('INSERT INTO stops VALUES($1,$2,$3,$4,ST_SetSRID(ST_MakePoint($5,$6),4326)::geography,$7,$8)',[f.carrierId,id,p.id,order,p.lng,p.lat,p.radiusM,JSON.stringify(p)]);
 if(i){const d:any=await s.document(f.dispatcher,cmd(),{loadId:id,mediaType:'application/pdf',kind:'other',filename:'synthetic-ltl.pdf'});await s.uploadDocument(f.dispatcher,cmd(),d.id,Buffer.from('%PDF-1.4\n% Synthetic LTL configuration test source\n%%EOF'),'application/pdf',new Files());docs.push(d.id);}
 await s.reviewAxles(f.dispatcher,cmd(i+1),{...f.input,loadId:id,documentId:docs[i],configuration:cfg});}
 const input={loadIds:ids,vehicles:[pair]},limited:any=await s.optimize(f.dispatcher,cmd(0),input);assert.equal(limited.result.routes.length,1);assert.equal(limited.result.routes[0].stops.length,2);assert.equal(limited.result.infeasible_loads.length,1);
 const c=await db.connect();try{await assert.rejects(requireRouteAxles(s,c,f.dispatcher,{stops:[{load_id:ids[0],stop:'pickup'},{load_id:ids[1],stop:'pickup'},{load_id:ids[0],stop:'delivery'},{load_id:ids[1],stop:'delivery'}]},pair),{code:'AXLE_INELIGIBLE'});}finally{c.release();}
 for(const [i,id] of ids.entries())await s.reviewAxles(f.dispatcher,cmd(i+3),{...f.input,loadId:id,documentId:docs[i],configuration:{...cfg,limitsKg:{...cfg.limitsKg,trailer:12000}}});
 const expanded:any=await s.optimize(f.dispatcher,cmd(0),input);assert.equal(expanded.result.routes.length,1);assert.equal(expanded.result.routes[0].stops.length,4);const approved:any=await s.approvePlan(f.dispatcher,cmd(),{planId:expanded.id});assert.equal(approved.groups[0].axleAssessments.length,2);await s.respond(f.driver,cmd(),{assignmentId:approved.groups[0].stops[0].assignmentId,action:'accept'});assert.equal((await s.snapshot(f.driver)).assignments.filter(a=>a.status==='accepted').length,2);
 if(process.env.AXLE_EVIDENCE_FILE)await writeFile(process.env.AXLE_EVIDENCE_FILE+'.ltl.json',JSON.stringify({verifiedAt:new Date().toISOString(),carrierId:f.carrierId,limited,expanded,approved,checks:['Both LTL loads individually pass 10.5t trailer-group limit','Combined 19k lb payload fits gross but overloads group; solver leaves one load unserved','Server approval recheck independently rejects combined loading','Reviewed 12t configuration permits both loads, approval and group acceptance'],limits:'Synthetic configured limits; reviewer input change is not automatically a physical capacity improvement.'},null,2)+'\n');
});
