import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {pool,migrate} from '../services/api/src/db.ts';import {Store} from '../services/api/src/store.ts';import {milton,london,fixtures} from '../services/api/src/fixtures.ts';
test('real Valhalla + OR-Tools consolidated dispatch retains one reservation until every manifest stop completes',{skip:!process.env.ROAD_ROUTING_TEST_URL},async()=>{
 process.env.OPTIMIZER_URL=process.env.ROAD_ROUTING_TEST_URL;const db=pool(process.env.TEST_DATABASE_URL),s=new Store(db),carrierId='road-group-'+randomUUID(),cmd=(expectedVersion=1)=>({key:randomUUID(),expectedVersion});
 try{await migrate(db);await s.seed(carrierId);const dispatcher=await s.membership('demo-dispatcher',carrierId),driver=await s.membership('demo-driver-1',carrierId);const base=fixtures().loads[0];
 for(const [id,startAt,weight] of [['RS-1042','2026-09-13T12:30:00Z',10000],['RS-1044','2026-09-13T12:40:00Z',9000]] as const){const load={...base,id,startAt,weightLb:weight,pallets:8,mode:'LTL',serviceMinutes:20};await db.query('UPDATE loads SET body=$3 WHERE carrier_id=$1 AND id=$2',[carrierId,id,JSON.stringify(load)]);await db.query('DELETE FROM stops WHERE carrier_id=$1 AND load_id=$2',[carrierId,id]);for(const [i,p] of [milton,london].entries())await db.query('INSERT INTO stops VALUES($1,$2,$3,$4,ST_SetSRID(ST_MakePoint($5,$6),4326)::geography,$7,$8)',[carrierId,id,p.id,i,p.lng,p.lat,p.radiusM,JSON.stringify(p)]);}
 const input={loadIds:['RS-1042','RS-1044'],vehicles:[{driverId:'D-01',truckId:'T-101',trailerId:'V-101'}]};let plan:any=await s.optimize(dispatcher,cmd(0),input);assert.equal(plan.result.routes.length,1);assert.equal(plan.result.routes[0].stops.length,4);assert.equal(plan.result.routing_evidence,'valhalla-truck');
 await db.query("UPDATE resources SET version=version+1 WHERE carrier_id=$1 AND id='T-101'",[carrierId]);await assert.rejects(s.approvePlan(dispatcher,cmd(),{planId:plan.id}),{code:'STALE_PLAN'});plan=await s.optimize(dispatcher,cmd(0),input);const approvalKey=cmd();const result:any=await s.approvePlan(dispatcher,approvalKey,{planId:plan.id});assert.deepEqual(await s.approvePlan(dispatcher,approvalKey,{planId:plan.id}),result);assert.equal(result.groups.length,1);
 let snapshot=await s.snapshot(dispatcher);assert.equal(snapshot.assignments.length,2);assert.equal((await db.query('SELECT * FROM reservations WHERE carrier_id=$1 AND active',[carrierId])).rows.length,3);const group=result.groups[0];const first=group.stops[0];await s.respond(driver,cmd(),{assignmentId:first.assignmentId,action:'accept'});snapshot=await s.snapshot(dispatcher);assert.equal(snapshot.assignments.filter(a=>a.status==='accepted').length,2);
 const backhaul:any=await s.optimize(dispatcher,cmd(0),{loadIds:['RS-1043'],vehicles:input.vehicles});
 const saved=(await db.query('SELECT input FROM planning_runs WHERE carrier_id=$1 AND id=$2',[carrierId,backhaul.id])).rows[0].input;
 assert.equal(saved.vehicles[0].driving_minutes,420-group.drivingMinutes,'Consolidated driving is deducted once for the trip, not once per load');
 assert.equal(saved.vehicles[0].duty_minutes,480-group.dutyMinutes);assert.equal(backhaul.result.routes.length,1,'Backhaul remains feasible after consolidated delivery');
 const last=group.stops.at(-1);await assert.rejects(s.completeStop(driver,cmd(2),{assignmentId:last.assignmentId,stopId:last.stopId}),{code:'STOP_ORDER'});
 for(const [i,stop] of group.stops.entries()){const current=(await s.snapshot(driver)).assignments.find(a=>a.id===stop.assignmentId)!;await s.completeStop(driver,cmd(current.version),{assignmentId:stop.assignmentId,stopId:stop.stopId});const remaining=(await db.query('SELECT * FROM reservations WHERE carrier_id=$1 AND active',[carrierId])).rows.length;assert.equal(remaining,i===group.stops.length-1?0:3);}
 snapshot=await s.snapshot(driver);assert.equal(snapshot.tripGroups[0].status,'completed');assert.equal(snapshot.manifests.length,2);assert.equal(snapshot.assignments.filter(a=>a.status==='completed').length,2);
 }finally{await db.end();delete process.env.OPTIMIZER_URL;}
});
