import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {pool,migrate} from '../services/api/src/db.ts';
import {Store} from '../services/api/src/store.ts';
import {createApi} from '../services/api/src/server.ts';
import {milton} from '../services/api/src/fixtures.ts';
const db=pool(process.env.TEST_DATABASE_URL),store=new Store(db),cmd=(expectedVersion=1)=>({key:randomUUID(),expectedVersion});
before(()=>migrate(db));after(()=>db.end());
async function setup(){const carrierId=`late-${randomUUID()}`;await store.seed(carrierId);const dispatcher=await store.membership('demo-dispatcher',carrierId),driver=await store.membership('demo-driver-1',carrierId),simulator=await store.membership('demo-simulator',carrierId);const trip:any=await store.dispatch(dispatcher,cmd(),{loadId:'RS-1042',driverId:'D-01',truckId:'T-101',trailerId:'V-101'});await store.respond(driver,cmd(),{assignmentId:trip.id,action:'accept'});return {carrierId,dispatcher,driver,simulator,trip};}
const outside={...milton,lat:43.53};
const point=(f:any,id:string,at:string,position=milton)=>({id,assignmentId:f.trip.id,at,position,accuracyM:10,odometerKm:1000,speedKph:0,duty:'on_duty' as const,provenance:'synthetic' as const});
const apply=async(f:any)=>{const review=await store.visitReview(f.dispatcher,f.trip.id),command=cmd(review.expectedVersion),body={assignmentId:f.trip.id,fingerprint:review.fingerprint,reason:'Reviewed original ordered GPS evidence and all prior billing revisions.',acknowledgeRevisedEvidence:true};return {review,command,body,result:await store.reconcileVisits(f.dispatcher,command,body)};};
const summary=(s:any)=>({visits:s.visits.map((v:any)=>[v.stop_id,new Date(v.arrival).toISOString(),new Date(v.departure).toISOString()]),bills:s.invoices.map((i:any)=>[i.body.dwellMinutes,i.body.billableMinutes,i.body.amountCents])});
test('late arrival reproduces missing detention; reviewed ordering matches baseline without moving GPS or doubling retry',async()=>{
 const baseline=await setup(),late=await setup();for(const f of [baseline,late]){const observations=[point(f,'arrive','2026-09-13T12:30:00Z'),point(f,'leave','2026-09-13T15:15:00Z',outside)];for(const e of f===late?observations.reverse():observations)await store.ingest(f.simulator,cmd(),e);}
 assert.equal((await store.snapshot(late.dispatcher)).visits.length,0);const rawBefore=(await db.query('SELECT * FROM telemetry WHERE carrier_id=$1 ORDER BY id',[late.carrierId])).rows;const before=await store.snapshot(late.dispatcher);assert.equal(before.assignments[0].visitReviewRequired,true);
 const action=await apply(late);assert.deepEqual(await store.reconcileVisits(late.dispatcher,action.command,action.body),action.result);const after=await store.snapshot(late.dispatcher);assert.deepEqual(summary(after),summary(await store.snapshot(baseline.dispatcher)));assert.equal(after.assignments[0].visitReviewRequired,false);assert.deepEqual(after.resources,before.resources);assert.deepEqual((await db.query('SELECT * FROM telemetry WHERE carrier_id=$1 ORDER BY id',[late.carrierId])).rows,rawBefore);assert.equal((await db.query('SELECT count(*) FROM visit_reconciliations WHERE carrier_id=$1',[late.carrierId])).rows[0].count,'1');
 await assert.rejects(store.reconcileVisits(late.dispatcher,cmd(action.review.expectedVersion),action.body),{code:'STALE_EVIDENCE'});
});
test('late evidence blocks approval; reconciliation retains approved history byte-for-byte and current totals exclude retired visits',async()=>{
 const f=await setup();await store.ingest(f.simulator,cmd(),point(f,'first','2026-09-13T13:00:00Z'));await store.ingest(f.simulator,cmd(),point(f,'exit','2026-09-13T15:15:00Z',outside));const s=await store.snapshot(f.dispatcher),draft=s.invoices[0];await store.approveInvoice(f.dispatcher,cmd(draft.revision),{invoiceId:draft.id,acknowledgeObservedSamples:true,evidenceNote:'Reviewed original same-stop sources and synthetic contract.'});const historical=(await db.query('SELECT * FROM invoice_revisions WHERE carrier_id=$1 ORDER BY revision',[f.carrierId])).rows;
 await store.ingest(f.simulator,cmd(),point(f,'late','2026-09-13T12:30:00Z'));await assert.rejects(store.detentionDraft(f.dispatcher,cmd(2),{visitId:s.visits[0].id,contractId:'demo-ftl'}),{code:'VISIT_REVIEW_REQUIRED'});await apply(f);
 const current=await store.snapshot(f.dispatcher);assert.equal(current.visits.length,1);assert.equal(current.invoices.length,1);assert.equal(current.invoices[0].status,'draft');assert.equal(current.invoices[0].body.amountCents,7500);assert.deepEqual((await db.query('SELECT * FROM invoice_revisions WHERE carrier_id=$1 AND visit_id=$2 ORDER BY revision',[f.carrierId,s.visits[0].id])).rows,historical);const review=await store.visitReview(f.dispatcher,f.trip.id);assert.equal(review.historicalVisits.length,1);assert.equal(review.history[0].reviewed_by,f.dispatcher.uid);assert.equal(review.invoices.length,3);
 await assert.rejects(store.approveInvoice(f.dispatcher,cmd(1),{invoiceId:draft.id,acknowledgeObservedSamples:true,evidenceNote:'Attempting the obsolete prior draft after reconciliation.'}),{code:'STALE_VERSION'});
});
test('new observation invalidates review and roles/carriers cannot reconcile someone else',async()=>{
 const f=await setup();await store.ingest(f.simulator,cmd(),point(f,'exit','2026-09-13T15:15:00Z',outside));await store.ingest(f.simulator,cmd(),point(f,'late','2026-09-13T12:30:00Z'));const review=await store.visitReview(f.dispatcher,f.trip.id),body={assignmentId:f.trip.id,fingerprint:review.fingerprint,reason:'Review must remain bound to this exact observation set.',acknowledgeRevisedEvidence:true};await store.ingest(f.simulator,cmd(),point(f,'later','2026-09-13T15:16:00Z',outside));await assert.rejects(store.reconcileVisits(f.dispatcher,cmd(review.expectedVersion),body),{code:'STALE_EVIDENCE'});
 const app=createApi(store,{localDemo:true});for(const uid of ['demo-driver-1','demo-simulator']){const headers={authorization:`Bearer ${uid}`,'x-carrier-id':f.carrierId,'idempotency-key':randomUUID(),'if-match':String(review.expectedVersion)};assert.equal((await app.inject({url:'/api/visit-review?assignmentId='+f.trip.id,headers})).statusCode,403);assert.equal((await app.inject({method:'POST',url:'/api/reconcile-visits',headers,payload:body})).statusCode,403);}const other=await setup();await assert.rejects(store.visitReview(other.dispatcher,f.trip.id),{code:'NOT_FOUND'});await app.close();assert.equal((await store.snapshot(f.dispatcher)).visits.length,0);
});
test('same-time conflicting positions cannot be arbitrarily reconciled and pending review blocks latest draft approval',async()=>{
 const f=await setup();await store.ingest(f.simulator,cmd(),point(f,'a','2026-09-13T12:30:00Z'));await store.ingest(f.simulator,cmd(),point(f,'b','2026-09-13T15:15:00Z',outside));await store.ingest(f.simulator,cmd(),point(f,'conflict','2026-09-13T12:30:00Z',outside));const s=await store.snapshot(f.dispatcher);await assert.rejects(store.approveInvoice(f.dispatcher,cmd(1),{invoiceId:s.invoices[0].id,acknowledgeObservedSamples:true,evidenceNote:'Billing cannot ignore contradictory late source observations.'}),{code:'VISIT_REVIEW_REQUIRED'});await assert.rejects(apply(f),{code:'AMBIGUOUS_TIME'});assert.equal((await store.snapshot(f.dispatcher)).assignments[0].visitReviewRequired,true);
});
test('late completed-trip evidence remains recoverable; replayed duplicates do not reopen review',async()=>{
 const f=await setup();const exit=point(f,'exit','2026-09-13T15:15:00Z',outside);await store.ingest(f.simulator,cmd(),exit);await db.query("UPDATE assignments SET status='completed',version=version+1 WHERE carrier_id=$1 AND id=$2",[f.carrierId,f.trip.id]);const arrival=point(f,'late-arrival','2026-09-13T12:30:00Z');await store.ingest(f.simulator,cmd(),arrival);await assert.rejects(store.ingest(f.simulator,cmd(),point(f,'forward','2026-09-13T15:16:00Z',outside)),{code:'NOT_ACCEPTED'});await apply(f);const initial=await store.snapshot(f.dispatcher);await store.ingest(f.simulator,cmd(),exit);await store.ingest(f.simulator,cmd(),arrival);const final=await store.snapshot(f.dispatcher);assert.deepEqual(final.visits,initial.visits);assert.deepEqual(final.invoices,initial.invoices);assert.equal(final.assignments[0].visitReviewRequired,false);
});
test('a late exit splits a mistaken continuous visit; competing reviews commit only once',async()=>{
 const f=await setup();await store.ingest(f.simulator,cmd(),point(f,'first-arrival','2026-09-13T12:30:00Z'));await store.ingest(f.simulator,cmd(),point(f,'second-arrival','2026-09-13T13:30:00Z'));await store.ingest(f.simulator,cmd(),point(f,'final-exit','2026-09-13T16:15:00Z',outside));await store.ingest(f.simulator,cmd(),point(f,'late-exit','2026-09-13T13:00:00Z',outside));const review=await store.visitReview(f.dispatcher,f.trip.id),body={assignmentId:f.trip.id,fingerprint:review.fingerprint,acknowledgeRevisedEvidence:true,reason:'Confirmed separate visits against the retained departure samples.'};const outcomes=await Promise.allSettled([store.reconcileVisits(f.dispatcher,cmd(review.expectedVersion),body),store.reconcileVisits(f.dispatcher,cmd(review.expectedVersion),body)]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);const s=await store.snapshot(f.dispatcher);assert.equal(s.visits.length,2);assert.equal(s.invoices.length,1);assert.equal(s.invoices[0].body.billableMinutes,45);assert.equal(s.invoices[0].body.amountCents,7500);assert.equal((await store.visitReview(f.dispatcher,f.trip.id)).historicalVisits.length,1);
});
