import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {pool,migrate} from '../services/api/src/db.ts';
import {Store} from '../services/api/src/store.ts';
import {milton} from '../services/api/src/fixtures.ts';
import {fenceConfidence,VISIT_SESSION_POLICY} from '../packages/domain/src/geofence.ts';
const db=pool(process.env.TEST_DATABASE_URL),store=new Store(db),cmd=(expectedVersion=1)=>({key:randomUUID(),expectedVersion});before(()=>migrate(db));after(()=>db.end());
async function setup(){const carrierId='visit-policy-'+randomUUID();await store.seed(carrierId);const dispatcher=await store.membership('demo-dispatcher',carrierId),driver=await store.membership('demo-driver-1',carrierId),simulator=await store.membership('demo-simulator',carrierId),trip:any=await store.dispatch(dispatcher,cmd(),{loadId:'RS-1042',driverId:'D-01',truckId:'T-101',trailerId:'V-101'});await store.respond(driver,cmd(),{assignmentId:trip.id,action:'accept'});return {carrierId,dispatcher,driver,simulator,trip};}
const event=(f:any,id:string,minute:number,position=milton,accuracyM=10)=>({id,assignmentId:f.trip.id,at:new Date(Date.parse('2026-09-13T12:30:00Z')+minute*60000).toISOString(),position,accuracyM,odometerKm:1000,speedKph:0,duty:'on_duty' as const,provenance:'synthetic' as const});
async function boundary(f:any,offset:number){return (await db.query("SELECT jsonb_build_object('lat',ST_Y(p::geometry),'lng',ST_X(p::geometry)) AS position FROM (SELECT ST_Project(location,(radius_m+$2)::double precision,0::double precision) p FROM stops WHERE carrier_id=$1 AND load_id='RS-1042' AND id=$3) x",[f.carrierId,offset,milton.id])).rows[0].position;}
const closed=(s:any)=>s.visits.map((v:any)=>[v.stop_id,new Date(v.arrival).toISOString(),v.departure&&new Date(v.departure).toISOString()]);
test('strict confidence filter holds exact boundary, invalid and low-confidence fixes',()=>{
 assert.equal(fenceConfidence(90,10,100),'boundary');assert.equal(fenceConfidence(110,10,100),'boundary');assert.equal(fenceConfidence(89.999,10,100),'inside');assert.equal(fenceConfidence(110.001,10,100),'outside');assert.equal(fenceConfidence(0,101,180),'uncertain');assert.equal(fenceConfidence(NaN,10,180),'uncertain');assert.equal(fenceConfidence(0,-1,180),'uncertain');
});
test('repeated edge jitter holds one visit and one detention draft, including duplicate delivery and reviewed late evidence',async()=>{
 const f=await setup(),base=await setup(),nearIn=await boundary(f,-5),nearOut=await boundary(f,5),outside=await boundary(f,30);
 const arrival=event(f,'arrival',0);await Promise.all([store.ingest(f.simulator,cmd(),arrival),store.ingest(f.simulator,cmd(),arrival)]);await store.ingest(base.simulator,cmd(),event(base,'arrival',0));
 for(let n=1;n<=24;n++)await store.ingest(f.simulator,cmd(),event(f,'jitter-'+n,n*5,n%2?nearIn:nearOut));await store.ingest(f.simulator,cmd(),event(f,'uncertain',140,outside,101));let snap=await store.snapshot(f.dispatcher);assert.equal(snap.visits.length,1);assert.equal(snap.visits[0].departure,null);assert.equal(snap.invoices.length,0);
 await store.ingest(f.simulator,cmd(),event(f,'departure',165,outside));await store.ingest(base.simulator,cmd(),event(base,'departure',165,outside));snap=await store.snapshot(f.dispatcher);assert.equal(snap.visits.length,1);assert.equal(snap.visits[0].session_policy,VISIT_SESSION_POLICY);assert.equal(snap.invoices.length,1);assert.equal(snap.invoices[0].body.billableMinutes,45);assert.equal(snap.invoices[0].body.visitPolicy.freeTimeScope,'each-observed-visit');assert.deepEqual(closed(snap),closed(await store.snapshot(base.dispatcher)));
 const points=(await store.tracking(f.driver,f.trip.id)).points;assert.equal(points.length,27);assert.equal(points.filter(p=>p.geofenceEvidence?.stopStates?.some((s:{stopId:string;confidence:string})=>s.stopId===milton.id&&s.confidence==='boundary')).length,24);assert.equal(points.find(p=>p.id==='uncertain').disposition,'uncertain');
 await store.ingest(f.simulator,cmd(),event(f,'late-jitter',125,nearOut));const review=await store.visitReview(f.dispatcher,f.trip.id);assert.equal(review.changed,false);assert.equal(review.reviewRequired,true);assert.equal(review.visitPolicy.id,VISIT_SESSION_POLICY);await store.reconcileVisits(f.dispatcher,cmd(review.expectedVersion),{assignmentId:f.trip.id,fingerprint:review.fingerprint,reason:'Reviewed boundary uncertainty and retained original visit timestamps.',acknowledgeRevisedEvidence:true});const after=await store.snapshot(f.dispatcher);assert.deepEqual(after.visits,snap.visits);assert.deepEqual(after.invoices,snap.invoices);
});
test('a one-minute confident exit splits visits and applies free time separately without merging source history',async()=>{
 const f=await setup(),outside=await boundary(f,30);for(const [id,minute,position] of [['arrive',0,milton],['exit',150,outside],['return',151,milton],['leave',301,outside]] as const)await store.ingest(f.simulator,cmd(),event(f,id,minute,position));const snap=await store.snapshot(f.dispatcher);assert.equal(snap.visits.length,2);assert.equal(snap.invoices.length,2);assert.deepEqual(snap.invoices.map(i=>i.body.billableMinutes),[30,30]);assert.equal(snap.invoices.reduce((n,i)=>n+i.body.dwellMinutes,0),300);assert.deepEqual(new Set(snap.invoices.flatMap(i=>i.body.evidence)),new Set(['arrive','exit','return','leave']));assert.ok(snap.invoices.every(i=>i.body.visitPolicy.id===VISIT_SESSION_POLICY));
 const review=await store.visitReview(f.dispatcher,f.trip.id);assert.equal(review.changed,false);assert.equal(review.proposed.length,2);assert.equal((await store.tracking(f.driver,f.trip.id)).points.length,4);
});
test('boundary uncertainty before arrival never backdates the first confident inside observation',async()=>{
 const f=await setup();await store.ingest(f.simulator,cmd(),event(f,'edge',0,await boundary(f,5)));assert.equal((await store.snapshot(f.dispatcher)).visits.length,0);await store.ingest(f.simulator,cmd(),event(f,'inside',3));await store.ingest(f.simulator,cmd(),event(f,'exit',123,await boundary(f,30)));const snap=await store.snapshot(f.dispatcher);assert.equal(snap.visits[0].arrival_event,'inside');assert.equal(snap.invoices.length,0);assert.equal((await store.visitReview(f.dispatcher,f.trip.id)).changed,false);
});
