import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {pool,migrate} from '../services/api/src/db.ts';
import {Store} from '../services/api/src/store.ts';
import {milton} from '../services/api/src/fixtures.ts';
const db=pool(process.env.TEST_DATABASE_URL),store=new Store(db),cmd=(expectedVersion=1)=>({key:randomUUID(),expectedVersion});before(()=>migrate(db));after(()=>db.end());
const at=(m:number)=>new Date(Date.parse('2026-09-13T12:30:00Z')+m*60000).toISOString();
const event=(f:any,id:string,minute:number,inside=true)=>({id,assignmentId:f.trip.id,at:at(minute),position:inside?milton:{...milton,lat:milton.lat+.01},accuracyM:5,odometerKm:1000,speedKph:0,duty:'on_duty' as const,provenance:'synthetic' as const});
async function setup(){const carrierId='dock-time-'+randomUUID();await store.seed(carrierId);const dispatcher=await store.membership('demo-dispatcher',carrierId),driver=await store.membership('demo-driver-1',carrierId),simulator=await store.membership('demo-simulator',carrierId),trip:any=await store.dispatch(dispatcher,cmd(),{loadId:'RS-1042',driverId:'D-01',truckId:'T-101',trailerId:'V-101'}),f={carrierId,dispatcher,driver,simulator,trip};await store.respond(driver,cmd(),{assignmentId:trip.id,action:'accept'});await store.ingest(simulator,cmd(),event(f,'arrival',0));await store.ingest(simulator,cmd(),event(f,'departure',165,false));const state=await store.snapshot(dispatcher),documentId=randomUUID();await db.query("INSERT INTO documents(carrier_id,id,load_id,object_name,sha256,media_type,status,extraction,version) VALUES($1,$2::uuid,'RS-1042',$2::text,$3,'application/pdf','stored',$4,2)",[carrierId,documentId,'a'.repeat(64),{filename:'synthetic-dock-ticket.pdf',provenance:'synthetic'}]);return {...f,visit:state.visits[0],invoice:state.invoices[0],documentId};}
const input=(f:any,review:any,start=10,end=160)=>({visitId:f.visit.id,stopId:milton.id,documentId:f.documentId,fingerprint:review.fingerprint,arrivalAt:at(start),departureAt:at(end),sourceNote:'Page 1: synthetic signed dock ticket states the same shipment and stop times.',reason:'Dock check-in and release differ from the retained GPS facility observations.',acknowledgeConflictingEvidence:true});
const approve=(id:string,corrected=false)=>({invoiceId:id,acknowledgeObservedSamples:true,acknowledgeCorrectedTimes:corrected,evidenceNote:'Reviewed the stored source ticket, original GPS samples, stop identity and contract.'});
test('document correction preserves observed truth and approved history; repeated commands and corrected approval remain explicit',async()=>{
 const f=await setup(),approved:any=await store.approveInvoice(f.dispatcher,cmd(1),approve(f.invoice.id)),before=await store.snapshot(f.dispatcher),raw=(await db.query('SELECT * FROM telemetry WHERE carrier_id=$1 ORDER BY id',[f.carrierId])).rows;
 const review=await store.visitTimeReview(f.dispatcher,f.visit.id),command=cmd(review.expectedVersion),body=input(f,review),result:any=await store.correctVisitTimes(f.dispatcher,command,body);assert.equal(result.revision,1);assert.equal(result.invoice.revision,3);assert.equal(result.invoice.billableMinutes,30);assert.equal(result.invoice.precision,'reviewed_document_times');assert.equal(result.invoice.timingEvidence.document.sha256,'a'.repeat(64));assert.equal(result.body.reviewedBy,f.dispatcher.uid);assert.equal(result.body.observed.arrivalEvent,'arrival');assert.equal(result.body.previousRevisionId,null);
 assert.deepEqual(await store.correctVisitTimes(f.dispatcher,command,body),JSON.parse(JSON.stringify(result)));await assert.rejects(store.correctVisitTimes(f.dispatcher,cmd(0),body),{code:'STALE_EVIDENCE'});const after=await store.snapshot(f.dispatcher);assert.deepEqual(after.visits,before.visits);assert.deepEqual(after.resources,before.resources);assert.deepEqual((await db.query('SELECT * FROM telemetry WHERE carrier_id=$1 ORDER BY id',[f.carrierId])).rows,raw);assert.deepEqual(after.invoices.find(i=>i.id===approved.id),before.invoices.find(i=>i.id===approved.id));
 await assert.rejects(store.approveInvoice(f.dispatcher,cmd(3),approve(result.invoice.id)),{code:'REVIEW_REQUIRED'});const final:any=await store.approveInvoice(f.dispatcher,cmd(3),approve(result.invoice.id,true));assert.equal(final.revision,4);assert.equal(final.amountCents,5000);assert.equal(final.precision,'reviewed_document_times');
 const fresh=await store.visitTimeReview(f.dispatcher,f.visit.id),zero:any=await store.correctVisitTimes(f.dispatcher,cmd(1),input(f,fresh,10,100));assert.equal(zero.invoice.billableMinutes,0);assert.equal(zero.invoice.amountCents,0);assert.equal(zero.invoice.revision,5);assert.equal(zero.body.previousRevisionId,result.id);assert.equal((await store.visitTimeReview(f.dispatcher,f.visit.id)).history.length,2);
});
test('source changes invalidate review and corrected approval without trapping late-GPS reconciliation',async()=>{
 const f=await setup(),review=await store.visitTimeReview(f.dispatcher,f.visit.id);await db.query('UPDATE documents SET version=version+1 WHERE carrier_id=$1 AND id=$2',[f.carrierId,f.documentId]);await assert.rejects(store.correctVisitTimes(f.dispatcher,cmd(0),input(f,review)),{code:'STALE_EVIDENCE'});
 const fresh=await store.visitTimeReview(f.dispatcher,f.visit.id),changed:any=await store.correctVisitTimes(f.dispatcher,cmd(0),input(f,fresh));await db.query('UPDATE documents SET version=version+1 WHERE carrier_id=$1 AND id=$2',[f.carrierId,f.documentId]);await assert.rejects(store.approveInvoice(f.dispatcher,cmd(2),approve(changed.invoice.id,true)),{code:'STALE_TIME_EVIDENCE'});
 await store.ingest(f.simulator,cmd(),event(f,'late-inside',30));const late=await store.visitReview(f.dispatcher,f.trip.id);assert.equal(late.changed,false);await store.reconcileVisits(f.dispatcher,cmd(late.expectedVersion),{assignmentId:f.trip.id,fingerprint:late.fingerprint,reason:'Reviewed late GPS without changes to the original visit boundaries.',acknowledgeRevisedEvidence:true});const rereview=await store.visitTimeReview(f.dispatcher,f.visit.id);assert.equal(rereview.reviewRequired,false);await store.correctVisitTimes(f.dispatcher,cmd(1),input(f,rereview));
});
test('wrong role, carrier, source shipment, stop, chronology, overlap and late hold cannot correct a visit',async()=>{
 const f=await setup(),other=await setup(),review=await store.visitTimeReview(f.dispatcher,f.visit.id),body=input(f,review);
 await assert.rejects(store.visitTimeReview(f.driver,f.visit.id),{code:'FORBIDDEN'});assert.throws(()=>store.correctVisitTimes(f.driver,cmd(0),body),{code:'FORBIDDEN'});await assert.rejects(store.visitTimeReview(other.dispatcher,f.visit.id),{code:'NOT_FOUND'});await assert.rejects(store.correctVisitTimes(f.dispatcher,cmd(0),{...body,documentId:other.documentId}),{code:'DOCUMENT_REQUIRED'});await assert.rejects(store.correctVisitTimes(f.dispatcher,cmd(0),{...body,stopId:'another-stop'}),{code:'REVIEW_REQUIRED'});await assert.rejects(store.correctVisitTimes(f.dispatcher,cmd(0),{...body,departureAt:body.arrivalAt}),{code:'INVALID_TIME'});
 await store.ingest(f.simulator,cmd(),event(f,'return',166));await store.ingest(f.simulator,cmd(),event(f,'leave-again',330,false));const fresh=await store.visitTimeReview(f.dispatcher,f.visit.id);await assert.rejects(store.correctVisitTimes(f.dispatcher,cmd(0),input(f,fresh,0,170)),{code:'VISIT_OVERLAP'});
 await store.ingest(f.simulator,cmd(),event(f,'late',40));const late=await store.visitTimeReview(f.dispatcher,f.visit.id);await assert.rejects(store.correctVisitTimes(f.dispatcher,cmd(0),input(f,late)),{code:'VISIT_REVIEW_REQUIRED'});assert.equal(late.history.length,0);
});
test('competing corrections commit once and reconstructed replacement visits do not inherit manual times',async()=>{
 const f=await setup(),review=await store.visitTimeReview(f.dispatcher,f.visit.id);const results=await Promise.allSettled([store.correctVisitTimes(f.dispatcher,cmd(0),input(f,review)),store.correctVisitTimes(f.dispatcher,cmd(0),input(f,review,20,160))]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await store.visitTimeReview(f.dispatcher,f.visit.id)).history.length,1);
 await store.ingest(f.simulator,cmd(),event(f,'late-exit',150,false));const late=await store.visitReview(f.dispatcher,f.trip.id);assert.equal(late.changed,true);await store.reconcileVisits(f.dispatcher,cmd(late.expectedVersion),{assignmentId:f.trip.id,fingerprint:late.fingerprint,reason:'Late departure evidence changes the GPS visit and retains manual correction history.',acknowledgeRevisedEvidence:true});const state=await store.snapshot(f.dispatcher);assert.equal(state.visits.length,1);assert.notEqual(state.visits[0].id,f.visit.id);assert.ok(state.invoices.every(i=>!i.body.timingEvidence));const historic=await store.visitTimeReview(f.dispatcher,f.visit.id);assert.ok(historic.visit.superseded_by);assert.equal(historic.history.length,1);
});
test('a later observed visit can flag overlapping corrected times without rejecting telemetry or approving two conflicting charges',async()=>{
 const f=await setup(),review=await store.visitTimeReview(f.dispatcher,f.visit.id),correction:any=await store.correctVisitTimes(f.dispatcher,cmd(0),input(f,review,0,200));
 await store.ingest(f.simulator,cmd(),event(f,'return',166));await store.ingest(f.simulator,cmd(),event(f,'leave-again',330,false));const state=await store.snapshot(f.dispatcher),secondVisit=state.visits.find(v=>v.id!==f.visit.id)!,second=state.invoices.find(i=>i.visit_id===secondVisit.id)!;assert.equal(second.body.timingConflicts[0].visitId,f.visit.id);assert.equal((await store.tracking(f.driver,f.trip.id)).points.length,4);
 await assert.rejects(store.approveInvoice(f.dispatcher,cmd(correction.invoice.revision),approve(correction.invoice.id,true)),{code:'VISIT_OVERLAP'});await assert.rejects(store.approveInvoice(f.dispatcher,cmd(second.revision),approve(second.id)),{code:'VISIT_OVERLAP'});
 const refreshed=await store.visitTimeReview(f.dispatcher,f.visit.id);await store.correctVisitTimes(f.dispatcher,cmd(1),input(f,refreshed,10,160));const approved:any=await store.approveInvoice(f.dispatcher,cmd(second.revision),approve(second.id));assert.deepEqual(approved.timingConflictReview.remainingConflicts,[]);assert.equal(approved.timingConflicts.length,1);
});
