import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {calculateAxles,axleReviewSchema,type AxleReviewInput} from '@roadstar/domain/axle';
import {request,type State,type Session,type SendCommand,type ShipmentDocument} from './api';
import {downloadOriginal} from './Documents';
import {Modal} from './ReviewDialog';

type Result=ReturnType<typeof calculateAxles>;
type History={id:string;revision:number;reviewed_by:string;recorded_at:string;body:{input:AxleReviewInput;result:Result;document:{id:string;version:number;sha256:string}}};
type Review={history:History[];proof:{required:boolean;eligible:boolean;reasons:string[];note?:string;result?:Result}};
type Draft={loadId:string;truckId:string;trailerId:string;truckVersion:number;loadVersion:number;trailerVersion:number;payloadLb:number;documents:ShipmentDocument[];historyId:string};
const fields=[['tractorWheelbaseM','Tractor wheelbase (m)'],['fifthWheelFromSteerM','Fifth wheel from steer group (m)'],['trailerSpanM','Kingpin to trailer group (m)'],['cargoCgFromKingpinM','Cargo centre from kingpin (m)'],['emptySteer','Empty steer group (kg)'],['emptyDrive','Empty drive group (kg)'],['emptyTrailer','Empty trailer group (kg)'],['limitSteer','Configured steer limit (kg)'],['limitDrive','Configured drive limit (kg)'],['limitTrailer','Configured trailer limit (kg)'],['grossLimitKg','Configured gross limit (kg)'],['driveAxles','Equalized drive axle count'],['trailerAxles','Equalized trailer axle count']] as const;
const kg=(n:number)=>new Intl.NumberFormat('en-CA',{maximumFractionDigits:1}).format(n)+' kg';
function Results({result}:{result:Result}){return <div className="axle-results"><h3>{result.eligible?'Within configured weight limits':'Configured weight limit exceeded'}</h3><p><strong>Gross {kg(result.grossKg)}</strong> / {kg(result.grossLimitKg)} · {result.grossWithinLimit?'within limit':'over limit'}</p><div className="axle-groups">{result.groups.map(g=><article key={g.id} className={g.withinLimit?'':'notice'}><strong>{g.id==='drive'?'Drive group':g.id==='trailer'?'Trailer group':'Steer group'}</strong><p>{kg(g.loadedKg)} / {kg(g.limitKg)}</p><span>{g.withinLimit?'Within configured limit':'Over configured limit'}</span></article>)}</div><p className="fine">{result.note}</p></div>;}
export function AxleReview({state,session,send,online}:{state:State;session:Session;send:SendCommand;online:boolean}){
 const [open,setOpen]=useState(false),[loadId,setLoad]=useState(''),[truckId,setTruck]=useState(''),[trailerId,setTrailer]=useState(''),[draft,setDraft]=useState<Draft|null>(null),[values,setValues]=useState<Record<string,string>>({}),[documentId,setDocument]=useState(''),[reason,setReason]=useState(''),[note,setNote]=useState(''),[ack,setAck]=useState(false),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=state.loads.find(l=>l.id===loadId),truck=state.resources.find(r=>r.kind==='truck'&&r.id===truckId),trailer=state.resources.find(r=>r.kind==='trailer'&&r.id===trailerId);
 const query=useQuery({queryKey:['axle-review',session.carrier,session.uid,loadId,truckId,trailerId],queryFn:()=>request<Review>(session,'axle-review?'+new URLSearchParams({loadId,truckId,trailerId})),enabled:open&&!!load&&!!truck&&!!trailer&&online,refetchInterval:online?2000:false,retry:false});
 const selectors=[{label:'Assessment load',value:loadId,change:setLoad,items:state.loads},{label:'Assessment truck',value:truckId,change:setTruck,items:state.resources.filter(r=>r.kind==='truck')},{label:'Assessment trailer',value:trailerId,change:setTrailer,items:state.resources.filter(r=>r.kind==='trailer')}];
 const data=query.data,documents=(state.documents??[]).filter(d=>d.load_id===loadId&&d.status==='stored'&&d.sha256);
 const ready=online&&!busy&&!query.isError&&!query.isFetching&&!!data&&!!load&&!!truck&&!!trailer;
 const source=draft?.documents.find(d=>d.id===documentId),currentSource=state.documents?.find(d=>d.id===documentId);
 const stale=!!draft&&(draft.loadVersion!==load?.version||draft.truckVersion!==truck?.version||draft.trailerVersion!==trailer?.version||draft.historyId!==(data?.history[0]?.id??'')||!!source&&(source.version!==currentSource?.version||source.sha256!==currentSource?.sha256||currentSource?.status!=='stored'));
 const num=(k:string)=>values[k]?.trim()?Number(values[k]):NaN;
 const configuration={tractorWheelbaseM:num('tractorWheelbaseM'),fifthWheelFromSteerM:num('fifthWheelFromSteerM'),trailerSpanM:num('trailerSpanM'),emptyKg:{steer:num('emptySteer'),drive:num('emptyDrive'),trailer:num('emptyTrailer')},limitsKg:{steer:num('limitSteer'),drive:num('limitDrive'),trailer:num('limitTrailer')},grossLimitKg:num('grossLimitKg'),driveAxles:num('driveAxles'),trailerAxles:num('trailerAxles'),equalizedGroups:true as const};
 let result:Result|undefined,calculationError='';
 if(draft&&fields.every(([key])=>values[key]?.trim()))try{result=calculateAxles(configuration,draft.payloadLb,num('cargoCgFromKingpinM'));}catch{calculationError='Check positive masses and dimensions, whole axle counts from 1 to 3, and cargo/fifth-wheel positions within the supported spans.';}
 const parsed=draft?axleReviewSchema.safeParse({loadId:draft.loadId,truckId:draft.truckId,trailerId:draft.trailerId,documentId,expectedDocumentVersion:source?.version,expectedLoadVersion:draft.loadVersion,expectedTrailerVersion:draft.trailerVersion,configuration,cargoCgFromKingpinM:num('cargoCgFromKingpinM'),sourceNote:note,reason,acknowledgeModeledLoads:ack}):null;
 async function download(doc:ShipmentDocument){try{await downloadOriginal(session,doc);}catch(e){setMessage(String(e));}}
 function begin(){if(!ready||!load||!truck||!trailer||!load.weightLb)return;setDraft({loadId,truckId,trailerId,truckVersion:truck.version,loadVersion:load.version,trailerVersion:trailer.version,payloadLb:load.weightLb,documents,historyId:data?.history[0]?.id??''});setValues({});setDocument('');setReason('');setNote('');setAck(false);setConfirm(false);setMessage('');}
 function copyPrevious(){const input=data?.history[0]?.body.input;if(!input)return;const c=input.configuration;setValues(Object.fromEntries(Object.entries({...c,cargoCgFromKingpinM:input.cargoCgFromKingpinM,emptySteer:c.emptyKg.steer,emptyDrive:c.emptyKg.drive,emptyTrailer:c.emptyKg.trailer,limitSteer:c.limitsKg.steer,limitDrive:c.limitsKg.drive,limitTrailer:c.limitsKg.trailer}).map(([k,v])=>[k,String(v)])));}
 async function save(){if(!draft||!parsed?.success||!ready||stale||!confirm)return;setBusy(true);setMessage('');try{const ok=await send('review-axles',parsed.data,draft.truckVersion);if(ok){setDraft(null);setMessage('Assessment synchronized. Check the current screening; dispatch approval remains separate.');await query.refetch();}else setMessage('Assessment was not confirmed. Inspect Activity before retrying; any queued request retains these original versions.');}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 return <details className="panel axle-review" onToggle={e=>{if(e.target===e.currentTarget)setOpen(e.currentTarget.open);}}><summary>Axle loading review</summary><p>Check a load against its tractor and trailer configuration before dispatch. Gross weight can pass while an axle group is overloaded.</p><div className="axle-fields">{selectors.map(({label,value,change,items})=><label key={label}>{label}<select value={value} onChange={e=>{change(e.target.value);setMessage('');}}><option value="">Choose {label.split(' ')[1]}</option>{items.map(i=><option key={i.id} value={i.id}>{i.id}</option>)}</select></label>)}</div>
 {!online&&<p className="notice">Offline. Cached history may be outdated; reconnect before recording an assessment.</p>}{query.isLoading&&<p role="status">Loading axle evidence…</p>}{query.isError&&<p role="alert">Could not refresh axle evidence. {query.error.message} <button disabled={!online} onClick={()=>void query.refetch()}>Refresh axle evidence</button></p>}
 {data&&<><h3>{online?'Current':'Cached'} screening · {data.proof.required?(data.proof.eligible?'Eligible under supported checks':'Held for review'):'Declared synthetic screening'}</h3>{data.proof.reasons.map(r=><p className="notice" key={r}>{r}</p>)}{data.proof.note&&<p>{data.proof.note}</p>}{data.proof.result&&<Results result={data.proof.result}/>}<p className="fine">{load?.weightLb?.toLocaleString('en-CA')??'Missing'} lb stored payload · {load?.provenance} source. Configured limits must come from reviewed vehicle evidence.</p>{!documents.length&&<p>Upload a supporting file for this load under Evidence & billing to begin.</p>}<button disabled={!ready||!documents.length||!load?.weightLb} onClick={begin}>New axle assessment</button>
 <details><summary>Assessment history · {data.history.length} {data.history.length===1?'revision':'revisions'}</summary>{!data.history.length&&<p>No source-bound assessments recorded for this combination.</p>}{data.history.map(h=>{const doc=state.documents?.find(d=>d.id===h.body.document.id),matches=doc?.version===h.body.document.version&&doc?.sha256===h.body.document.sha256;return <article key={h.id} className="axle-history"><h3>Revision {h.revision} · {h.body.result.eligible?'Configured limits passed':'Configured limit exceeded'}</h3><p>{h.body.input.reason}</p><p>{h.body.input.sourceNote}</p><p className="fine">{h.reviewed_by} · {new Date(h.recorded_at).toLocaleString('en-CA',{timeZone:'America/Toronto'})} ET · source v{h.body.document.version}</p><code>{h.body.document.sha256}</code><button disabled={!online||!matches} onClick={()=>doc&&void download(doc)}>Download reviewed source</button>{!matches&&<p className="notice">The current document differs from this historical review. This revision retains its original source identity.</p>}<details><summary>Recorded calculation and geometry</summary><Results result={h.body.result}/><p>Tractor wheelbase {h.body.input.configuration.tractorWheelbaseM} m · fifth wheel {h.body.input.configuration.fifthWheelFromSteerM} m from steer · trailer span {h.body.input.configuration.trailerSpanM} m · cargo centre {h.body.input.cargoCgFromKingpinM} m from kingpin.</p></details></article>;})}</details></>}
 {message&&<p role="status">{message}</p>}
 {draft&&<Modal title="Review axle loading" description={`${draft.loadId} · ${draft.truckId} + ${draft.trailerId} · ${draft.payloadLb.toLocaleString('en-CA')} lb stored cargo. Record evidence before requesting dispatch approval.`} onClose={()=>{if(!busy)setDraft(null);}}><fieldset disabled={busy||confirm} className="axle-editor"><legend>Source and supported configuration</legend><label>Axle source document<select value={documentId} onChange={e=>setDocument(e.target.value)}><option value="">Choose stored source</option>{draft.documents.map(d=><option key={d.id} value={d.id}>{d.extraction.filename} · v{d.version}</option>)}</select></label><button disabled={!source||!online||stale} onClick={()=>source&&void download(source)}>Download source for review</button>{source&&<p className="fine axle-hash">SHA-256 {source.sha256}</p>}<p>Use the empty coupled combination's masses once. Supported geometry: one tractor, one semitrailer, equalized groups; cargo between kingpin and trailer group, fifth wheel between steer and drive groups.</p>{!!data?.history.length&&<button onClick={copyPrevious}>Copy previous inputs for rechecking</button>}<div className="axle-fields">{fields.map(([key,label])=><label key={key}>{label}<input type="number" inputMode="decimal" step={key.endsWith('Axles')?'1':'any'} value={values[key]??''} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))}/></label>)}</div><label>Source evidence note<textarea minLength={20} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Page, empty weights, geometry, ratings and cargo position checked."/></label><label>Assessment reason<textarea minLength={20} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="checkbox-label"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed the source and equalized configuration. These are static modeled loads, not scale measurements or legal clearance.</label></fieldset>
 {calculationError&&<p role="alert">{calculationError}</p>}{result&&<Results result={result}/>}<p className="notice">Saving activates required assessments for every subsequent load on {draft.truckId}. Changing its configuration invalidates older assessments. A failed assessment is retained and blocks this combination.</p>{stale&&<p role="alert">Evidence changed while this review was open. Close and start a new assessment using current versions.</p>}{query.isError&&<p role="alert">Current axle evidence could not be checked. Close this review and refresh the evidence before recording.</p>}{!online&&<p role="alert">Reconnect and refresh evidence before recording.</p>}{confirm?<><p><strong>Record this reviewed revision?</strong> The server rechecks the source and resource versions. This does not assign the load or approve a route.</p><button disabled={busy} onClick={()=>setConfirm(false)}>Back to inputs</button><button className="primary" disabled={!ready||stale||!parsed?.success} onClick={()=>void save()}>{busy?'Recording assessment…':'Record assessment'}</button></>:<button className="primary" disabled={!ready||stale||!parsed?.success} onClick={()=>setConfirm(true)}>Review before recording</button>}{message&&<p role="status">{message}</p>}</Modal>}
 </details>;
}
