import {RouteGeometry} from './RouteGeometry';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {request,type State,type Session,type SendCommand} from './api';
import {Modal} from './ReviewDialog';
type Area={id?:string;west:number;east:number;south:number;north:number};
type Review={id:string;revision:number;status:string;approved_by?:string;approved_at?:string;body:{assignmentVersion:number;loadVersion:number;closures:Area[];evaluatedAt:string;eligible:boolean;reasons:string[];resources?:{id:string;version:number}[];drivingMinutes?:number;dutyMinutes?:number;completionAt?:string;hasToll?:boolean;telemetryId?:string;originAt?:string;note?:string;route?:any;routeFingerprint?:string}};
type Reviews={receipts:{route_revision_id:string;acknowledged_by:string;acknowledged_at:string}[];assignmentVersion:number;closures:{id:string;area:Area;observed_at:string;source_ref:string;reason:string;provenance:string;recorded_by:string}[];revisions:Review[]};
const date=(at?:string)=>at?new Date(at).toLocaleString('en-CA',{timeZone:'America/Toronto',dateStyle:'medium',timeStyle:'short'})+' ET':'Unavailable';
export function ClosureReview({state,session,send,online}:{state:State;session:Session;send:SendCommand;online:boolean}){
 const [open,setOpen]=useState(false),[selected,setSelected]=useState(''),[west,setWest]=useState(''),[east,setEast]=useState(''),[south,setSouth]=useState(''),[north,setNorth]=useState(''),[observed,setObserved]=useState(''),[source,setSource]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirm,setConfirm]=useState<Review|null>(null),[ack,setAck]=useState(false);
 const trips=state.assignments.filter(a=>a.status==='accepted'),trip=trips.find(a=>a.id===selected),load=state.loads.find(l=>l.id===trip?.loadId);
 const reviews=useQuery({queryKey:['route-reviews',session.carrier,session.uid,selected],queryFn:()=>request<Reviews>(session,`route-reviews?assignmentId=${encodeURIComponent(selected)}`),enabled:open&&!!trip&&online,refetchInterval:online?2000:false,retry:false});
 const data=reviews.data;
 const stale=(r:Review)=>r.status==='pending'&&(!trip||r.body.assignmentVersion!==trip.version||r.body.loadVersion!==load?.version||(r.body.resources??[]).some(v=>state.resources.find(x=>x.id===v.id)?.version!==v.version)||r.body.closures.length!==(data?.closures.length??0));
 const outdatedApproval=(r:Review)=>r.status==='approved'&&r.body.closures.length!==(data?.closures.length??0);
 const ready=online&&!busy&&!reviews.isError&&!!data&&!!trip;
 function select(id:string){setSelected(id);setConfirm(null);setAck(false);setWest('');setEast('');setSouth('');setNorth('');setObserved('');setSource('');setReason('');setError('');setNotice('');}
 async function act(path:string,body:Record<string,unknown>,version:number,message:string){setBusy(true);setError('');setNotice('');try{if(await send(path,body,version)){await reviews.refetch();setNotice(message);setConfirm(null);setAck(false);}else setError('The command was not confirmed. Review the activity queue and refresh before trying a new revision.');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 function synthetic(){setWest('-80.5314');setEast('-80.5294');setSouth('43.273031');setNorth('43.275031');setObserved(state.scenarios.find(s=>s.id==='recovery')?.clock??'');setSource('RoadStar synthetic closure scenario');setReason('Synthetic road closure ahead of this trip; inspect the truck-feasible alternate.');setNotice('Synthetic bounds populated. Recording this closure is a separate action.');}
 return <details className="closure-review panel" onToggle={e=>setOpen(e.currentTarget.open)}><summary>Road closures & route revisions</summary>{open&&<><div className="panel-heading"><div><p className="eyebrow">Observed disruption · reviewed response</p><h2>Keep the route accountable</h2></div></div><p>Record the source. Compare remaining work, then approve a revision. Existing GPS and reservation history stay visible.</p>
 <label>Active trip<select aria-label="Closure trip" value={selected} disabled={busy} onChange={e=>select(e.target.value)}><option value="">Choose an accepted trip</option>{trips.map(t=><option key={t.id} value={t.id}>{t.loadId} · {t.driverId} · {t.truckId}</option>)}</select></label>{!trips.length&&<p className="notice">No accepted trips are available for route review.</p>}
 {trip&&<><p className="fine">{load?.provenance} · {trip.driverId} / {trip.truckId} / {trip.trailerId} · Reserved until {date(trip.endAt)}</p>{reviews.isLoading&&<p role="status">Loading closure evidence…</p>}{reviews.isError&&<p role="alert" className="error">Closure evidence unavailable. Refresh the connection before making a decision.</p>}
 <div className="closure-columns"><div><h3>Record an observed closure</h3><p className="fine">Bounds exclude all roads within the rectangle. Use a sourced closure, not an inferred traffic slowdown.</p>{load?.provenance==='synthetic'&&<button disabled={!ready} onClick={synthetic}>Fill synthetic closure example</button>}
 <form onSubmit={e=>{e.preventDefault();void act('report-closure',{assignmentId:trip.id,area:{west:Number(west),east:Number(east),south:Number(south),north:Number(north)},observedAt:observed,sourceRef:source,reason},trip.version,'Closure recorded. Rehearse the remaining route; no route has been adopted.');}}><fieldset disabled={!ready} className="closure-form"><div className="closure-bounds">{([['West longitude',west,setWest],['East longitude',east,setEast],['South latitude',south,setSouth],['North latitude',north,setNorth]] as const).map(([label,value,set])=><label key={label}>{label}<input required type="number" step="any" aria-label={label} value={value} onChange={e=>set(e.target.value)}/></label>)}</div><label>Observed at, with time zone<input required aria-label="Closure observed at" placeholder="2026-09-13T08:30:00-04:00" value={observed} onChange={e=>setObserved(e.target.value)}/></label><label>Source reference<input required minLength={3} aria-label="Closure source" value={source} onChange={e=>setSource(e.target.value)}/></label><label>Reason<textarea required minLength={10} aria-label="Closure reason" value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="submit">Record closure</button></fieldset></form>
 </div><div><h3>Retained observations</h3>{data?.closures.length?data.closures.map(c=><article key={c.id} className="closure-source"><strong>{c.reason}</strong><p>{date(c.observed_at)} · {c.provenance}</p><p className="fine">Source: {c.source_ref}<br/>Recorded by {c.recorded_by}</p><p className="fine">Bounds {c.area.west}, {c.area.south} → {c.area.east}, {c.area.north}</p></article>):<p className="fine">No closure recorded for this trip.</p>}<button className="primary" disabled={!ready||!data?.closures.length} onClick={()=>void act('rehearse-route',{assignmentId:trip.id},trip.version,'Remaining route reviewed. Inspect the result before approval.')}>{busy?'Checking current evidence…':'Rehearse remaining route'}</button></div></div>
 {data?.revisions.map(r=><article key={r.id} className="closure-result" aria-label="Route revision evidence"><div className="panel-heading"><h3>{r.status==='unresolved'?'No feasible revision':r.status==='approved'?'Approved route revision':'Proposed route revision'}</h3><span className="tag">{stale(r)?'Stale':r.status} · r{r.revision}</span></div><p className="fine">Evaluated {date(r.body.evaluatedAt)} · {r.body.closures.length} closure area(s)</p>{r.body.drivingMinutes!==undefined&&<div className="closure-metrics"><div><span>Remaining driving</span><strong>{r.body.drivingMinutes} min</strong></div><div><span>Remaining on-duty work</span><strong>{r.body.dutyMinutes} min</strong></div><div><span>Modeled completion</span><strong>{date(r.body.completionAt)}</strong></div></div>}{r.body.route&&<RouteGeometry route={r.body.route} closures={r.body.closures}/>} {r.body.hasToll&&<p className="notice">Alternate route includes toll segments. Toll charges have not been estimated.</p>}{r.body.reasons.map((v,i)=><p key={i} className="notice">{v}</p>)}{r.status==='unresolved'&&<p>Keep the trip unresolved and review another operational recovery. No route was approved.</p>}{r.body.telemetryId&&<p className="fine">Origin: same-trip GPS at {date(r.body.originAt)}. Remaining stops, current duty budgets and supplied truck dimensions were checked.</p>}<p className="fine">{r.body.note??'Missing or infeasible evidence remains visible.'}</p>{stale(r)&&<p className="notice">The trip or evidence changed. Rehearse again before approval.</p>}{r.status==='pending'&&<button className="primary" disabled={!ready||stale(r)} onClick={()=>{setConfirm(r);setAck(false);}}>Review route approval</button>}{outdatedApproval(r)&&<p className="notice">Historical approval: additional closures were recorded. This revision does not cover the current closure evidence.</p>}{data.receipts?.filter(x=>x.route_revision_id===r.id).map(x=><p role="status" key={x.route_revision_id}>Driver receipt recorded by {x.acknowledged_by} at {date(x.acknowledged_at)}. Route adoption remains separate.</p>)}{r.status==='approved'&&<p role="status">Approved by {r.approved_by} at {date(r.approved_at)}. Driver receipt and route adoption are separate; approval does not prove the truck followed this route.</p>}</article>)}
 </>}{!online&&<p className="notice">Offline. Displayed evidence may be stale; reconnect to record, rehearse or approve.</p>}{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 {confirm&&trip&&<Modal title="Approve this route revision?" description={`${trip.loadId} · ${trip.driverId} / ${trip.truckId}. The server rechecks current evidence. Original observations remain unchanged.`} onClose={()=>{if(!busy)setConfirm(null);}}><p>{confirm.body.drivingMinutes} min driving · {confirm.body.dutyMinutes} min on duty · complete {date(confirm.body.completionAt)}</p>{confirm.body.hasToll&&<p className="notice">Includes toll segments; charges are not estimated.</p>}<label className="hos-ack"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed the modeled route, remaining work and toll information. Driver receipt and adoption are separate.</label>{stale(confirm)&&<p role="alert" className="notice">Evidence changed. Close this review and rehearse again.</p>}<button className="primary" disabled={!ready||!ack||stale(confirm)} onClick={()=>void act('approve-route',{routeRevisionId:confirm.id,acknowledgeModeledRoute:true},confirm.revision,'Route revision approved. Driver receipt and adoption remain separate.')}>Approve route revision</button></Modal>}
 </>}</details>;
}
