import {Component,lazy,Suspense,useCallback,useEffect,useMemo,useRef,useState,type KeyboardEvent,type ReactNode} from 'react';
import {ApiError,request,type Session} from './api';
import {comparisonCompatibility,corridorComparisonMetrics,corridorComparisonMilestones,corridorComparisonSpeedProfile,corridorMilestones,eventAt,eventAtOrBefore,mergeCorridorPage,routeAt,type CorridorComparisonSpeedProfileEntry,type CorridorEvent,type CorridorPage,type CorridorRecording,type CorridorRoute} from './corridor-replay-model';
import type {CorridorCamera} from './CorridorScene';
import './corridor-replay.css';

const CorridorScene=lazy(()=>import('./CorridorScene'));
export type ReplayRun={run_id:string;assignment_id:string;event_count:number;conditions_hash:string};
export type RecordingLoader=(run:ReplayRun,onProgress:(progress:Progress)=>void)=>Promise<CorridorRecording>;
export type CorridorReplayProps={run:ReplayRun;matchedRun?:ReplayRun|null;session:Session;online:boolean;recordingLoader?:RecordingLoader;initialOpen?:boolean;initialCompare?:boolean};
type LoadState='idle'|'loading'|'ready'|'empty'|'error';
type Progress={loaded:number;total:number|null};

class SceneBoundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true};}render(){return this.state.failed?this.props.fallback:this.props.children;}}

const stamp=(value:string)=>new Date(value).toLocaleString('en-CA',{timeZone:'America/Toronto',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit'})+' ET';
const elapsed=(seconds:number)=>{const value=Math.max(0,Math.floor(seconds)),hours=Math.floor(value/3600),minutes=Math.floor(value%3600/60);return `${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`;};
const signedElapsed=(seconds:number)=>`${seconds>=0?'+':'−'}${elapsed(Math.abs(seconds))}`;
const short=(value:string)=>value.length>14?`${value.slice(0,8)}…${value.slice(-4)}`:value;

async function fetchRecording(run:ReplayRun,session:Session,onProgress:(progress:Progress)=>void){
 let merged:CorridorRecording|null=null,offset=0,snapshot:string|undefined;
 for(;;){const params=new URLSearchParams({offset:String(offset),limit:'1000'});if(snapshot)params.set('snapshot',snapshot);const page=await request<CorridorPage>(session,`simulator/${run.run_id}/presentation?${params}`);merged=mergeCorridorPage(merged,page);snapshot=merged.snapshot;onProgress({loaded:merged.events.length,total:merged.total});if(page.next_offset===null)break;offset=page.next_offset;}
 if(!merged)throw new Error('Recording unavailable.');
 return merged;
}

function diagramPath(route:CorridorRoute,position:{lat:number;lng:number}){
 const latitude=route.geometry.coordinates.reduce((sum,point)=>sum+point[1],0)/route.geometry.coordinates.length,longitudeScale=Math.max(.15,Math.cos(latitude*Math.PI/180)),points=route.geometry.coordinates.map(([lng,lat])=>[lng*longitudeScale,lat] as [number,number]),minX=Math.min(...points.map(point=>point[0])),maxX=Math.max(...points.map(point=>point[0])),minY=Math.min(...points.map(point=>point[1])),maxY=Math.max(...points.map(point=>point[1]));
 const spanX=Math.max(maxX-minX,.000001),spanY=Math.max(maxY-minY,.000001),scale=Math.min(920/spanX,330/spanY),offsetX=(1000-spanX*scale)/2,offsetY=(405-spanY*scale)/2;
 const project=([lng,lat]:[number,number])=>[offsetX+(lng*longitudeScale-minX)*scale,405-offsetY-(lat-minY)*scale] as const;
 return{route:route.geometry.coordinates.map(project).map(point=>point.join(',')).join(' '),position:project([position.lng,position.lat])};
}

function CorridorDiagram({recording,index,comparison,speedProfile}:{recording:CorridorRecording;index:number;comparison?:{baseline:CorridorEvent;disrupted:CorridorEvent};speedProfile?:CorridorComparisonSpeedProfileEntry[]}){
 const event=eventAt(recording,index),route=routeAt(recording,index);if(!event||!route)return null;
 const path=diagramPath(route,event.sample.position),stops=route.stop_indices.map(i=>route.geometry.coordinates[i]).filter(Boolean).map(point=>diagramPath(route,{lng:point[0],lat:point[1]}).position);
 const comparePoints=comparison?{baseline:diagramPath(route,comparison.baseline.sample.position).position,disrupted:diagramPath(route,comparison.disrupted.sample.position).position}:null;
 const profileTicks=(speedProfile??[]).filter(entry=>entry.routeOrdinal===route.ordinal).map(entry=>({
  key:`${entry.baseline.eventId}-${entry.disrupted.eventId}`,
  baseline:entry.baseline.speedKph===null?null:{point:diagramPath(route,entry.baseline.position).position,height:Math.max(3,entry.baseline.speedKph/2.7)},
  disrupted:entry.disrupted.speedKph===null?null:{point:diagramPath(route,entry.disrupted.position).position,height:Math.max(3,entry.disrupted.speedKph/2.7)},
 }));
 return <div className="corridor-diagram" role="img" aria-label={`Recorded route diagram at ${stamp(event.sample.at)}${profileTicks.length?` with ${profileTicks.length} exact paired speed samples`:``}`}>
  <svg viewBox="0 0 1000 405" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><defs><pattern id="corridor-grid" width="50" height="50" patternUnits="userSpaceOnUse"><path d="M 50 0 L 0 0 0 50" fill="none" stroke="#3b403e" strokeWidth="1"/></pattern></defs><rect width="1000" height="405" fill="url(#corridor-grid)"/><polyline points={path.route} fill="none" stroke="#454a48" strokeWidth="18" strokeLinejoin="round"/><polyline points={path.route} fill="none" stroke="#e65c32" strokeWidth="5" strokeLinejoin="round"/>{profileTicks.map(tick=><g key={tick.key} className="corridor-diagram-speed-tick">{tick.baseline&&<line x1={tick.baseline.point[0]-5} y1={tick.baseline.point[1]} x2={tick.baseline.point[0]-5} y2={tick.baseline.point[1]-tick.baseline.height} stroke="#f5f3ed" strokeWidth="4" strokeLinecap="round"/>}{tick.disrupted&&<line x1={tick.disrupted.point[0]+5} y1={tick.disrupted.point[1]} x2={tick.disrupted.point[0]+5} y2={tick.disrupted.point[1]-tick.disrupted.height} stroke="#e65c32" strokeWidth="5"/>}</g>)}{stops.map((point,i)=><circle key={`${point[0]}-${point[1]}-${i}`} cx={point[0]} cy={point[1]} r="9" fill={i===stops.length-1?'#e65c32':'#f5f3ed'} stroke="#242729" strokeWidth="4"/>)}{comparePoints?<><line x1={comparePoints.baseline[0]} y1={comparePoints.baseline[1]} x2={comparePoints.disrupted[0]} y2={comparePoints.disrupted[1]} stroke="#aeb1a9" strokeWidth="3" strokeDasharray="7 8"/><g transform={`translate(${comparePoints.baseline[0]} ${comparePoints.baseline[1]})`}><circle r="18" fill="#242729" stroke="#f5f3ed" strokeWidth="6"/><rect x="-8" y="-13" width="16" height="26" rx="3" fill="#f5f3ed"/></g><g transform={`translate(${comparePoints.disrupted[0]} ${comparePoints.disrupted[1]})`}><circle r="18" fill="#fff0df"/><rect x="-9" y="-15" width="18" height="30" rx="3" fill="#e65c32"/></g></>:<g transform={`translate(${path.position[0]} ${path.position[1]})`}><circle r="19" fill="#fff0df"/><rect x="-11" y="-18" width="22" height="36" rx="4" fill="#e65c32"/><path d="M-6 -18 L0 -27 L6 -18" fill="#f5f3ed"/></g>}</svg>
  <p>{comparison?speedProfile?.length?'Ivory cylinders / orange fins · height = recorded speed':'Ivory baseline · orange modeled disruption · exact at-or-before observations':'Plan diagram · exact source point on its recorded route epoch'}</p>
 </div>;
}

export function CorridorReplay({run,matchedRun,session,online,recordingLoader,initialOpen=false,initialCompare=false}:CorridorReplayProps){
 const[open,setOpen]=useState(initialOpen),[recording,setRecording]=useState<CorridorRecording|null>(null),[loadState,setLoadState]=useState<LoadState>('idle'),[progress,setProgress]=useState<Progress>({loaded:0,total:null}),[error,setError]=useState(''),[reload,setReload]=useState(0),[cursor,setCursor]=useState(0),[playing,setPlaying]=useState(false),[pace,setPace]=useState(60),[camera,setCamera]=useState<CorridorCamera>('overview'),[diagram,setDiagram]=useState(false),[reduced,setReduced]=useState(false),[savedAt,setSavedAt]=useState<string|null>(null),[compareMode,setCompareMode]=useState(initialCompare),[speedProfileVisible,setSpeedProfileVisible]=useState(true),[matchedRecording,setMatchedRecording]=useState<CorridorRecording|null>(null),[matchedState,setMatchedState]=useState<LoadState>('idle'),[matchedProgress,setMatchedProgress]=useState<Progress>({loaded:0,total:null}),[matchedError,setMatchedError]=useState(''),[matchedReload,setMatchedReload]=useState(0);
 const canLoad=online||!!recordingLoader;
 const sourceRevision=`${run.event_count}:${run.conditions_hash}`;
 const matchedRevision=matchedRun?`${matchedRun.run_id}:${matchedRun.event_count}:${matchedRun.conditions_hash}`:'';
 const cursorRef=useRef(cursor);cursorRef.current=cursor;
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)'),update=()=>setReduced(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 useEffect(()=>{if(reduced)setPlaying(false);},[reduced]);
 useEffect(()=>{if(!open)setPlaying(false);},[open]);
 useEffect(()=>{setRecording(null);setCursor(0);setPlaying(false);setLoadState('idle');setProgress({loaded:0,total:null});setError('');setCompareMode(initialCompare);setSpeedProfileVisible(true);},[run.run_id,sourceRevision,initialCompare]);
 useEffect(()=>{setMatchedRecording(null);setMatchedState('idle');setMatchedProgress({loaded:0,total:null});setMatchedError('');},[matchedRevision]);
 useEffect(()=>{
  if(!open||!canLoad)return;
  let active=true;setLoadState('loading');setError('');setProgress({loaded:0,total:null});setPlaying(false);
  void(async()=>{
   try{const merged=await (recordingLoader?recordingLoader(run,value=>{if(active)setProgress(value);}):fetchRecording(run,session,value=>{if(active)setProgress(value);}));
    if(!active||!merged)return;setRecording(merged);setCursor(0);setSavedAt(new Date().toISOString());setLoadState(merged.events.length?'ready':'empty');
   }catch(reason){if(!active)return;setRecording(null);setProgress({loaded:0,total:null});setLoadState('error');setError(reason instanceof ApiError&&reason.status===409?'Recording changed while loading. Partial pages were discarded.':reason instanceof Error?reason.message:'Recording unavailable.');}
 })();return()=>{active=false;};
 },[open,canLoad,reload,run.run_id,sourceRevision,session.carrier,session.token,session.uid,recordingLoader]);
 useEffect(()=>{
  if(!open||!compareMode||!canLoad||!matchedRun)return;
  let active=true;setMatchedState('loading');setMatchedError('');setMatchedProgress({loaded:0,total:null});setPlaying(false);
  void(async()=>{try{const loaded=await (recordingLoader?recordingLoader(matchedRun,value=>{if(active)setMatchedProgress(value);}):fetchRecording(matchedRun,session,value=>{if(active)setMatchedProgress(value);}));if(!active)return;setMatchedRecording(loaded);setMatchedState(loaded.events.length?'ready':'empty');}
   catch(reason){if(!active)return;setMatchedRecording(null);setMatchedState('error');setMatchedError(reason instanceof ApiError&&reason.status===409?'Matched recording changed while loading. Partial pages were discarded.':reason instanceof Error?reason.message:'Matched recording unavailable.');}
  })();return()=>{active=false;};
 },[open,compareMode,canLoad,matchedReload,matchedRevision,session.carrier,session.token,session.uid,recordingLoader]);
 const compatibility=useMemo(()=>recording&&matchedRecording?comparisonCompatibility(recording,matchedRecording):null,[recording,matchedRecording]);
 const speedProfile=useMemo(()=>compareMode&&compatibility?.ok&&recording&&matchedRecording?corridorComparisonSpeedProfile(recording,matchedRecording):[],[compareMode,compatibility,recording,matchedRecording]);
 const selected=recording?eventAt(recording,cursor):null,comparison=useMemo(()=>compareMode&&compatibility?.ok&&recording&&matchedRecording&&selected?corridorComparisonMetrics(recording,matchedRecording,selected.elapsed_seconds):null,[compareMode,compatibility,recording,matchedRecording,selected]);
 const route=recording?routeAt(recording,cursor):null,milestones=useMemo(()=>{if(!recording)return[];if(comparison&&matchedRecording)return corridorComparisonMilestones(recording,matchedRecording).map(item=>{const event=eventAtOrBefore(recording,item.elapsedSeconds);return{...item,index:event?recording.events.findIndex(candidate=>candidate.sample.id===event.sample.id):0};});return corridorMilestones(recording).map(item=>({...item,elapsedSeconds:recording.events[item.index].elapsed_seconds}));},[recording,matchedRecording,comparison]);
 const visibleSpeedProfile=useMemo(()=>comparison&&speedProfileVisible?speedProfile.filter(entry=>entry.sharedTimeSeconds<=comparison.sharedTimeSeconds):[],[comparison,speedProfile,speedProfileVisible]);
 const maxCursor=useMemo(()=>{if(!recording?.events.length)return 0;if(!compareMode||!compatibility?.ok||!matchedRecording)return recording.events.length-1;const sharedEnd=Math.min(recording.events.at(-1)!.elapsed_seconds,matchedRecording.events.at(-1)!.elapsed_seconds),event=eventAtOrBefore(recording,sharedEnd);return event?recording.events.findIndex(candidate=>candidate.sample.id===event.sample.id):0;},[recording,matchedRecording,compareMode,compatibility]);
 useEffect(()=>{if(cursor>maxCursor){setCursor(maxCursor);setPlaying(false);}},[cursor,maxCursor]);
 useEffect(()=>{if(!playing||reduced||!recording?.events.length)return;const startIndex=cursorRef.current===maxCursor?0:Math.min(cursorRef.current,maxCursor),startElapsed=recording.events[startIndex].elapsed_seconds,start=performance.now();if(startIndex!==cursorRef.current)setCursor(startIndex);let frame=0;
  const tick=(now:number)=>{const target=startElapsed+(now-start)/1000*pace,events=recording.events;let low=startIndex,high=maxCursor;while(low<high){const middle=Math.ceil((low+high)/2);if(events[middle].elapsed_seconds<=target)low=middle;else high=middle-1;}if(cursorRef.current!==low)setCursor(low);if(low>=maxCursor){setPlaying(false);return;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);
 },[playing,pace,recording,reduced,maxCursor]);
 const choose=useCallback((index:number)=>{setPlaying(false);setCursor(Math.max(0,Math.min(maxCursor,Math.round(index))));},[maxCursor]);
 function timelineKey(event:KeyboardEvent<HTMLInputElement>){if(!recording)return;if(event.key===' '){event.preventDefault();if(!reduced)setPlaying(value=>!value);}else if(event.key==='Home'){event.preventDefault();choose(0);}else if(event.key==='End'){event.preventDefault();choose(maxCursor);}else if(event.key==='ArrowLeft'||event.key==='ArrowDown'){event.preventDefault();choose(cursor-1);}else if(event.key==='ArrowRight'||event.key==='ArrowUp'){event.preventDefault();choose(cursor+1);}}
 const visualComparison=comparison?{baseline:comparison.baseline,disrupted:comparison.disrupted}:undefined;
 const fallback=recording?<CorridorDiagram recording={recording} index={cursor} comparison={visualComparison} speedProfile={visibleSpeedProfile}/>:null,percentage=progress.total?Math.round(progress.loaded/progress.total*100):0,matchedPercentage=matchedProgress.total?Math.round(matchedProgress.loaded/matchedProgress.total*100):0;
 return <section className="corridor-replay" aria-label="Recorded corridor replay"><div className={`corridor-heading ${open?'is-open':''}`}><div className="corridor-heading-copy"><p className="eyebrow">RECORDED CORRIDOR / 02</p><h3>Read the wait. Then watch the road answer.</h3><p>{run.assignment_id} · acknowledged synthetic history</p></div><button className="primary" onClick={()=>setOpen(value=>!value)}>{open?'Close replay':'Open 3D corridor replay'}</button></div>{open&&<>
  {loadState==='loading'&&<div className="corridor-load" role="status"><span>Assembling one frozen recording</span><strong>{progress.total?`${progress.loaded.toLocaleString('en-CA')} / ${progress.total.toLocaleString('en-CA')}`:'Requesting first page'}</strong><div><i style={{width:`${percentage}%`}}/></div><small>Only acknowledged source events are loaded. The simulator clock is untouched.</small></div>}
  {!online&&!recording&&!recordingLoader&&<div className="corridor-state" role="status"><strong>Recording unavailable offline</strong><p>Connect before the first load. A completed recording remains available if the connection drops later.</p></div>}
  {loadState==='error'&&<div className="corridor-state is-error" role="alert"><strong>Recording not assembled</strong><p>{error}</p><button disabled={!canLoad} onClick={()=>setReload(value=>value+1)}>Reload from first page</button></div>}
  {loadState==='empty'&&<div className="corridor-state"><strong>No acknowledged observations</strong><p>This run has no historical positions to display. Pending generated samples are excluded.</p><button disabled={!canLoad} onClick={()=>setReload(value=>value+1)}>Check again</button></div>}
  {recording&&selected&&route&&<><div className="corridor-toolbar"><div role="group" aria-label="Corridor view"><button aria-pressed={!diagram&&camera==='overview'} onClick={()=>{setDiagram(false);setCamera('overview');}}>Perspective</button><button aria-pressed={!diagram&&camera==='plan'} onClick={()=>{setDiagram(false);setCamera('plan');}}>Plan</button><button aria-label={diagram?'Show 3D':'Use diagram'} aria-pressed={diagram} onClick={()=>setDiagram(value=>!value)}>Diagram</button></div>{comparison&&<button className="corridor-profile-toggle" aria-pressed={speedProfileVisible} onClick={()=>setSpeedProfileVisible(value=>!value)}>Speed profile</button>}{matchedRun&&<button className="corridor-compare-toggle" aria-pressed={compareMode} onClick={()=>{setPlaying(false);setCompareMode(value=>!value);setSpeedProfileVisible(true);}}>{compareMode?'Exit comparison':'Compare 401 slowdown'}</button>}</div>
   {compareMode&&matchedState==='loading'&&<div className="corridor-load corridor-compare-load" role="status"><span>Checking matched recording evidence</span><strong>{matchedProgress.total?`${matchedProgress.loaded.toLocaleString('en-CA')} / ${matchedProgress.total.toLocaleString('en-CA')}`:'Requesting first page'}</strong><div><i style={{width:`${matchedPercentage}%`}}/></div><small>Comparison appears only after basis hash, route and scenario start time match.</small></div>}
   {compareMode&&matchedState==='error'&&<div className="corridor-state is-error" role="alert"><strong>Matched recording not accepted</strong><p>{matchedError}</p><button disabled={!canLoad} onClick={()=>setMatchedReload(value=>value+1)}>Reload matched recording</button></div>}
   {compareMode&&matchedState==='empty'&&<div className="corridor-state is-error" role="alert"><strong>Matched recording has no evidence</strong><p>Both runs need acknowledged synthetic observations.</p></div>}
   {compareMode&&compatibility&&!compatibility.ok&&<div className="corridor-state is-error" role="alert"><strong>Matched recording rejected</strong><p>{compatibility.reason}</p></div>}
   {!online&&<p className="corridor-saved" role="status">Offline · saved recording from {savedAt?stamp(savedAt):'this session'}. Historical values are frozen.</p>}
   <div className={`corridor-stage ${diagram?'is-diagram':''} ${comparison?'is-comparing':''}`}><div className="corridor-stage-readout"><span>{comparison?'MODELED SYNTHETIC / MATCHED RUNS':'SOUTHERN ONTARIO / RECORDED ROUTE'}</span><strong>{comparison?`${comparison.baseline.sample.phase.replaceAll('_',' ')} / ${comparison.disrupted.sample.phase.replaceAll('_',' ')}`:selected.sample.phase.replaceAll('_',' ')}</strong><small>{comparison?`${elapsed(comparison.sharedTimeSeconds)} shared scenario time`:stamp(selected.sample.at)} · exact {comparison?'at-or-before observations':'observation'}</small><em>{comparison?'Ivory baseline · signal-orange disruption':`Epoch ${String(route.ordinal+1).padStart(2,'0')} · ${route.source}`}</em></div>{diagram?fallback:<SceneBoundary fallback={fallback}><Suspense fallback={<div className="corridor-scene-loading" role="status">Loading corridor renderer…</div>}><CorridorScene route={route} event={selected} comparison={visualComparison} speedProfile={visibleSpeedProfile} camera={camera} reducedMotion={reduced} playing={playing} onUnavailable={()=>setDiagram(true)}/></Suspense></SceneBoundary>}{comparison&&speedProfileVisible&&<div className="corridor-speed-legend" role="status"><span><i className="is-baseline"/>Baseline</span><span><i className="is-disrupted"/>Slowdown</span><strong>{visibleSpeedProfile.length} / {speedProfile.length} exact pairs</strong></div>}<p className="corridor-stage-note">{comparison?(speedProfileVisible?'Exact sampled observations · height = recorded speed · lateral spacing is diagrammatic · no interpolation':'Same basis · no interpolation · connector shows recorded progress gap'):'Source geometry · selected marker snaps to an acknowledged event'}</p></div>
   {comparison?<div className="corridor-instrument corridor-compare-instrument"><div className="corridor-primary-readout"><span>SHARED TIME</span><strong>{elapsed(comparison.sharedTimeSeconds)}</strong><small>Historical scenario cursor only</small></div><div><span>Progress gap</span><strong>{comparison.progressGapKm===null?'—':`${comparison.progressGapKm>=0?'+':''}${comparison.progressGapKm.toFixed(3)}`}</strong><small>km · baseline minus disruption</small></div><div><span>Slowdown / baseline</span><strong>{comparison.disrupted.sample.speedKph===null?'—':comparison.disrupted.sample.speedKph.toFixed(1)} / {comparison.baseline.sample.speedKph===null?'—':comparison.baseline.sample.speedKph.toFixed(1)}</strong><small>km/h · source age {comparison.disruptedObservationAgeSeconds.toFixed(0)}s / {comparison.baselineObservationAgeSeconds.toFixed(0)}s</small></div><div><span>Modeled finish delta</span><strong>{signedElapsed(comparison.modeledCompletionDeltaSeconds)}</strong><small>disruption minus baseline</small></div></div>:<div className="corridor-instrument"><div className="corridor-primary-readout"><span>VIEW TIME</span><strong>{elapsed(selected.elapsed_seconds)}</strong><small>Historical cursor only</small></div><div><span>Speed</span><strong>{selected.sample.speedKph===null?'—':selected.sample.speedKph.toFixed(1)}</strong><small>km/h · preceding interval</small></div><div><span>Odometer</span><strong>{selected.sample.odometerKm===null?'—':selected.sample.odometerKm.toFixed(3)}</strong><small>km · source reading</small></div><div><span>Duty</span><strong>{selected.sample.duty.replaceAll('_',' ')}</strong><small>at observation instant</small></div></div>}
   <div className="corridor-transport"><div className="corridor-control-grid"><div className="corridor-playback" role="group" aria-label="Historical playback"><button aria-label={playing?'Pause view playback':'Play view playback'} disabled={reduced} aria-pressed={playing} onClick={()=>setPlaying(value=>!value)}>{playing?'Pause':'Play'}</button><button onClick={()=>choose(0)}>Restart</button></div><label className="corridor-pace">View pace<select value={pace} disabled={reduced} onChange={event=>setPace(Number(event.target.value))}><option value={30}>30×</option><option value={60}>60×</option><option value={120}>120×</option></select></label><label className="corridor-scrub"><span><b>{comparison?'Shared observation':'Observation'} {(cursor+1).toLocaleString('en-CA')}</b><small>{(maxCursor+1).toLocaleString('en-CA')} {comparison?'shared-time':'acknowledged'} events</small></span><input aria-label={comparison?'Matched recording shared timeline':'Recorded observation timeline'} type="range" min="0" max={maxCursor} step="1" value={Math.min(cursor,maxCursor)} onChange={event=>choose(Number(event.target.value))} onKeyDown={timelineKey}/></label><div className="corridor-milestones" aria-label={comparison?'Matched comparison milestones':'Recorded milestones'}>{milestones.map(milestone=><button key={milestone.id} aria-pressed={cursor===milestone.index} onClick={()=>choose(milestone.index)}><span>{milestone.label}</span><small>{elapsed(milestone.elapsedSeconds)}</small></button>)}</div>{reduced&&<p className="corridor-motion-note">Reduced motion is on. Use the slider, arrow keys, Home and End to move between exact events.</p>}</div></div>
   <details className="corridor-source"><summary>{comparison?'Matched source evidence':'Exact source event'}</summary><div className="corridor-source-summary"><p><span>{comparison?'Baseline / disruption observations':'Observation'}</span><code title={comparison?`${comparison.baseline.sample.id} / ${comparison.disrupted.sample.id}`:selected.sample.id} aria-label={comparison?`Baseline observation ${comparison.baseline.sample.id}; disrupted observation ${comparison.disrupted.sample.id}`:`Observation ${selected.sample.id}`}>{comparison?`${short(comparison.baseline.sample.id)} / ${short(comparison.disrupted.sample.id)}`:short(selected.sample.id)}</code></p><p><span>Route epoch</span><code title={selected.route_key} aria-label={`Route epoch ${selected.route_key}`}>{short(selected.route_key)}</code></p><p><span>{comparison?'Comparison basis':'Recording snapshot'}</span><code title={comparison?recording.comparison_basis_hash:recording.snapshot} aria-label={comparison?`Comparison basis ${recording.comparison_basis_hash}`:`Recording snapshot ${recording.snapshot}`}>{short(comparison?recording.comparison_basis_hash:recording.snapshot)}</code></p><p><span>Assignment / run</span><code title={`Assignment ${recording.assignment_id}; run ${recording.run_id}`} aria-label={`Assignment ${recording.assignment_id}; run ${recording.run_id}`}>{short(recording.assignment_id)}<br/>{short(recording.run_id)}</code></p></div><p className="corridor-source-note">{recording.evidence}. {recording.speed_semantics}. {recording.clock_semantics}. {comparison?'Matched values are modeled synthetic evidence selected at or before the shared time; no interpolation is performed.':''}</p><details className="corridor-source-full"><summary>Full source identifiers</summary><code>Observation {selected.sample.id}<br/>{comparison?`Matched observation ${comparison.baseline.sample.id===selected.sample.id?comparison.disrupted.sample.id:comparison.baseline.sample.id}\nComparison basis ${recording.comparison_basis_hash}\n`:''}Route epoch {selected.route_key}<br/>Recording snapshot {recording.snapshot}<br/>Assignment {recording.assignment_id}<br/>Run {recording.run_id}</code></details></details>
   <div className="corridor-foot"><span>{recording.events.length.toLocaleString('en-CA')} / {recording.total.toLocaleString('en-CA')} source events</span><span>{comparison?'Matched deterministic basis':`Route ${short(route.key)} · epoch ${route.ordinal+1} of ${recording.routes.length}`}</span><span>View controls issue no operational commands</span></div></>}
 </>}</section>;
}
