import {Component,lazy,Suspense,useCallback,useEffect,useMemo,useRef,useState,type KeyboardEvent,type ReactNode} from 'react';
import {ApiError,request,type Session} from './api';
import {corridorMilestones,eventAt,mergeCorridorPage,routeAt,type CorridorPage,type CorridorRecording,type CorridorRoute} from './corridor-replay-model';
import type {CorridorCamera} from './CorridorScene';
import './corridor-replay.css';

const CorridorScene=lazy(()=>import('./CorridorScene'));
type ReplayRun={run_id:string;assignment_id:string;event_count:number;conditions_hash:string};
type LoadState='idle'|'loading'|'ready'|'empty'|'error';
type Progress={loaded:number;total:number|null};

class SceneBoundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true};}render(){return this.state.failed?this.props.fallback:this.props.children;}}

const stamp=(value:string)=>new Date(value).toLocaleString('en-CA',{timeZone:'America/Toronto',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit'})+' ET';
const elapsed=(seconds:number)=>{const value=Math.max(0,Math.floor(seconds)),hours=Math.floor(value/3600),minutes=Math.floor(value%3600/60);return `${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`;};
const short=(value:string)=>value.length>14?`${value.slice(0,8)}…${value.slice(-4)}`:value;

function diagramPath(route:CorridorRoute,position:{lat:number;lng:number}){
 const latitude=route.geometry.coordinates.reduce((sum,point)=>sum+point[1],0)/route.geometry.coordinates.length,longitudeScale=Math.max(.15,Math.cos(latitude*Math.PI/180)),points=route.geometry.coordinates.map(([lng,lat])=>[lng*longitudeScale,lat] as [number,number]),minX=Math.min(...points.map(point=>point[0])),maxX=Math.max(...points.map(point=>point[0])),minY=Math.min(...points.map(point=>point[1])),maxY=Math.max(...points.map(point=>point[1]));
 const spanX=Math.max(maxX-minX,.000001),spanY=Math.max(maxY-minY,.000001),scale=Math.min(920/spanX,330/spanY),offsetX=(1000-spanX*scale)/2,offsetY=(405-spanY*scale)/2;
 const project=([lng,lat]:[number,number])=>[offsetX+(lng*longitudeScale-minX)*scale,405-offsetY-(lat-minY)*scale] as const;
 return{route:route.geometry.coordinates.map(project).map(point=>point.join(',')).join(' '),position:project([position.lng,position.lat])};
}

function CorridorDiagram({recording,index}:{recording:CorridorRecording;index:number}){
 const event=eventAt(recording,index),route=routeAt(recording,index);if(!event||!route)return null;
 const path=diagramPath(route,event.sample.position),stops=route.stop_indices.map(i=>route.geometry.coordinates[i]).filter(Boolean).map(point=>diagramPath(route,{lng:point[0],lat:point[1]}).position);
 return <div className="corridor-diagram" role="img" aria-label={`Recorded route diagram at ${stamp(event.sample.at)}`}>
  <svg viewBox="0 0 1000 405" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><defs><pattern id="corridor-grid" width="50" height="50" patternUnits="userSpaceOnUse"><path d="M 50 0 L 0 0 0 50" fill="none" stroke="#3b403e" strokeWidth="1"/></pattern></defs><rect width="1000" height="405" fill="url(#corridor-grid)"/><polyline points={path.route} fill="none" stroke="#454a48" strokeWidth="18" strokeLinejoin="round"/><polyline points={path.route} fill="none" stroke="#e65c32" strokeWidth="5" strokeLinejoin="round"/>{stops.map((point,i)=><circle key={`${point[0]}-${point[1]}-${i}`} cx={point[0]} cy={point[1]} r="9" fill={i===stops.length-1?'#e65c32':'#f5f3ed'} stroke="#242729" strokeWidth="4"/>)}<g transform={`translate(${path.position[0]} ${path.position[1]})`}><circle r="19" fill="#fff0df"/><rect x="-11" y="-18" width="22" height="36" rx="4" fill="#e65c32"/><path d="M-6 -18 L0 -27 L6 -18" fill="#f5f3ed"/></g></svg>
  <p>Plan diagram · exact source point on its recorded route epoch</p>
 </div>;
}

export function CorridorReplay({run,session,online}:{run:ReplayRun;session:Session;online:boolean}){
 const[open,setOpen]=useState(false),[recording,setRecording]=useState<CorridorRecording|null>(null),[loadState,setLoadState]=useState<LoadState>('idle'),[progress,setProgress]=useState<Progress>({loaded:0,total:null}),[error,setError]=useState(''),[reload,setReload]=useState(0),[cursor,setCursor]=useState(0),[playing,setPlaying]=useState(false),[pace,setPace]=useState(60),[camera,setCamera]=useState<CorridorCamera>('overview'),[diagram,setDiagram]=useState(false),[reduced,setReduced]=useState(false),[savedAt,setSavedAt]=useState<string|null>(null);
 const sourceRevision=`${run.event_count}:${run.conditions_hash}`;
 const cursorRef=useRef(cursor);cursorRef.current=cursor;
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)'),update=()=>setReduced(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 useEffect(()=>{if(reduced)setPlaying(false);},[reduced]);
 useEffect(()=>{if(!open)setPlaying(false);},[open]);
 useEffect(()=>{setRecording(null);setCursor(0);setPlaying(false);setLoadState('idle');setProgress({loaded:0,total:null});setError('');},[run.run_id,sourceRevision]);
 useEffect(()=>{
  if(!open||!online)return;
  let active=true;setLoadState('loading');setError('');setProgress({loaded:0,total:null});setPlaying(false);
  void(async()=>{let merged:CorridorRecording|null=null,offset=0,snapshot:string|undefined;
   try{for(;;){const params=new URLSearchParams({offset:String(offset),limit:'1000'});if(snapshot)params.set('snapshot',snapshot);const page=await request<CorridorPage>(session,`simulator/${run.run_id}/presentation?${params}`);if(!active)return;merged=mergeCorridorPage(merged,page);snapshot=merged.snapshot;setProgress({loaded:merged.events.length,total:merged.total});if(page.next_offset===null)break;offset=page.next_offset;}
    if(!active||!merged)return;setRecording(merged);setCursor(0);setSavedAt(new Date().toISOString());setLoadState(merged.events.length?'ready':'empty');
   }catch(reason){if(!active)return;setRecording(null);setProgress({loaded:0,total:null});setLoadState('error');setError(reason instanceof ApiError&&reason.status===409?'Recording changed while loading. Partial pages were discarded.':reason instanceof Error?reason.message:'Recording unavailable.');}
  })();return()=>{active=false;};
 },[open,online,reload,run.run_id,sourceRevision,session.carrier,session.token,session.uid]);
 const milestones=useMemo(()=>recording?corridorMilestones(recording):[],[recording]),selected=recording?eventAt(recording,cursor):null,route=recording?routeAt(recording,cursor):null;
 useEffect(()=>{if(!playing||reduced||!recording?.events.length)return;const startIndex=cursorRef.current===recording.events.length-1?0:cursorRef.current,startElapsed=recording.events[startIndex].elapsed_seconds,start=performance.now();if(startIndex!==cursorRef.current)setCursor(startIndex);let frame=0;
  const tick=(now:number)=>{const target=startElapsed+(now-start)/1000*pace,events=recording.events;let low=startIndex,high=events.length-1;while(low<high){const middle=Math.ceil((low+high)/2);if(events[middle].elapsed_seconds<=target)low=middle;else high=middle-1;}if(cursorRef.current!==low)setCursor(low);if(low>=events.length-1){setPlaying(false);return;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);
 },[playing,pace,recording,reduced]);
 const choose=useCallback((index:number)=>{setPlaying(false);setCursor(Math.max(0,Math.min((recording?.events.length??1)-1,Math.round(index))));},[recording]);
 function timelineKey(event:KeyboardEvent<HTMLInputElement>){if(!recording)return;if(event.key===' '){event.preventDefault();if(!reduced)setPlaying(value=>!value);}else if(event.key==='Home'){event.preventDefault();choose(0);}else if(event.key==='End'){event.preventDefault();choose(recording.events.length-1);}else if(event.key==='ArrowLeft'||event.key==='ArrowDown'){event.preventDefault();choose(cursor-1);}else if(event.key==='ArrowRight'||event.key==='ArrowUp'){event.preventDefault();choose(cursor+1);}}
 const fallback=recording?<CorridorDiagram recording={recording} index={cursor}/>:null,percentage=progress.total?Math.round(progress.loaded/progress.total*100):0;
 return <section className="corridor-replay" aria-label="Recorded corridor replay"><div className={`corridor-heading ${open?'is-open':''}`}><div className="corridor-heading-copy"><p className="eyebrow">RECORDED CORRIDOR / 02</p><h3>Read the wait. Then watch the road answer.</h3><p>{run.assignment_id} · acknowledged synthetic history</p></div><button className="primary" onClick={()=>setOpen(value=>!value)}>{open?'Close replay':'Open 3D corridor replay'}</button></div>{open&&<>
  {loadState==='loading'&&<div className="corridor-load" role="status"><span>Assembling one frozen recording</span><strong>{progress.total?`${progress.loaded.toLocaleString('en-CA')} / ${progress.total.toLocaleString('en-CA')}`:'Requesting first page'}</strong><div><i style={{width:`${percentage}%`}}/></div><small>Only acknowledged source events are loaded. The simulator clock is untouched.</small></div>}
  {!online&&!recording&&<div className="corridor-state" role="status"><strong>Recording unavailable offline</strong><p>Connect before the first load. A completed recording remains available if the connection drops later.</p></div>}
  {loadState==='error'&&<div className="corridor-state is-error" role="alert"><strong>Recording not assembled</strong><p>{error}</p><button disabled={!online} onClick={()=>setReload(value=>value+1)}>Reload from first page</button></div>}
  {loadState==='empty'&&<div className="corridor-state"><strong>No acknowledged observations</strong><p>This run has no historical positions to display. Pending generated samples are excluded.</p><button disabled={!online} onClick={()=>setReload(value=>value+1)}>Check again</button></div>}
  {recording&&selected&&route&&<><div className="corridor-toolbar"><div role="group" aria-label="Corridor view"><button aria-pressed={!diagram&&camera==='overview'} onClick={()=>{setDiagram(false);setCamera('overview');}}>Perspective</button><button aria-pressed={!diagram&&camera==='plan'} onClick={()=>{setDiagram(false);setCamera('plan');}}>Plan</button><button aria-label={diagram?'Show 3D':'Use diagram'} aria-pressed={diagram} onClick={()=>setDiagram(value=>!value)}>Diagram</button></div></div>
   {!online&&<p className="corridor-saved" role="status">Offline · saved recording from {savedAt?stamp(savedAt):'this session'}. Historical values are frozen.</p>}
   <div className={`corridor-stage ${diagram?'is-diagram':''}`}><div className="corridor-stage-readout"><span>SOUTHERN ONTARIO / RECORDED ROUTE</span><strong>{selected.sample.phase.replaceAll('_',' ')}</strong><small>{stamp(selected.sample.at)} · exact observation</small><em>Epoch {String(route.ordinal+1).padStart(2,'0')} · {route.source}</em></div>{diagram?fallback:<SceneBoundary fallback={fallback}><Suspense fallback={<div className="corridor-scene-loading" role="status">Loading corridor renderer…</div>}><CorridorScene route={route} event={selected} camera={camera} reducedMotion={reduced} playing={playing} onUnavailable={()=>setDiagram(true)}/></Suspense></SceneBoundary>}<p className="corridor-stage-note">Source geometry · selected marker snaps to an acknowledged event</p></div>
   <div className="corridor-instrument"><div className="corridor-primary-readout"><span>VIEW TIME</span><strong>{elapsed(selected.elapsed_seconds)}</strong><small>Historical cursor only</small></div><div><span>Speed</span><strong>{selected.sample.speedKph===null?'—':selected.sample.speedKph.toFixed(1)}</strong><small>km/h · preceding interval</small></div><div><span>Odometer</span><strong>{selected.sample.odometerKm===null?'—':selected.sample.odometerKm.toFixed(3)}</strong><small>km · source reading</small></div><div><span>Duty</span><strong>{selected.sample.duty.replaceAll('_',' ')}</strong><small>at observation instant</small></div></div>
   <div className="corridor-transport"><div className="corridor-control-grid"><div className="corridor-playback" role="group" aria-label="Historical playback"><button aria-label={playing?'Pause view playback':'Play view playback'} disabled={reduced} aria-pressed={playing} onClick={()=>setPlaying(value=>!value)}>{playing?'Pause':'Play'}</button><button onClick={()=>choose(0)}>Restart</button></div><label className="corridor-pace">View pace<select value={pace} disabled={reduced} onChange={event=>setPace(Number(event.target.value))}><option value={30}>30×</option><option value={60}>60×</option><option value={120}>120×</option></select></label><label className="corridor-scrub"><span><b>Observation {(cursor+1).toLocaleString('en-CA')}</b><small>{recording.events.length.toLocaleString('en-CA')} acknowledged events</small></span><input aria-label="Recorded observation timeline" type="range" min="0" max={recording.events.length-1} step="1" value={cursor} onChange={event=>choose(Number(event.target.value))} onKeyDown={timelineKey}/></label><div className="corridor-milestones" aria-label="Recorded milestones">{milestones.map(milestone=><button key={milestone.id} aria-pressed={cursor===milestone.index} onClick={()=>choose(milestone.index)}><span>{milestone.label}</span><small>{elapsed(recording.events[milestone.index].elapsed_seconds)}</small></button>)}</div>{reduced&&<p className="corridor-motion-note">Reduced motion is on. Use the slider, arrow keys, Home and End to move between exact events.</p>}</div></div>
   <details className="corridor-source"><summary>Exact source event</summary><div className="corridor-source-summary"><p><span>Observation</span><code title={selected.sample.id} aria-label={`Observation ${selected.sample.id}`}>{short(selected.sample.id)}</code></p><p><span>Route epoch</span><code title={selected.route_key} aria-label={`Route epoch ${selected.route_key}`}>{short(selected.route_key)}</code></p><p><span>Recording snapshot</span><code title={recording.snapshot} aria-label={`Recording snapshot ${recording.snapshot}`}>{short(recording.snapshot)}</code></p><p><span>Assignment / run</span><code title={`Assignment ${recording.assignment_id}; run ${recording.run_id}`} aria-label={`Assignment ${recording.assignment_id}; run ${recording.run_id}`}>{short(recording.assignment_id)}<br/>{short(recording.run_id)}</code></p></div><p className="corridor-source-note">{recording.evidence}. {recording.speed_semantics}. {recording.clock_semantics}.</p><details className="corridor-source-full"><summary>Full source identifiers</summary><code>Observation {selected.sample.id}<br/>Route epoch {selected.route_key}<br/>Recording snapshot {recording.snapshot}<br/>Assignment {recording.assignment_id}<br/>Run {recording.run_id}</code></details></details>
   <div className="corridor-foot"><span>{recording.events.length.toLocaleString('en-CA')} / {recording.total.toLocaleString('en-CA')} source events</span><span>Route {short(route.key)} · epoch {route.ordinal+1} of {recording.routes.length}</span><span>View controls issue no operational commands</span></div></>}
 </>}</section>;
}
