import {Component,lazy,Suspense,useEffect,useState,type ReactNode} from 'react';
import {useQuery} from '@tanstack/react-query';
import {request,type State,type Session} from './api';
import {dockPresentation,type DockRun} from './dock-rehearsal-model';
import './dock-rehearsal.css';
const DockScene=lazy(()=>import('./DockScene'));
const stamp=(v?:string|null)=>v?new Date(v).toLocaleString('en-CA',{timeZone:'America/Toronto',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit'})+' ET':'Awaiting evidence';
class SceneBoundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true};}render(){return this.state.failed?this.props.fallback:this.props.children;}}
export function DockRehearsal({state,run,session,online}:{state:State;run:DockRun;session:Session;online:boolean}){
 const[open,setOpen]=useState(false),[camera,setCamera]=useState<'overview'|'dock'|'top'>('overview'),[selected,setSelected]=useState<'truck'|'dock'|'fence'>('truck'),[flat,setFlat]=useState(false),[reduced,setReduced]=useState(false);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)'),update=()=>setReduced(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 const current=useQuery({queryKey:['dock-current',session.carrier,session.uid],queryFn:()=>request<State>(session,'state'),enabled:open&&online,refetchInterval:open&&online?2000:false,retry:false});
 const data=current.data??state,p=dockPresentation(data,run,session.carrier),saved=current.dataUpdatedAt?new Date(current.dataUpdatedAt).toISOString():null,fresh=online&&!current.isError&&!!current.data;
 const fallback=<div className="dock-flat" role="img" aria-label="Illustrative dock diagram"><div className="dock-flat-building">DOCK</div><div className="dock-flat-route"/>{p?.atDock&&<div className="dock-flat-truck">{p.trip.truckId}</div>}<p>Diagram view · source evidence remains below</p></div>;
 if(!p)return <p className="notice">Dock rehearsal requires a synthetic assignment in this dispatcher workspace.</p>;
 const money=p.amountCents===null?'Held for review':new Intl.NumberFormat('en-CA',{style:'currency',currency:p.estimate!.currency!}).format(p.amountCents/100);
 return <section className="dock-rehearsal" aria-label="Dock recovery rehearsal"><div className={`dock-rehearsal-heading ${open?'is-open':''}`}><div><p className="eyebrow">RECOVERY REHEARSAL / 01</p><h3>A dock wait changes the next move.</h3><p>{p.load.id} · {p.facility?.name?.replace(' · synthetic location','')??'Selected trip'} · synthetic scenario</p></div><button className="primary" aria-label={open?'Close dock rehearsal':'Open 3D dock rehearsal'} onClick={()=>setOpen(v=>!v)}>{open?'Close':'Open 3D dock rehearsal'}</button></div>{open&&<>
 <div className="dock-toolbar"><div role="group" aria-label="Dock camera">{(['overview','dock','top'] as const).map(v=><button key={v} aria-label={v==='overview'?'Overview':v==='dock'?'Dock':'Plan'} aria-pressed={camera===v} onClick={()=>setCamera(v)}>{v==='overview'?'Overview':v==='dock'?'Dock':'Plan'}</button>)}</div><button onClick={()=>{setCamera('overview');setSelected('truck');}}>Home camera</button><button aria-pressed={flat} onClick={()=>setFlat(v=>!v)}>{flat?'Show 3D':'Use diagram'}</button></div>
 <div className="dock-stage"><div className="dock-scene-label"><span>ILLUSTRATIVE FACILITY LAYOUT</span><strong>{p.phase}</strong><small>{stamp(p.sample?.at)} · acknowledged sample</small><span className={`dock-duty-status ${p.headroom.startsWith('Driving held')?'is-held':''}`}>{p.budget&&p.budget.onDutyMinutes<=0?`On-duty limit reached · ${p.budget.onDutyMinutes} min`:p.headroom}{!fresh?' · saved':''}</span></div>{flat?fallback:<SceneBoundary fallback={fallback}><Suspense fallback={<div className="dock-flat" role="status">Loading dock scene…</div>}><DockScene atDock={p.atDock} held={p.held} selected={selected} onSelect={setSelected} camera={camera} reducedMotion={reduced} onUnavailable={()=>setFlat(true)}/></Suspense></SceneBoundary>}<p className="dock-layout-note">Schematic placement · no surveyed bay, queue or boundary claim</p></div>
 <div className="dock-inspector-tabs" role="group" aria-label="Inspect dock evidence">{(['truck','dock','fence'] as const).map(v=><button key={v} aria-pressed={selected===v} onClick={()=>setSelected(v)}>{v==='truck'?'Driver & HOS':v==='dock'?'Dock & detention':'GPS evidence'}</button>)}</div>
 {!fresh&&<p role="status" className="notice">{online?'Current evidence unavailable or refreshing.':'Offline.'} Saved observation only; HOS and amounts are not updating. Downloaded {stamp(saved)}.</p>}
 <div className={`dock-evidence-body inspect-${selected}`}><div className="dock-outcomes"><div><span>On-duty headroom</span><strong>{p.budget?`${p.budget.onDutyMinutes} min`:'Unavailable'}</strong><p>{p.headroom}</p></div><div><span>Driving allowance</span><strong>{p.budget?`${p.budget.drivingMinutes} min`:'Unavailable'}</strong><p>All duty limits apply together.</p></div><div><span>Provisional detention</span><strong>{money}</strong><p>{p.amountCents!==null?`${p.estimate!.dwellMinutes} observed min · ${p.estimate!.billableMinutes} billable min`:'No billable amount inferred from the scene.'}</p></div></div>
 <div className="dock-inspector" aria-live="polite">{selected==='truck'?<><h4>{p.driver?.name??p.trip.driverId} · {p.trip.truckId}</h4><p>Dock waiting consumes on-duty time. Use the assignment review below to select an eligible driver for further work; driver acceptance remains separate.</p><p className="fine">Duty: {p.sample?.duty.replaceAll('_',' ')??'Unavailable'} · {p.sample?.speedKph??'Unknown'} km/h · {p.sample?.odometerKm??'Unknown'} km recorded</p></>:selected==='dock'?<><h4>{p.facility?.name??'Current dock evidence'}</h4><p>{p.reason}</p>{p.estimate?.contract&&<p>{p.estimate.contract.freeMinutes} free minutes · {p.estimate.contract.id} v{p.estimate.contract.version}. An open-visit estimate is not an invoice.</p>}</>:<><h4>Observation confidence</h4><p>{p.reason}</p><p>{p.sample?.accuracyM??'Unknown'} m sample accuracy. The drawn fence is illustrative; database evidence determines visit confidence.</p><p className="fine">Arrival recorded {stamp(p.visit?.arrival)}<br/>Latest observation {stamp(p.estimate?.evidenceAt)}</p><details><summary>Observation IDs</summary><code>Arrival: {p.estimate?.arrivalEvent??'Unavailable'}<br/>Latest: {p.estimate?.evidenceId??'Unavailable'}</code></details></>}</div></div>
 <details className="dock-provenance"><summary>Sources and snapshot times</summary><p>Current HOS/visit evidence at {stamp(p.estimate?.asOf??data.scenarios[0]?.clock)}. Scene observation at {stamp(p.sample?.at)}. This view has no historical scrubber.</p><p>{run.event_count} acknowledged observations · {run.pending_samples} pending. Browser rendering does not advance the simulator or calculate billing.</p><code>Run {run.run_id}<br/>Assignment {run.assignment_id}<br/>Conditions {run.conditions_hash}<br/>Sample {p.sample?.id??'None'}</code></details>
 </>}</section>;
}
