import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {request,type Session,type SendCommand} from './api';
import {RouteGeometry} from './RouteGeometry';
import {Modal} from './ReviewDialog';
import type {Assignment} from '@roadstar/domain';
type Evidence={closures:{id:string}[];receipts:{route_revision_id:string;acknowledged_at:string}[];revisions:{id:string;revision:number;status:string;approved_at:string;body:{closures:{id:string;west:number;east:number;south:number;north:number}[];hasToll?:boolean;route?:unknown;drivingMinutes?:number;dutyMinutes?:number;completionAt?:string}}[]};
const date=(at:string)=>new Date(at).toLocaleString('en-CA',{timeZone:'America/Toronto'})+' ET';
export function DriverRouteReview({trip,session,send,online}:{trip:Assignment;session:Session;send:SendCommand;online:boolean}){
 const [confirm,setConfirm]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const query=useQuery({queryKey:['route-reviews',session.carrier,session.uid,trip.id],queryFn:()=>request<Evidence>(session,`route-reviews?assignmentId=${trip.id}`),enabled:online,refetchInterval:online?2000:false,retry:false});
 const data=query.data,approved=data?.revisions.filter(r=>r.status==='approved').sort((a,b)=>b.approved_at.localeCompare(a.approved_at)||b.id.localeCompare(a.id))[0],receipt=data?.receipts.find(r=>r.route_revision_id===approved?.id);
 const current=!!approved&&data?.closures.length===approved.body.closures.length&&data.closures.every(c=>approved.body.closures.some(a=>a.id===c.id));
 const ready=online&&!busy&&!query.isError&&current&&!receipt;
 if(!data?.closures.length&&!query.isError)return null;
 async function acknowledge(){if(!ready||!approved||confirm!==approved.id)return;setBusy(true);setError('');try{if(await send('acknowledge-route',{routeRevisionId:approved.id,acknowledgeReceipt:true},approved.revision)){await query.refetch();setConfirm(null);}else setError('Receipt was not confirmed. Review the activity queue before retrying.');}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <section className="panel closure-review" aria-label={`Route update for ${trip.loadId}`}><p className="eyebrow">Route update · {trip.loadId}</p><h2>Review the closure response</h2>{query.isError&&<p className="error" role="alert">Route evidence unavailable. Refresh the connection before acknowledging.</p>}{!current&&<p className="notice">Closure evidence needs dispatcher review. An earlier route approval does not cover the current closures.</p>}{approved&&<><p className="fine">Dispatcher approved {date(approved.approved_at)}. Modeled remaining work: {approved.body.drivingMinutes} min driving / {approved.body.dutyMinutes} min on duty.</p>{approved.body.route&&<RouteGeometry route={approved.body.route} closures={approved.body.closures}/>} {approved.body.hasToll&&<p className="notice">This route includes toll segments. Charges are not estimated.</p>}{receipt?<p role="status">Driver receipt recorded {date(receipt.acknowledged_at)}. Receipt does not prove route adoption or execution.</p>:<button className="primary" disabled={!ready} onClick={()=>setConfirm(approved.id)}>Review route receipt</button>}</>}{!online&&<p className="notice">Offline. Evidence may be stale; reconnect to confirm receipt.</p>}{error&&<p role="alert" className="error">{error}</p>}{confirm&&<Modal title="Confirm route receipt?" description={`${trip.loadId} · ${trip.truckId}. Confirm that you received and reviewed this dispatcher-approved route. This does not start navigation or certify safe passage.`} onClose={()=>{if(!busy)setConfirm(null);}}>{(!current||approved?.id!==confirm)&&<p role="alert">Route evidence changed. Close and review the latest dispatcher response.</p>}<button className="primary" disabled={!ready||approved?.id!==confirm} onClick={()=>void acknowledge()}>Confirm route receipt</button></Modal>}</section>;
}
