import {useState} from 'react';
import {request} from './api';
import type {State,Session,SendCommand} from './api';
import type {HosProfile,HosProfileResult} from '@roadstar/domain/hos-profile';
import type {HosReviewInput} from '@roadstar/domain/hos-import';
import {Modal} from './ReviewDialog';
type Preview=HosProfileResult&{expectedVersion:number;profile:HosProfile;sourceSha256:string};
const minutes=(n:number|undefined)=>typeof n==='number'?`${n} min`:'Unknown';
const date=(s:string|undefined)=>s?new Date(s).toLocaleString('en-CA',{timeZone:'America/Toronto',dateStyle:'medium',timeStyle:'short'}):'Unknown';
export function HosReview({state,session,send,online}:{state:State;session:Session;send:SendCommand;online:boolean}){
 const drivers=state.resources.filter(r=>r.kind==='driver'),[selected,setSelected]=useState(''),[sourceCsv,setSourceCsv]=useState(''),[sourceName,setSourceName]=useState(''),[cycle,setCycle]=useState<1|2>(1),[anchor,setAnchor]=useState(''),[reset,setReset]=useState(''),[reason,setReason]=useState(''),[ack,setAck]=useState(false),[incomplete,setIncomplete]=useState(false),[busy,setBusy]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[confirm,setConfirm]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const driver=drivers.find(d=>d.id===selected),evidence=driver?.hosEvidence,dispatcher=state.actor.role==='dispatcher';
 const change=(fn:()=>void)=>{fn();setPreview(null);setConfirm(false);setError('');setNotice('');};
 const input=():HosReviewInput=>({driverId:selected,cycle,dayAnchor:anchor,...(reset?{cycleStartedAt:reset}:{}),sourceName,sourceCsv,reason,acknowledgePlanningLimits:true,acceptIncomplete:incomplete});
 async function inspect(){if(!driver||!online)return;setBusy(true);setError('');try{const body=input();const result=await request<Preview>(session,'hos-preview',{id:crypto.randomUUID(),path:'hos-preview',body,version:driver.version,status:'pending',createdAt:new Date().toISOString()});setPreview(result);setIncomplete(false);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function apply(){if(!preview||!driver||driver.version!==preview.expectedVersion)return;setBusy(true);try{const ok=await send('review-hos',input(),preview.expectedVersion);if(ok){setConfirm(false);setPreview(null);setNotice('Reviewed history saved. The driver version and planning evidence have been updated.');}else setError('Review was not confirmed. Inspect the activity queue, refresh the driver and preview again.');}finally{setBusy(false);}}
 async function download(){if(!driver)return;setBusy(true);setError('');try{const result=await request<{record:{source_text:string|null;source_ref:string}|null}>(session,`hos-history?driverId=${encodeURIComponent(driver.id)}`);if(!result.record?.source_text)throw new Error('No retained CSV source is available for this profile.');const url=URL.createObjectURL(new Blob([result.record.source_text],{type:'text/csv'}));const link=document.createElement('a');link.href=url;link.download=result.record.source_ref;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <section className="panel" aria-label="Hours of service evidence"><div className="panel-heading"><div><p className="eyebrow">Duty history & planning</p><h2>Hours of service evidence</h2></div><span className="tag">Planning aid</span></div>
 <label>Driver history<select aria-label="HOS driver" disabled={busy} value={selected} onChange={e=>change(()=>{setSelected(e.target.value);setSourceCsv('');setSourceName('');setAck(false);})}><option value="">Choose a driver</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.name??d.id} · {d.id}</option>)}</select></label>
 {driver&&<><p>{evidence?.profile==='federal-south-60-solo-ordinary-v1'?'Federal · solo freight south of 60°N':evidence?.profile==='declared-budget-history'?'Declared budget history':'No supported profile'} · {evidence?.status??'Unverified'} · {driver.provenance}</p>{evidence?.reason&&<p className="notice">{evidence.reason}</p>}<p>Remaining driving {minutes(driver.budget?.drivingMinutes)} · On-duty {minutes(driver.budget?.onDutyMinutes)} · Cycle {minutes(driver.budget?.cycleMinutes)}</p>{evidence?.dayStart&&<p>Operator day {date(evidence.dayStart)} → {date(evidence.dayEnd)} ET · Day driving {minutes(evidence.dayDrivingMinutes)} · Day on-duty {minutes(evidence.dayOnDutyMinutes)}</p>}{evidence?.shiftStart&&<p>Shift since {date(evidence.shiftStart)} ET · Shift driving {minutes(evidence.shiftDrivingMinutes)} · Shift on-duty {minutes(evidence.shiftOnDutyMinutes)} · Daily rest still required {minutes(evidence.dailyRestRemainingMinutes)}</p>}{evidence?.revision&&<><p className="fine">Revision {evidence.revision} · Source {evidence.sourceRef} · Reviewed by {evidence.reviewedBy}</p><button disabled={!online||busy} onClick={()=>void download()}>Download reviewed duty CSV</button></>}
 {dispatcher&&<><h3>Review imported duty history</h3><p className="fine">Ordinary federal south-of-60 solo freight only. Select this profile from the carrier’s operating jurisdiction. Upload continuous intervals with columns start,end,duty. Timestamps require a time zone; duty values are off_duty, sleeper, on_duty or driving. The last declared duty continues until a subsequent recorded change.</p>
 <fieldset className="hos-review-form" disabled={busy||!online}><label>Duty history CSV<input key={selected} aria-label="Duty history CSV" type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];change(()=>{setSourceCsv('');setSourceName('');});if(!file)return;if(file.size>700000){setError('Use a duty CSV under 700 KB.');return;}setBusy(true);try{setSourceCsv(await file.text());setSourceName(file.name);}catch{setError('Unable to read the selected file.');}finally{setBusy(false);}}}/></label><label>Cycle<select value={cycle} onChange={e=>change(()=>setCycle(Number(e.target.value) as 1|2))}><option value={1}>Cycle 1 · 70 hours / 7 days</option><option value={2}>Cycle 2 · 120 hours / 14 days, with additional rest condition</option></select></label><label>Operator-day anchor with time zone<input aria-label="Operator-day anchor" placeholder="2026-09-13T00:00:00-04:00" value={anchor} onChange={e=>change(()=>setAnchor(e.target.value))}/></label><label>Declared cycle reset (optional)<input aria-label="Declared cycle reset" placeholder="Leave empty to retain rolling cycle history" value={reset} onChange={e=>change(()=>setReset(e.target.value))}/></label><label>Review reason<textarea aria-label="HOS review reason" value={reason} onChange={e=>change(()=>setReason(e.target.value))}/></label><label className="hos-ack fine"><input type="checkbox" checked={ack} onChange={e=>change(()=>setAck(e.target.checked))}/> I reviewed the source and selected operation profile. This is a planning aid, not certified ELD evidence.</label><button disabled={!sourceCsv||!anchor||reason.length<10||!ack} onClick={()=>void inspect()}>{busy?'Checking history…':'Preview HOS clocks'}</button></fieldset>
 {preview&&<div className="selected-sample"><h3>Review result · {preview.hosEvidence.status}</h3><p>{preview.profile.history.length} sourced intervals · Driver version {preview.expectedVersion}</p>{preview.hosEvidence.reason?<p className="notice">{preview.hosEvidence.reason}</p>:<><p>Driving {minutes(preview.budget?.drivingMinutes)} · On-duty {minutes(preview.budget?.onDutyMinutes)} · Cycle {minutes(preview.budget?.cycleMinutes)}</p><p>Day driving {minutes(preview.hosEvidence.dayDrivingMinutes)} · Shift driving {minutes(preview.hosEvidence.shiftDrivingMinutes)} · Daily rest remaining {minutes(preview.hosEvidence.dailyRestRemainingMinutes)}</p></>}<p className="fine">Stored source SHA-256: <code style={{overflowWrap:'anywhere'}}>{preview.sourceSha256}</code></p><p className="fine">Fixed 24-hour days; no sleeper split, adverse-condition exception or automatic cycle reset. Mandatory rest uses a conservative allocation; ambiguous history needs review. Plans stop at the current day/rest horizon.</p>{driver.version!==preview.expectedVersion&&<p className="notice">Driver evidence changed. Preview again before saving.</p>}<button disabled={!online||busy||driver.version!==preview.expectedVersion} onClick={()=>setConfirm(true)}>Review and save history</button></div>}
 </>}
 </>}
 {!online&&<p className="notice">Offline. Source review requires a connection.</p>}{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 {confirm&&preview&&driver&&<Modal title="Apply reviewed duty history?" description={`Save a new profile revision for ${driver.id}. Existing proposals become stale; prior source revisions remain retained.`} onClose={()=>{if(!busy)setConfirm(false);}}><p>{preview.hosEvidence.status==='incomplete'?'This history cannot establish driving availability. Saving it removes the current usable planning budgets.':'The server will recompute these clocks against current duty evidence before applying the revision.'}</p>{preview.hosEvidence.status==='incomplete'&&<label className="hos-ack"><input type="checkbox" checked={incomplete} onChange={e=>setIncomplete(e.target.checked)}/> I acknowledge that driving availability will remain unverified.</label>}<button disabled={busy||!online||driver.version!==preview.expectedVersion||preview.hosEvidence.status==='incomplete'&&!incomplete} onClick={()=>void apply()}>{busy?'Saving reviewed history…':'Apply reviewed history'}</button></Modal>}
 </section>;
}
