type Area={west:number;east:number;south:number;north:number};
export function RouteGeometry({route,closures}:{route:any;closures:Area[]}){
 const legs=route?.route?.trip?.legs?.map((l:any)=>l.shape?.coordinates) as number[][][]|undefined;
 if(route?.routing_evidence!=='valhalla-truck'||!legs?.length||legs.some(l=>!Array.isArray(l)||l.length<2||l.some(p=>p.length!==2||!p.every(Number.isFinite))))return <p className="notice">Verified route geometry is unavailable.</p>;
 const points=legs.flat(),extent=[...points,...closures.flatMap(c=>[[c.west,c.south],[c.east,c.north]])],latitudes=extent.map(p=>p[1]),longitudes=extent.map(p=>p[0]);
 const minLon=Math.min(...longitudes),maxLon=Math.max(...longitudes),minLat=Math.min(...latitudes),maxLat=Math.max(...latitudes),cos=Math.cos((minLat+maxLat)/2*Math.PI/180),dx=(maxLon-minLon)*cos,dy=maxLat-minLat,scale=Math.min(520/Math.max(dx,.00001),190/Math.max(dy,.00001)),left=40+(520-dx*scale)/2,top=25+(190-dy*scale)/2;
 const xy=(p:number[])=>[left+(p[0]-minLon)*cos*scale,top+(maxLat-p[1])*scale];const start=xy(points[0]),end=xy(points.at(-1)!);
 return <figure className="closure-geometry"><svg viewBox="0 0 600 240" role="img" aria-label="Proposed truck route diagram"><title>Returned Valhalla truck route and closure bounds</title><desc>Orange lines show proposed road geometry. Shaded rectangles mark declared closures. Start is current GPS and the final circle is the remaining destination. This diagram has no basemap and is not navigation guidance.</desc>{closures.map((c,i)=>{const [x,y]=xy([c.west,c.north]),[right,bottom]=xy([c.east,c.south]);return <rect key={i} x={x} y={y} width={Math.max(right-x,2)} height={Math.max(bottom-y,2)} fill="#ac3716" fillOpacity=".18" stroke="#ac3716" strokeWidth="1"/>;})}{legs.map((l,i)=><polyline key={i} points={l.map(p=>xy(p).join(',')).join(' ')} fill="none" stroke="#e65c32" strokeWidth="2.5" strokeLinejoin="round"/>)}<circle cx={start[0]} cy={start[1]} r="5" fill="#191b1d"/><circle cx={end[0]} cy={end[1]} r="5" fill="#f5f3ed" stroke="#191b1d" strokeWidth="2"/></svg><figcaption>Proposed road geometry · filled start: current GPS · outlined end: remaining destination · shaded area: closure. Diagram only; no basemap or navigation guidance.</figcaption></figure>;
}
