import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {request,type State,type Session,type SendCommand} from './api';
import {Modal} from './ReviewDialog';
type Visit={id?:string;stop_id:string;arrival:string;departure:string|null;arrival_event:string;departure_event:string|null;retainedVisitId?:string|null};
type Review={assignmentId:string;expectedVersion:number;fingerprint:string;reviewRequired:boolean;changed:boolean;sampleCount:number;issues:string[];current:Visit[];proposed:Visit[];historicalVisits:Visit[];invoices:{id:string;visit_id:string;status:string;revision:number;body:{amountCents:number;currency:string}}[];history:{id:string;recorded_at:string;reviewed_by:string;reason:string}[]};
const at=(value:string|null)=>value?new Date(value).toLocaleString('en-CA',{timeZone:'America/Toronto',dateStyle:'medium',timeStyle:'short'})+' ET':'Open';
function Visits({items}:{items:Visit[]}){return items.length?<ul>{items.map((v,i)=><li key={v.id??i}><strong>{v.stop_id}</strong><p>{at(v.arrival)} → {at(v.departure)}</p><p className="fine">Samples: {v.arrival_event} → {v.departure_event??'awaiting departure'}{v.retainedVisitId?' · unchanged visit retained':''}</p></li>)}</ul>:<p>No visits established.</p>;}
export function VisitReconciliation({state,session,send,online}:{state:State;session:Session;send:SendCommand;online:boolean}){
 const [open,setOpen]=useState(false),[selected,setSelected]=useState(''),[confirm,setConfirm]=useState<Review|null>(null),[reason,setReason]=useState(''),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const trip=state.assignments.find(a=>a.id===selected),pending=state.assignments.filter(a=>a.visitReviewRequired);
 const query=useQuery({queryKey:['visit-review',session.carrier,session.uid,selected],queryFn:()=>request<Review>(session,`visit-review?assignmentId=${encodeURIComponent(selected)}`),enabled:open&&!!trip&&online,refetchInterval:online?2000:false,retry:false});
 const data=query.data,ready=online&&!busy&&!query.isError&&!!data&&!!trip,stale=!!confirm&&(data?.fingerprint!==confirm.fingerprint||trip?.version!==confirm.expectedVersion);
 async function apply(){if(!confirm||!ready||stale)return;setBusy(true);setMessage('');try{if(await send('reconcile-visits',{assignmentId:confirm.assignmentId,fingerprint:confirm.fingerprint,reason:reason.trim(),acknowledgeRevisedEvidence:true},confirm.expectedVersion)){setConfirm(null);setAck(false);await query.refetch();setMessage('Visit evidence reconciled. Revised drafts require separate billing approval. Prior invoices remain in history.');}else setMessage('Reconciliation was not confirmed. Inspect the action queue and refresh the evidence.');}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 return <details className="panel" onToggle={e=>setOpen(e.currentTarget.open)}><summary>Late GPS & visit reconciliation{pending.length?` · ${pending.length} awaiting review`:''}</summary><p className="fine">Late samples can change observed visit timing. Review the ordered source history before billing approval. Replaced visits and invoices remain in the audit history; this action does not initiate payment.</p><label>Visit review trip<select aria-label="Visit review trip" value={selected} onChange={e=>{setSelected(e.target.value);setConfirm(null);setMessage('');}}><option value="">Choose a trip</option>{state.assignments.map(a=><option key={a.id} value={a.id}>{a.loadId} · {a.driverId}{a.visitReviewRequired?' · late evidence needs review':''}</option>)}</select></label>
 {query.isLoading&&<p role="status">Reconstructing observed visits…</p>}{query.isError&&<p role="alert">{query.error.message} <button onClick={()=>void query.refetch()} disabled={!online}>Retry visit review</button></p>}{!online&&<p className="notice">Offline. Reconnect to review and approve current evidence.</p>}
 {data&&trip&&<><p>{data.sampleCount} source observations · {data.reviewRequired?'Billing approval held for late evidence review':'No late evidence hold'}</p><h3>Current visits</h3><Visits items={data.current}/><h3>Reconstructed visits</h3><Visits items={data.proposed}/>{data.issues.map(issue=><p role="alert" key={issue}>{issue}</p>)}{(data.reviewRequired||data.changed)&&<button disabled={!ready||!!data.issues.length} onClick={()=>{setConfirm(data);setReason('');setAck(false);}}>Review visit reconciliation</button>}
 <details><summary>Prior visits & invoice audit</summary><Visits items={data.historicalVisits}/>{data.invoices.map(i=><p key={i.id}>{i.status} revision {i.revision} · {new Intl.NumberFormat('en-CA',{style:'currency',currency:i.body.currency}).format(i.body.amountCents/100)} · {data.historicalVisits.some(v=>v.id===i.visit_id)?'historical visit; excluded from current billing':'current visit'}<br/><code>{i.id}</code></p>)}{data.history.map(h=><p key={h.id}>Reconciled by {h.reviewed_by} · {at(h.recorded_at)}<br/>{h.reason}</p>)}</details></>}
 {message&&<p role="status">{message}</p>}{confirm&&<Modal title="Reconcile these observed visits?" description="Review the before and after evidence. Original observations and approved invoices are retained." onClose={()=>{if(!busy)setConfirm(null);}}><h3>Before</h3><Visits items={confirm.current}/><h3>After</h3><Visits items={confirm.proposed}/><p className="notice">These are GPS sample times, not exact physical dock crossings. Changed visits receive revised drafts requiring separate approval. Prior approved amounts are history, not additional charges or payments.</p><label>Reconciliation reason<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={20} maxLength={2000}/></label><label className="checkbox-label"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed the source samples, revised visits and prior invoice history.</label>{stale&&<p role="alert">Evidence changed. Close and review the current reconstruction.</p>}<button className="primary" disabled={!ready||stale||!ack||reason.trim().length<20} onClick={()=>void apply()}>{busy?'Recording reconciliation…':'Approve visit reconciliation'}</button></Modal>}</details>;
}
