import {randomUUID} from 'node:crypto';
import {writeFile,mkdir} from 'node:fs/promises';
import {pool} from '../services/api/src/db.ts';
import {Store} from '../services/api/src/store.ts';
import {Files} from '../services/api/src/files.ts';
import {milton} from '../services/api/src/fixtures.ts';
const db=pool('postgresql://roadstar:local-roadstar-only@127.0.0.1:55432/roadstar'),store=new Store(db),carrier='dock-document-'+randomUUID(),cmd=(expectedVersion=1)=>({key:randomUUID(),expectedVersion});
function ticket(){const lines=['ROADSTAR - SYNTHETIC DOCK TICKET','Demonstration only - not a real shipment document','Load RS-1042 / Milton yard / Demo Driver 1','Date: September 13, 2026','Dock check-in: 12:40:00 UTC (08:40 ET)','Dock release: 15:10:00 UTC (11:10 ET)','Source: synthetic facility desk attestation','GPS facility arrival/departure can differ from dock service times.'];const stream='BT /F1 14 Tf 55 750 Td '+lines.map((s,i)=>(i?'0 -28 Td ':'')+'('+s.replaceAll('(','\\(').replaceAll(')','\\)')+') Tj').join('\n')+' ET';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`];let pdf='%PDF-1.4\n',offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;}const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return Buffer.from(pdf);}
try{await store.seed(carrier);const dispatcher=await store.membership('demo-dispatcher',carrier),driver=await store.membership('demo-driver-1',carrier),simulator=await store.membership('demo-simulator',carrier),trip:any=await store.dispatch(dispatcher,cmd(),{loadId:'RS-1042',driverId:'D-01',truckId:'T-101',trailerId:'V-101'});await store.respond(driver,cmd(),{assignmentId:trip.id,action:'accept'});for(const [id,at,position] of [['arrival','2026-09-13T12:30:00Z',milton],['departure','2026-09-13T15:15:00Z',{...milton,lat:milton.lat+.01}]] as const)await store.ingest(simulator,cmd(),{id,assignmentId:trip.id,at,position,accuracyM:5,odometerKm:1000,speedKph:0,duty:'on_duty',provenance:'synthetic'});const before=await store.snapshot(dispatcher),visit=before.visits[0],draft=before.invoices[0];const approved:any=await store.approveInvoice(dispatcher,cmd(draft.revision),{invoiceId:draft.id,acknowledgeObservedSamples:true,evidenceNote:'Synthetic baseline review of the original GPS samples and bound shipment terms.'});const doc:any=await store.document(dispatcher,cmd(before.loads.find(l=>l.id==='RS-1042')!.version),{loadId:'RS-1042',mediaType:'application/pdf',kind:'other',filename:'synthetic-milton-dock-ticket.pdf'}),bytes=ticket();await store.uploadDocument(dispatcher,cmd(1),doc.id,bytes,'application/pdf',new Files());await mkdir('docs/evidence/visit-time-review-2026-09-11',{recursive:true});await writeFile('docs/evidence/visit-time-review-2026-09-11/synthetic-dock-ticket.pdf',bytes);await writeFile('/tmp/roadstar-visit-time-fixture.json',JSON.stringify({carrier,assignmentId:trip.id,visitId:visit.id,documentId:doc.id,baselineApprovedId:approved.id,baselineAmountCents:approved.amountCents,raw:(await db.query('SELECT * FROM telemetry WHERE carrier_id=$1 ORDER BY id',[carrier])).rows,visits:before.visits,resources:before.resources},null,2));console.log('Prepared '+carrier+' with actual stored PDF and approved $75 baseline');}finally{await db.end();}
