import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {pool} from '../services/api/src/db.ts';
import {Store} from '../services/api/src/store.ts';
import {randomUUID} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
// A new isolated synthetic carrier for every preparation; no operational seed reset.
assert.ok(process.env.TEST_DATABASE_URL,'Set TEST_DATABASE_URL explicitly to the local RoadStar test database.');
assert.ok(['localhost','127.0.0.1','[::1]'].includes(new URL(process.env.TEST_DATABASE_URL).hostname),'Fixture preparation is restricted to local PostgreSQL.');
const carrier='axle-ui-'+randomUUID(),dir='docs/evidence/axle-review-web-2026-09-11';
await mkdir(dir,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome'});
try{const page=await browser.newPage();await page.setContent(`<html><head><style>@page{size:A4;margin:22mm}body{font:13px Arial;color:#272c2b;line-height:1.5}h1{font-size:26px}h2{font-size:17px;margin-top:24px}.badge{color:#af4215;font-weight:bold}table{border-collapse:collapse;width:100%}td,th{padding:8px;border-bottom:1px solid #ddd;text-align:left}.note{background:#f5f1e8;padding:12px}footer{margin-top:28px;font-size:11px}</style></head><body><p class="badge">ROADSTAR / SYNTHETIC DEMONSTRATION</p><h1>Axle configuration &amp; loading sheet</h1><p>Shipment <b>RS-1042</b> | Tractor <b>T-101</b> | Semitrailer <b>V-101</b><br>Fixture revision 1 - prepared September 11, 2026</p><p class="note">Illustrative inputs only. This is not a scale ticket, manufacturer rating, legal clearance or evidence from a real carrier.</p><h2>Empty coupled combination and configured limits</h2><table><tr><th>Group</th><th>Empty mass</th><th>Configured limit</th><th>Axles</th></tr><tr><td>Steer</td><td>5,000 kg</td><td>6,500 kg</td><td>1</td></tr><tr><td>Drive</td><td>5,000 kg</td><td>18,000 kg</td><td>2, equalized</td></tr><tr><td>Trailer</td><td>4,000 kg</td><td>14,000 kg</td><td>2, equalized</td></tr></table><p>Configured gross limit: <b>40,000 kg</b>. Empty masses include the coupled tractor and trailer and must be added only once.</p><h2>Geometry and cargo</h2><table><tr><td>Tractor steer-to-drive-group wheelbase</td><td>4.0 m</td></tr><tr><td>Fifth wheel from steer group</td><td>3.8 m</td></tr><tr><td>Kingpin-to-trailer-group span</td><td>10.0 m</td></tr><tr><td>Stored shipment cargo</td><td>32,000 lb</td></tr><tr><td>Placement A: cargo centre from kingpin</td><td>8.0 m</td></tr><tr><td>Placement B: same cargo moved toward kingpin</td><td>5.0 m</td></tr></table><h2>Review exercise</h2><p>Calculate both placements without changing payload or group limits. Retain the failed placement, then record a separate assessment for the modeled repositioning. Physical repositioning is not demonstrated by this fixture. Dispatch approval remains a separate action.</p><footer>Supported static model: one tractor and semitrailer, equalized axle groups, cargo within the kingpin-to-trailer-group span. No dynamic, tire, side-to-side or individual-axle measurement claims.</footer></body></html>`);await page.pdf({path:dir+'/synthetic-loading-sheet.pdf',format:'A4',printBackground:true});}finally{await browser.close();}
const db=pool(process.env.TEST_DATABASE_URL);try{await new Store(db).seed(carrier);}finally{await db.end();}
await writeFile('/tmp/roadstar-axle-ui-fixture.json',JSON.stringify({carrier,dir,pdf:dir+'/synthetic-loading-sheet.pdf'},null,2));console.log(JSON.stringify({carrier,dir}));
