import {randomUUID} from 'node:crypto';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
import {pool} from '../services/api/src/db.ts';import {Store} from '../services/api/src/store.ts';import {milton} from '../services/api/src/fixtures.ts';
const db=pool('postgresql://roadstar:local-roadstar-only@127.0.0.1:55432/roadstar'),store=new Store(db),carrier='route-review-'+randomUUID(),checks:any[]=[];
async function call(path:string,body?:unknown,version=1,role='demo-dispatcher',key=randomUUID(),expected=200){const r=await fetch('http://127.0.0.1:4010/api/'+path,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer '+role,'x-carrier-id':carrier,'idempotency-key':key,'if-match':String(version),'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const result=await r.json();assert.equal(r.status,expected,JSON.stringify(result));checks.push({path,status:r.status,role});return result as any;}
try{
await store.seed(carrier);const trip=await call('dispatch',{loadId:'RS-1042',driverId:'D-01',truckId:'T-101',trailerId:'V-101'});await call('respond',{assignmentId:trip.id,action:'accept'},1,'demo-driver-1');await call('simulation-clock',{at:trip.startAt},1,'demo-simulator');
await call('telemetry',{id:randomUUID(),assignmentId:trip.id,at:trip.startAt,position:milton,accuracyM:5,speedKph:0,odometerKm:100,duty:'on_duty',provenance:'synthetic'},1,'demo-simulator');await call('complete-stop',{assignmentId:trip.id,stopId:milton.id,occurredAt:trip.startAt},2,'demo-driver-1');
const originalTelemetry=(await db.query('SELECT * FROM telemetry WHERE carrier_id=$1 ORDER BY id',[carrier])).rows,originalReservations=(await db.query('SELECT * FROM reservations WHERE carrier_id=$1 ORDER BY id',[carrier])).rows;
const report=await call('report-closure',{assignmentId:trip.id,area:{west:-80.5314,east:-80.5294,south:43.273031,north:43.275031},observedAt:trip.startAt,sourceRef:'synthetic highway closure fixture',reason:'Synthetic road closure ahead; review the truck-feasible alternate'},3,'demo-simulator');
const review=await call('rehearse-route',{assignmentId:trip.id},4);assert.equal(review.status,'pending');assert.equal(review.body.hasToll,true);
await call('approve-route',{routeRevisionId:review.id,acknowledgeModeledRoute:true},1,'demo-driver-1',randomUUID(),403);
const key=randomUUID(),approved=await call('approve-route',{routeRevisionId:review.id,acknowledgeModeledRoute:true},1,'demo-dispatcher',key);assert.deepEqual(await call('approve-route',{routeRevisionId:review.id,acknowledgeModeledRoute:true},1,'demo-dispatcher',key),approved);
const own=await call('route-reviews?assignmentId='+trip.id,undefined,1,'demo-driver-1');assert.equal(own.revisions[0].status,'approved');assert.equal(own.revisions[0].revision,2);await call('route-reviews?assignmentId='+trip.id,undefined,1,'demo-driver-2',randomUUID(),403);
assert.deepEqual((await db.query('SELECT * FROM telemetry WHERE carrier_id=$1 ORDER BY id',[carrier])).rows,originalTelemetry);assert.deepEqual((await db.query('SELECT * FROM reservations WHERE carrier_id=$1 ORDER BY id',[carrier])).rows,originalReservations);
const receipt={verifiedAt:new Date().toISOString(),carrier,assignmentId:trip.id,closure:report,routeRevisionId:review.id,routeFingerprint:review.body.routeFingerprint,completionAt:review.body.completionAt,drivingMinutes:review.body.drivingMinutes,dutyMinutes:review.body.dutyMinutes,hasToll:review.body.hasToll,reviewedOrigin:review.body.origin,originalTelemetryPreserved:true,reservationsUnchanged:true,repeatApprovalIdentical:true,approvedRevision:own.revisions[0].revision,checks,scope:'Actual local HTTP API and PostgreSQL with Ontario Valhalla. Synthetic closure only; route UI, driver acknowledgement and simulator adoption are separate outstanding steps.'};
await writeFile('docs/evidence/route-review-api-2026-09-11.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt,null,2));
}finally{await db.end()}
