import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {pool} from '../services/api/src/db.ts';
import {Store} from '../services/api/src/store.ts';
import {london} from '../services/api/src/fixtures.ts';
const phase=process.argv[2],pointer='data/complete-replay-fixture.json',dir='docs/evidence/complete-replay-2026-09-12';
const db=pool('postgresql://roadstar:local-roadstar-only@127.0.0.1:55432/roadstar');
let f:any=phase==='prepare'?{carrier:'complete-replay-'+randomUUID(),createdAt:new Date().toISOString()}:JSON.parse(await readFile(pointer,'utf8'));
async function save(){await writeFile(pointer,JSON.stringify(f,null,2)+'\n');}
async function api(path:string,body?:unknown,version=1,role='demo-dispatcher',expected=200,key=randomUUID()){
 const r=await fetch('http://127.0.0.1:4010/api/'+path,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json',authorization:'Bearer '+role,'x-carrier-id':f.carrier,'idempotency-key':key,'if-match':String(version)},body:body===undefined?undefined:JSON.stringify(body)});
 const value=await r.json();assert.equal(r.status,expected,JSON.stringify({path,value}));return value as any;
}
async function sim(action:string,body?:unknown){const r=await fetch('http://127.0.0.1:4020'+action,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(600000)});const out=await r.json();assert.ok(r.ok,JSON.stringify(out));return out as any;}
async function durable(){const out:any={};for(const table of ['telemetry','stop_visits','invoice_revisions','assignments','reservations','disruptions','approvals','resources','loads','scenarios','duty_events','stop_completions'])out[table]=(await db.query(`SELECT * FROM ${table} WHERE carrier_id=$1 ORDER BY id`,[f.carrier])).rows;return JSON.parse(JSON.stringify(out));}
try{
 await mkdir(dir,{recursive:true});
 if(phase==='prepare'){
  try{await readFile(pointer);throw Error('Existing rehearsal pointer retained; archive explicitly before preparing another.');}catch(e:any){if(e.code!=='ENOENT')throw e;}
  await new Store(db).seed(f.carrier);await save();
  const pickup={id:'london-local-yard',name:'London local yard · synthetic location',lat:42.99,lng:-81.20,radiusM:100};
  // The scenario is authored before dispatch; production commands never bypass review.
  const rows=(await db.query('SELECT id,body FROM loads WHERE carrier_id=$1 AND id=ANY($2::text[])',[f.carrier,['RS-1042','RS-1043']])).rows;
  for(const row of rows){const load=row.id==='RS-1042'?{...row.body,pickup,drivingMinutes:10,serviceMinutes:10,endAt:'2026-09-13T13:00:00Z'}:{...row.body,startAt:'2026-09-13T13:15:00Z',endAt:'2026-09-13T16:00:00Z'};await db.query('UPDATE loads SET body=$3 WHERE carrier_id=$1 AND id=$2',[f.carrier,row.id,JSON.stringify(load)]);await db.query('DELETE FROM stops WHERE carrier_id=$1 AND load_id=$2',[f.carrier,row.id]);for(const [i,s]of[load.pickup,load.delivery].entries())await db.query('INSERT INTO stops VALUES($1,$2,$3,$4,ST_SetSRID(ST_MakePoint($5,$6),4326)::geography,$7,$8)',[f.carrier,row.id,s.id,i,s.lng,s.lat,s.radiusM,JSON.stringify(s)]);}
  for(const id of ['D-01','D-02']){const row=(await db.query('SELECT body FROM resources WHERE carrier_id=$1 AND id=$2',[f.carrier,id])).rows[0];const body={...row.body,position:id==='D-01'?pickup:london,budget:{...row.body.budget,...(id==='D-01'?{onDutyMinutes:240}:{})}};await db.query('UPDATE resources SET body=$3 WHERE carrier_id=$1 AND id=$2',[f.carrier,id,JSON.stringify(body)]);await db.query('UPDATE hos_bases SET budget=$3 WHERE carrier_id=$1 AND driver_id=$2',[f.carrier,id,JSON.stringify(body.budget)]);}
  f.initialState=await api('state');f.trip=await api('dispatch',{loadId:'RS-1042',driverId:'D-01',truckId:'T-101',trailerId:'V-101'});await api('respond',{assignmentId:f.trip.id,action:'accept'},1,'demo-driver-1');f.next=await api('dispatch',{loadId:'RS-1043',driverId:'D-01',truckId:'T-101',trailerId:'V-101'});
  f.request={assignment_id:f.trip.id,carrier_id:f.carrier,start_time:f.trip.startAt,dock_wait_seconds:9900,route:{locations:[pickup,london].map(p=>({lat:p.lat,lon:p.lng})),truck:{height:4.1,width:2.6,length:23,weight:40,axle_load:9,hazmat:false,evidence:'synthetic-scenario'}}};f.run=await sim('/runs',f.request);await save();
  await sim(`/runs/${f.run.id}/resume`,{});await sim(`/runs/${f.run.id}/advance`,{seconds:1});await sim(`/runs/${f.run.id}/pause`,{});const s=await api('state');f.delay=(await sim(`/runs/${f.run.id}`)).delay_reports;assert.equal(f.delay.length,1);assert.ok(f.delay[0].result.impactedLoads.some((x:any)=>x.id===f.next.id));assert.equal(s.assignments.find((a:any)=>a.id===f.next.id).status,'offered');assert.equal(s.proposals.length,0);
  f.ready=true;await save();console.log(JSON.stringify({phase,carrier:f.carrier,run:f.run.id,impactedLoad:'RS-1043'}));
 }else if(phase==='recover'){
  assert.ok(f.ready&&!f.proposal&&!f.approval,'Recovery phase requires prepared, unrehearsed fixture');const s=await api('state');f.proposal=await api('propose',{loadId:'RS-1043',driverId:'D-02',truckId:'T-102',trailerId:'V-102',reason:'Recover the next London departure after the simulator-observed 165-minute dock wait'},s.loads.find((x:any)=>x.id==='RS-1043').version);assert.ok(f.proposal.body.comparison.proposed.eligible);assert.ok(!f.proposal.body.comparison.current?.eligible||f.proposal.body.comparison.currentUnavailable);await save();console.log('Recovery ready for built-browser approval and separate driver acceptance');
 }else if(phase==='seal'){
  assert.ok(f.beforeReplay&&!f.replayed,'Seal requires the complete original run');f.beforeReplay=await durable();assert.equal(f.beforeReplay.invoice_revisions.filter((i:any)=>i.status==='approved').length,1);f.billingReviewed=true;await save();console.log('Approved billing and all operational records sealed for replay comparison');
 }else if(phase==='run'||phase==='replay'){
  assert.ok(f.proposal,'Rehearse and approve first');const s=await api('state');const recovered=s.assignments.find((x:any)=>x.loadId==='RS-1043'&&x.driverId==='D-02'&&x.status==='accepted');assert.ok(recovered,'Actual dispatcher approval and driver acceptance required');f.approval=recovered;
  if(phase==='replay'){assert.ok(f.beforeReplay&&f.billingReviewed&&!f.replayed,'Completed original, reviewed billing and unreplayed fixture required');await sim(`/runs/${f.run.id}/reset`,{});}
  await sim(`/runs/${f.run.id}/resume`,{});let state=await sim(`/runs/${f.run.id}`);const target=phase==='replay'?f.finishedSeconds:10200;
  while(state.elapsed_seconds<target){const batch=Math.min(300,target-state.elapsed_seconds);const out=await sim(`/runs/${f.run.id}/advance`,{seconds:batch});state=await sim(`/runs/${f.run.id}`);console.log(JSON.stringify({phase,elapsed:state.elapsed_seconds,phaseName:state.phase,events:state.events.length}));assert.ok(!out.pending);if(phase==='run'&&state.phase==='route_complete')break;}
  await sim(`/runs/${f.run.id}/pause`,{});assert.equal(state.phase,'route_complete');const digest=createHash('sha256').update(JSON.stringify(state.events)).digest('hex');
  if(phase==='run'){f.finishedSeconds=state.elapsed_seconds;f.eventHash=digest;f.conditions=state.initial_conditions;f.beforeReplay=await durable();f.finalState=await api('state');assert.equal(f.beforeReplay.telemetry.length,state.events.length);const closed=f.beforeReplay.stop_visits.filter((v:any)=>v.departure);assert.equal(closed.length,1);const draft=f.beforeReplay.invoice_revisions.find((i:any)=>i.status==='draft');assert.ok(draft&&draft.body.amountCents>0);f.draft=draft;await save();console.log(JSON.stringify({phase,events:state.events.length,hash:digest,draft: draft.body}));}
  else{assert.equal(digest,f.eventHash);assert.deepEqual(state.initial_conditions,f.conditions);assert.deepEqual(await durable(),f.beforeReplay);assert.deepEqual([f.draft.body.dwellMinutes,f.draft.body.billableMinutes,f.draft.body.amountCents],[165,45,7500]);assert.equal(f.beforeReplay.invoice_revisions.length,2);assert.equal(f.finalState.resources.find((r:any)=>r.id==='D-01').budget.onDutyMinutes,40);f.replayed=true;f.verifiedAt=new Date().toISOString();await save();await writeFile(dir+'/verification.json',JSON.stringify({verifiedAt:f.verifiedAt,carrier:f.carrier,runId:f.run.id,conditionsHash:f.run.conditions_hash,eventHash:digest,events:state.events.length,elapsedSeconds:f.finishedSeconds,conditions:f.conditions,delay:f.delay,comparison:f.proposal.body.comparison,acceptedRecovery:f.approval,finalDutyEvidence:f.finalState.resources.filter((r:any)=>r.id==='D-01'||r.id==='D-02'),visits:f.beforeReplay.stop_visits,invoices:f.beforeReplay.invoice_revisions,checks:['Independent simulator sends every one-second observation through operational HTTP API','Delay identifies next offered load without assigning it','Dispatcher approval and independent driver acceptance required before continuation','Full dock wait closes with same-stop observation evidence and configured two-hour free time','Dispatcher separately reviews the same-stop samples and approves billing before replay','Reset replay reproduces exact complete event list hash and initial conditions','Telemetry, visits, invoice revisions, assignments, reservations, disruptions and approvals byte-equivalent after replay'],limits:'Synthetic London local trip with actual Valhalla truck geometry and explicitly authored 165-minute dwell. Same-run reset validates deduplication, not an independent counterfactual savings experiment. Final destination visit remains open pending departure evidence; a stop-completion command does not establish billing time. No native or cloud control claim.'},null,2)+'\n');console.log('Complete replay is identical; no operational records duplicated');}
 }else throw Error('Use prepare, recover, run, seal or replay');
}finally{await db.end();}
