import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {writeFile,mkdir,access,readFile} from 'node:fs/promises';
import {pool} from '../services/api/src/db.ts';
import {Store} from '../services/api/src/store.ts';
import {london} from '../services/api/src/fixtures.ts';
const db=pool('postgresql://roadstar:local-roadstar-only@127.0.0.1:55432/roadstar'),dir='docs/evidence/dock-hos-2026-09-12';
const resume=process.argv[2]==='resume';const f:any=resume?JSON.parse(await readFile('data/dock-hos-fixture.json','utf8')):{carrier:'dock-hos-'+randomUUID(),createdAt:new Date().toISOString(),checkpoints:[]};const carrier=f.carrier;
async function save(){await writeFile('data/dock-hos-fixture.json',JSON.stringify(f,null,2)+'\n');}
async function api(path:string,body?:unknown,version=1,role='demo-dispatcher',status=200){const r=await fetch('http://127.0.0.1:4010/api/'+path,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer '+role,'x-carrier-id':carrier,'content-type':'application/json','idempotency-key':randomUUID(),'if-match':String(version)},body:body===undefined?undefined:JSON.stringify(body)});const out:any=await r.json();assert.equal(r.status,status,JSON.stringify(out));return out;}
async function sim(path:string,body?:unknown){const r=await fetch('http://127.0.0.1:4020'+path,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(600000)});const out:any=await r.json();assert.ok(r.ok,JSON.stringify(out));return out;}
try{
 if(!resume){await access('data/dock-hos-fixture.json').then(()=>{throw Error('Retained dock HOS fixture exists; archive it explicitly before preparing a new scenario.');},e=>{if(e.code!=='ENOENT')throw e;});await mkdir(dir,{recursive:true});await new Store(db).seed(carrier);await save();
 const pickup={id:'london-local-yard',name:'London local yard · synthetic location',lat:42.99,lng:-81.20,radiusM:100};
 const row=(await db.query("SELECT body FROM loads WHERE carrier_id=$1 AND id='RS-1042'",[carrier])).rows[0];const load={...row.body,pickup,drivingMinutes:10,serviceMinutes:10,endAt:'2026-09-13T13:00:00Z'};
 await db.query("UPDATE loads SET body=$2 WHERE carrier_id=$1 AND id='RS-1042'",[carrier,JSON.stringify(load)]);await db.query("DELETE FROM stops WHERE carrier_id=$1 AND load_id='RS-1042'",[carrier]);for(const [i,s]of[load.pickup,load.delivery].entries())await db.query('INSERT INTO stops VALUES($1,$2,$3,$4,ST_SetSRID(ST_MakePoint($5,$6),4326)::geography,$7,$8)',[carrier,load.id,s.id,i,s.lng,s.lat,s.radiusM,JSON.stringify(s)]);
 for(const id of ['D-01','D-02'])await db.query("UPDATE resources SET body=jsonb_set(body,'{position}',$3::jsonb) WHERE carrier_id=$1 AND id=$2",[carrier,id,JSON.stringify(id==='D-01'?pickup:london)]);
 f.hosSource={driverId:'D-01',cycle:1,dayAnchor:'2026-09-13T04:00:00Z',sourceName:'synthetic-overnight-duty.csv',sourceCsv:'start,end,duty\n2026-08-28T04:00:00Z,2026-09-12T23:30:00Z,off_duty\n2026-09-12T23:30:00Z,2026-09-13T12:00:00Z,on_duty\n',reason:'Synthetic overnight duty ledger for the dock exhaustion rehearsal',acknowledgePlanningLimits:true,acceptIncomplete:false};
 f.review=await api('review-hos',f.hosSource);assert.equal(f.review.budget.onDutyMinutes,90);await save();
 f.trip=await api('dispatch',{loadId:load.id,driverId:'D-01',truckId:'T-101',trailerId:'V-101'});await api('respond',{assignmentId:f.trip.id,action:'accept'},1,'demo-driver-1');
 f.request={assignment_id:f.trip.id,carrier_id:carrier,start_time:f.trip.startAt,dock_wait_seconds:36000,route:{locations:[pickup,london].map(p=>({lat:p.lat,lon:p.lng})),truck:{height:4.1,width:2.6,length:23,weight:40,axle_load:9,hazmat:false,evidence:'synthetic-scenario'}}};f.run=await sim('/runs',f.request);await save();}else assert.ok(f.run&&!f.ready,'Resume requires an incomplete retained run');
 await sim(`/runs/${f.run.id}/resume`,{});
 for(const target of [3600,9000,9900]){if(f.checkpoints.some((c:any)=>c.seconds===target))continue;let run=await sim(`/runs/${f.run.id}`);while(run.elapsed_seconds<target){const result=await sim(`/runs/${f.run.id}/advance`,{seconds:Math.min(300,target-run.elapsed_seconds)});assert.ok(!result.pending);run=await sim(`/runs/${f.run.id}`);}const s=await api('state'),d=s.resources.find((r:any)=>r.id==='D-01'),e=s.openVisitEstimates[0];assert.equal(run.phase,'dock_wait');assert.equal(d.budget.onDutyMinutes,0);assert.equal(d.budget.drivingMinutes,780);assert.equal(e.status,'estimate');assert.equal(e.dwellMinutes,target/60);assert.equal(e.amountCents,target===3600?0:target===9000?5000:7500);assert.equal(s.invoices.length,0);assert.equal(s.visits[0].departure,null);f.checkpoints.push({seconds:target,eventCount:run.events.length,driver:d,estimate:e,visit:s.visits[0]});await save();console.log(JSON.stringify({seconds:target,amountCents:e.amountCents,onDutyMinutes:d.budget.onDutyMinutes}));}
 await sim(`/runs/${f.run.id}/pause`,{});
 const before=await api('state');f.rejected=await api('propose',{loadId:'RS-1043',driverId:'D-01',truckId:'T-101',trailerId:'V-101'},1,'demo-dispatcher',409);assert.equal(f.rejected.error.code,'INELIGIBLE');const after=await api('state');assert.deepEqual(after.assignments,before.assignments);assert.deepEqual(after.proposals,before.proposals);if(!f.proposal)f.proposal=await api('propose',{loadId:'RS-1043',driverId:'D-02',truckId:'T-102',trailerId:'V-102',reason:'Keep the exhausted driver at the dock and review an eligible driver for the next open load'});await save();assert.ok(f.proposal.body.proof.eligible);f.ready=true;await save();console.log('Ready for separate built-web dispatcher approval and driver acceptance: '+carrier);
}finally{try{if(f.run)await sim(`/runs/${f.run.id}/pause`,{});}finally{await db.end();}}
