import test from 'node:test';import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Queue,type Database} from '../src/queue.ts';
import {axleDraftInput,axleDraftCurrent,axleReviewCommand,axleSourceKey,calculateAxles,type AxleDraft} from '../src/axle-review.ts';
function draft():AxleDraft{return {snapshot:{loadId:'RS-1042',truckId:'T-101',trailerId:'V-101',truckVersion:3,trailerVersion:1,loadVersion:1,weightLb:32000,historyId:'prior',documents:[{id:'12345678-1234-4234-8234-123456789012',load_id:'RS-1042',version:3,status:'stored',sha256:'a'.repeat(64),media_type:'application/pdf'}]},values:{tractorWheelbaseM:'4',fifthWheelFromSteerM:'3.8',trailerSpanM:'10',cargoCgFromKingpinM:'8',emptySteer:'5000',emptyDrive:'5000',emptyTrailer:'4000',limitSteer:'6500',limitDrive:'18000',limitTrailer:'14000',grossLimitKg:'40000',driveAxles:'2',trailerAxles:'2'},documentId:'12345678-1234-4234-8234-123456789012',sourceNote:'Reviewed synthetic same-load weights, geometry and source limits.',reason:'Retain the supported group overload before repositioning cargo.'};}
test('native assessment requires current opened source and explicit acknowledgment, but retains failed results',()=>{const d=draft(),key=axleSourceKey(d.snapshot.documents[0]);assert.equal(axleReviewCommand(d,d.snapshot,'',true),null);assert.equal(axleReviewCommand(d,d.snapshot,key,false),null);const cmd=axleReviewCommand(d,d.snapshot,key,true);assert.ok(cmd);assert.equal(cmd.version,3);const r=calculateAxles(cmd.body.configuration,d.snapshot.weightLb,cmd.body.cargoCgFromKingpinM);assert.equal(r.grossWithinLimit,true);assert.equal(r.eligible,false);d.values.cargoCgFromKingpinM='5';const passed=axleDraftInput(d);assert.ok(passed.success);assert.equal(calculateAxles(passed.data.configuration,32000,5).eligible,true);});
test('native draft rejects changed vehicle/load/history/source and source from another shipment',()=>{for(const mutate of [(s:AxleDraft['snapshot'])=>s.truckVersion++,(s:AxleDraft['snapshot'])=>s.trailerVersion++,(s:AxleDraft['snapshot'])=>s.loadVersion++,(s:AxleDraft['snapshot'])=>s.weightLb++,(s:AxleDraft['snapshot'])=>s.historyId='other',(s:AxleDraft['snapshot'])=>s.documents[0].version++,(s:AxleDraft['snapshot'])=>s.documents[0].sha256='b'.repeat(64),(s:AxleDraft['snapshot'])=>s.documents[0].load_id='other',(s:AxleDraft['snapshot'])=>s.documents[0].status='registered',(s:AxleDraft['snapshot'])=>s.truckId='other']){const d=draft(),current=structuredClone(d.snapshot);mutate(current);assert.equal(axleDraftCurrent(d,current),false);assert.equal(axleReviewCommand(d,current,axleSourceKey(d.snapshot.documents[0]),true),null);}});
test('blank, unsupported and malformed native inputs cannot create commands',()=>{for(const [k,v] of [['emptySteer',''],['cargoCgFromKingpinM','11'],['driveAxles','1.5'],['trailerSpanM','NaN'],['fifthWheelFromSteerM','5']]){const d=draft();d.values[k]=v;assert.equal(axleDraftInput(d).success,false);}const d=draft();d.sourceNote='short';assert.equal(axleDraftInput(d).success,false);});
function connect(path:string){const sql=new DatabaseSync(path),db:Database={execAsync:async s=>{sql.exec(s);},runAsync:async(s,...p)=>sql.prepare(s).run(...p),getAllAsync:async<T>(s:string,...p:any[])=>sql.prepare(s).all(...p) as T[],getFirstAsync:async<T>(s:string,...p:any[])=>sql.prepare(s).get(...p) as T??null};return {sql,db};}
test('axle draft and exact queued command survive SQLite restart, preserve original versions and stay scoped',async()=>{const dir=mkdtempSync(join(tmpdir(),'roadstar-axle-'));try{const path=join(dir,'db'),d=draft();let c=connect(path),q=new Queue(c.db,'local|carrier|dispatcher');await q.init();await q.saveDraft('axle:draft',JSON.stringify(d));await q.enqueue('review-id','/api/review-axles',axleDraftInput(d).data,3,'Axle review');await q.flush(async()=>{throw new Error('offline');});c.sql.close();c=connect(path);q=new Queue(c.db,'local|carrier|dispatcher');await q.init();assert.deepEqual(JSON.parse(await q.draft('axle:draft')),d);assert.equal((await q.list())[0].status,'pending');let count=0;await q.flush(async command=>{count++;assert.equal(command.id,'review-id');assert.equal(command.expectedVersion,3);return {status:200,body:{revision:3}};});await q.flush(async()=>{throw new Error('must not repeat synchronized command');});assert.equal(count,1);assert.equal((await q.list())[0].status,'synchronized');const other=new Queue(c.db,'local|carrier|driver');await other.init();assert.equal(await other.draft('axle:draft'),'');assert.equal((await other.list()).length,0);c.sql.close();}finally{rmSync(dir,{recursive:true,force:true});}});
