import test from 'node:test';import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Queue,type Database} from '../src/queue.ts';
import {parseUtcInput,correctionBody,correctionCommand,type VisitCorrectionDraft} from '../src/visit-correction.ts';
import {sourceKey,type BillingReview} from '../src/billing-review.ts';
function fixture():VisitCorrectionDraft {const snapshot:BillingReview={visit:{id:'f9116940-9115-4bd8-9182-19c4b3226f86',assignment_id:'trip',load_id:'RS-1042',stop_id:'milton',arrival:'2026-09-13T12:30:00Z',departure:'2026-09-13T15:15:00Z',arrival_event:'a',departure_event:'b'},expectedVersion:0,reviewRequired:false,fingerprint:'a'.repeat(64),documents:[{id:'c9116940-9115-4bd8-9182-19c4b3226f86',version:2,sha256:'b'.repeat(64),media_type:'application/pdf'}],history:[],invoices:[],neighbors:[],terms:[],effective:{arrivalAt:'2026-09-13T12:30:00Z',departureAt:'2026-09-13T15:15:00Z'}};return {snapshot,documentId:snapshot.documents[0].id,arrival:'2026-09-13 12:40:00',departure:'2026-09-13 15:10:00',sourceNote:'Page 1 identifies the same Milton dock and service times.',reason:'The original GPS times include yard waiting before check-in.'};}
test('UTC inputs reject normalization, zones and reversed chronology',()=>{assert.equal(parseUtcInput('2026-09-13 12:40'),'2026-09-13T12:40:00.000Z');for(const v of ['2026-02-30 12:00','2026-09-13 24:00','2026-09-13 12:40-04:00','9/13/2026 12:40'])assert.equal(parseUtcInput(v),null,v);const d=fixture();d.departure=d.arrival;assert.equal(correctionBody(d),null);});
test('correction binds version zero, exact viewed source and explicit acknowledgement',()=>{const d=fixture(),key=sourceKey(d.snapshot.documents[0]);const command=correctionCommand(d,d.snapshot,key,true);assert.equal(command?.version,0);assert.equal((command?.body as any).arrivalAt,'2026-09-13T12:40:00.000Z');assert.equal(correctionCommand(d,d.snapshot,'',true),null);assert.equal(correctionCommand(d,d.snapshot,key,false),null);});
test('saved correction never silently rebases changed evidence',()=>{const d=JSON.parse(JSON.stringify(fixture())),key=sourceKey(d.snapshot.documents[0]);for(const mutate of [(r:BillingReview)=>r.fingerprint='c'.repeat(64),(r:BillingReview)=>r.expectedVersion=1,(r:BillingReview)=>r.expectedVersion=undefined,(r:BillingReview)=>r.documents[0].sha256='d'.repeat(64),(r:BillingReview)=>r.documents[0].version++,(r:BillingReview)=>r.visit.stop_id='other',(r:BillingReview)=>r.visit.departure=null,(r:BillingReview)=>r.visit.superseded_by='new',(r:BillingReview)=>r.reviewRequired=true]){const current=structuredClone(d.snapshot);mutate(current);assert.equal(correctionCommand(d,current,key,true),null);}assert.equal(d.snapshot.expectedVersion,0);assert.equal(d.snapshot.fingerprint,'a'.repeat(64));});

function connect(path:string){const sql=new DatabaseSync(path),db:Database={execAsync:async s=>{sql.exec(s);},runAsync:async(s,...p)=>sql.prepare(s).run(...p),getAllAsync:async<T>(s:string,...p:any[])=>sql.prepare(s).all(...p) as T[],getFirstAsync:async<T>(s:string,...p:any[])=>sql.prepare(s).get(...p) as T??null};return {sql,db};}
test('correction draft and original command survive SQLite reopening without duplicate execution',async()=>{const dir=mkdtempSync(join(tmpdir(),'roadstar-correction-'));try{const path=join(dir,'db'),d=fixture();let c=connect(path),q=new Queue(c.db,'cloud|carrier|dispatcher');await q.init();await q.saveDraft('correction',JSON.stringify(d));await q.enqueue('correction-id','/api/correct-visit-times',correctionBody(d),0,'Correction');await q.flush(async()=>{throw Error('offline');});c.sql.close();c=connect(path);q=new Queue(c.db,'cloud|carrier|dispatcher');await q.init();assert.deepEqual(JSON.parse(await q.draft('correction')),d);assert.equal((await q.list())[0].status,'pending');let count=0;await q.flush(async cmd=>{count++;assert.equal(cmd.id,'correction-id');assert.equal(cmd.expectedVersion,0);assert.deepEqual(JSON.parse(cmd.body),correctionBody(d));return{status:200,body:{revision:1}};});await q.flush(async()=>{throw Error('Duplicate execution');});assert.equal(count,1);const other=new Queue(c.db,'cloud|other|dispatcher');await other.init();assert.equal(await other.draft('correction'),'');assert.equal((await other.list()).length,0);c.sql.close();}finally{rmSync(dir,{recursive:true,force:true});}});
