import type {Actor,Command,Store} from './store.ts';
import {demand,DomainError} from '../../../packages/domain/src/index.ts';
const configured=()=>!process.env.K_SERVICE&&!!process.env.SIMULATOR_CONTROL_URL;
function origin(){demand(configured(),'SIMULATOR_UNAVAILABLE','Local simulator controls are not configured.',503);const url=new URL(process.env.SIMULATOR_CONTROL_URL!);demand(url.protocol==='http:'&&['127.0.0.1','localhost','[::1]'].includes(url.hostname)&&!url.username&&!url.password&&url.pathname==='/'&&!url.search&&!url.hash,'SIMULATOR_UNAVAILABLE','Simulator control URL must be a loopback HTTP origin.',503);return url.origin;}
async function call(path:string,body?:unknown){let response:Response;try{response=await fetch(origin()+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),redirect:'error',signal:AbortSignal.timeout(60000)});}catch(e){if(e instanceof DomainError)throw e;throw new DomainError('SIMULATOR_UNAVAILABLE','Simulator response unavailable. Retry the same queued action to recover its receipt.',503);}let result:any;try{result=await response.json();}catch{throw new DomainError('SIMULATOR_UNAVAILABLE','Simulator returned an unreadable response.',503);}demand(response.ok,'SIMULATOR_CONTROL',typeof result.detail==='string'?result.detail:JSON.stringify(result.detail??result),response.status>=500?503:409);return result;}
function matches(a:Actor,run:any){return run?.carrier_id===a.carrierId&&run.api_origin===(process.env.SIMULATOR_OPERATIONAL_ORIGIN??`http://127.0.0.1:${process.env.PORT??4010}`);}
async function ownRun(store:Store,a:Actor,run:any){demand(matches(a,run),'NOT_FOUND','Simulator run is unavailable in this carrier.',404);const r=await store.db.query('SELECT l.body FROM assignments a JOIN loads l ON l.carrier_id=a.carrier_id AND l.id=a.load_id WHERE a.carrier_id=$1 AND a.id=$2',[a.carrierId,run.assignment_id]);demand(r.rows[0]?.body.provenance==='synthetic','NOT_FOUND','A synthetic assignment in this carrier is required.',404);return run;}
export async function simulatorInventory(store:Store,a:Actor){store.dispatcher(a);if(!configured())return {configured:false,runs:[]};const result=await call('/control/runs?carrier_id='+encodeURIComponent(a.carrierId));const runs=[];for(const run of result.runs??[]){if(!matches(a,run))continue;try{runs.push(await ownRun(store,a,run));}catch(e){if(!(e instanceof DomainError)||e.code!=='NOT_FOUND')throw e;}}return {configured:true,runs};}
export async function simulatorControl(store:Store,a:Actor,cmd:Command,input:any){store.dispatcher(a);demand(cmd.expectedVersion===0,'INVALID_VERSION','Simulator controls use version zero and an exact state fingerprint.',400);demand(cmd.key.length>=8&&cmd.key.length<=128,'INVALID_KEY','Command key required.',400);const run=await call('/control/runs/'+encodeURIComponent(input.runId));await ownRun(store,a,run);demand(run.run_id===input.runId,'NOT_FOUND','Simulator run identity differs.',404);const result=await call('/control/runs/'+encodeURIComponent(input.runId),{key:cmd.key,expected_state:input.expectedState,action:input.action,seconds:input.seconds??1,revision_id:input.revisionId??null,expected_revision:input.expectedRevision??null,requested_by:a.uid});if(result.pending)throw new DomainError('SIMULATOR_PENDING','Batch paused with retained observations. Resume the run, then retry the original action.',503);if(result.error)throw new DomainError('SIMULATOR_CONTROL',typeof result.error.detail==='string'?result.error.detail:JSON.stringify(result.error.detail),result.error.status>=500?503:409);return result;}
