import {randomUUID,createHash} from 'node:crypto';
import type pg from 'pg';
import type {Store,Actor,Command} from './store.ts';
import {computation} from './planning.ts';
import {demand,timestamp} from '../../../packages/domain/src/index.ts';
import type {Assignment} from '../../../packages/domain/src/index.ts';
export async function commitmentHash(c:pg.PoolClient,carrierId:string){const rows=(await c.query("SELECT id,version,status FROM assignments WHERE carrier_id=$1 AND status IN ('offered','accepted') ORDER BY id",[carrierId])).rows;return createHash('sha256').update(JSON.stringify(rows)).digest('hex');}
export function approvePlan(s:Store,a:Actor,cmd:Command,input:any){s.dispatcher(a);return s.command(a,cmd,'planning.approved',input,async c=>{
 const plan=(await c.query('SELECT * FROM planning_runs WHERE carrier_id=$1 AND id=$2',[a.carrierId,input.planId])).rows[0];demand(plan?.status==='proposal'&&plan.version===cmd.expectedVersion,'STALE_PLAN','Planning proposal changed.');
 demand(plan.input.commitmentHash===await commitmentHash(c,a.carrierId),'STALE_PLAN','Existing dispatch commitments changed. Recompute.');
 for(const evidence of plan.input.versions){const table=evidence.kind==='load'?'loads':'resources';const row=(await c.query(`SELECT version FROM ${table} WHERE carrier_id=$1 AND id=$2`,[a.carrierId,evidence.id])).rows[0];demand(row?.version===evidence.version,'STALE_PLAN','Operational inputs changed. Recompute.');}
 const currentNow=await s.now(c,a,'synthetic');demand(currentNow===plan.input.now,'STALE_PLAN','Scenario clock changed. Recompute.');
 const fresh=await computation('/optimize-roads',plan.input);demand(fresh.input_hash===plan.result.input_hash,'STALE_PLAN','Routing or feasibility evidence changed. Recompute.');
 demand(plan.result.routes.length,'NO_ROUTES','No feasible routes to approve.');const groups=[];const seenLoads=new Set<string>();
 for(const route of plan.result.routes){
  const vehicle=plan.input.vehicles.find((v:any)=>v.id===route.vehicle_id);demand(vehicle,'INVALID_PLAN','Unknown planning vehicle.');const ids=[...new Set<string>(route.stops.map((stop:any)=>stop.load_id))];
  const start=new Date(timestamp(plan.input.now)+vehicle.available_at*60000).toISOString();const last=route.stops.at(-1),lastInput=plan.input.loads.find((l:any)=>l.id===last.load_id);const end=new Date(timestamp(plan.input.now)+(last.minute+lastInput.delivery_service)*60000).toISOString();demand(timestamp(end)>timestamp(start),'INVALID_PLAN','Empty route interval.');
  const groupId=randomUUID(),assignmentIds=new Map<string,string>(),manifestStops=[];
  for(const loadId of ids){demand(!seenLoads.has(loadId),'INVALID_PLAN','Load appears on multiple routes.');seenLoads.add(loadId);const load=await s.load(c,a,loadId);demand(load.status==='open','STALE_PLAN','Load is no longer open.');const id=randomUUID();assignmentIds.set(loadId,id);await c.query("INSERT INTO assignments VALUES($1,$2,$3,$4,$5,$6,$7,$8,1,'offered')",[a.carrierId,id,loadId,vehicle.driverId,vehicle.truckId,vehicle.trailerId,start,end]);await c.query("UPDATE loads SET status='offered',version=version+1 WHERE carrier_id=$1 AND id=$2",[a.carrierId,loadId]);}
  const leader=assignmentIds.values().next().value!;for(const id of [vehicle.driverId,vehicle.truckId,vehicle.trailerId])await c.query("INSERT INTO reservations VALUES($1,$2,$3,$4,tstzrange($5,$6,'[)'),true)",[a.carrierId,randomUUID(),leader,id,start,end]);
  for(const stop of route.stops){const load=await s.load(c,a,stop.load_id),point=stop.stop==='pickup'?load.pickup:load.delivery;manifestStops.push({assignmentId:assignmentIds.get(load.id),loadId:load.id,stop:stop.stop,stopId:point.id,point,minute:stop.minute,customer:load.customer,weightLb:load.weightLb,pallets:load.pallets,mode:load.mode});}
  const resourceVersions=(await c.query('SELECT id,version FROM resources WHERE carrier_id=$1 AND id=ANY($2::text[])',[a.carrierId,[vehicle.driverId,vehicle.truckId,vehicle.trailerId]])).rows;
  const manifest={groupId,planningRunId:plan.id,driverId:vehicle.driverId,truckId:vehicle.truckId,trailerId:vehicle.trailerId,startAt:start,endAt:end,stops:manifestStops,drivingMinutes:route.driving_minutes,dutyMinutes:route.duty_minutes,routingEvidence:plan.result.routing_evidence,inputHash:plan.result.input_hash,resourceVersions,assumptions:plan.result.assumptions,provenance:'synthetic'};
  await c.query("INSERT INTO trip_groups(carrier_id,id,planning_run_id,driver_id,status,body) VALUES($1,$2,$3,$4,'offered',$5)",[a.carrierId,groupId,plan.id,vehicle.driverId,JSON.stringify(manifest)]);
  for(const id of assignmentIds.values()){await c.query('INSERT INTO trip_members VALUES($1,$2,$3)',[a.carrierId,groupId,id]);await c.query('INSERT INTO manifests VALUES($1,$2,$3,now())',[a.carrierId,id,JSON.stringify(manifest)]);}
  await c.query('INSERT INTO outbox(carrier_id,id,kind,payload) VALUES($1,$2,$3,$4)',[a.carrierId,randomUUID(),'driver.assignment',JSON.stringify({groupId,driverId:vehicle.driverId,notifyDriverIds:[vehicle.driverId]})]);groups.push(manifest);
 }
 await c.query("UPDATE planning_runs SET status='approved',version=version+1 WHERE carrier_id=$1 AND id=$2",[a.carrierId,plan.id]);await c.query('INSERT INTO plan_approvals(carrier_id,id,planning_run_id,approved_by,evidence) VALUES($1,$2,$3,$4,$5)',[a.carrierId,randomUUID(),plan.id,a.uid,JSON.stringify({inputHash:fresh.input_hash,groups})]);return {planId:plan.id,status:'approved',version:plan.version+1,groups};
});}
export async function groupFor(c:pg.PoolClient,carrierId:string,assignmentId:string){return (await c.query('SELECT g.* FROM trip_groups g JOIN trip_members m ON m.carrier_id=g.carrier_id AND m.group_id=g.id WHERE g.carrier_id=$1 AND m.assignment_id=$2',[carrierId,assignmentId])).rows[0];}
export async function respondGroup(s:Store,c:pg.PoolClient,a:Actor,v:Assignment,action:string){const group=await groupFor(c,a.carrierId,v.id);if(!group)return null;demand(group.status==='offered','INVALID_TRANSITION','Trip group has already been answered.');
 if(action==='accept')for(const e of group.body.resourceVersions){const row=(await c.query('SELECT version FROM resources WHERE carrier_id=$1 AND id=$2',[a.carrierId,e.id])).rows[0];demand(row?.version===e.version,'STALE_PLAN','Vehicle or duty evidence changed after offer. Dispatcher must review again.');}
 const members=(await c.query('SELECT a.* FROM assignments a JOIN trip_members m ON m.carrier_id=a.carrier_id AND m.assignment_id=a.id WHERE m.carrier_id=$1 AND m.group_id=$2',[a.carrierId,group.id])).rows;
 for(const member of members){await c.query('UPDATE assignments SET status=$3,version=version+1 WHERE carrier_id=$1 AND id=$2',[a.carrierId,member.id,action==='accept'?'accepted':'rejected']);await c.query('UPDATE loads SET status=$3,version=version+1 WHERE carrier_id=$1 AND id=$2',[a.carrierId,member.load_id,action==='accept'?'accepted':'open']);if(action==='reject')await c.query('UPDATE reservations SET active=false WHERE carrier_id=$1 AND assignment_id=$2',[a.carrierId,member.id]);}
 await c.query('UPDATE trip_groups SET status=$3,version=version+1 WHERE carrier_id=$1 AND id=$2',[a.carrierId,group.id,action==='accept'?'accepted':'rejected']);return {...await s.getAssignment(c,a,v.id),tripGroupId:group.id,affectedAssignments:members.map((m:any)=>m.id)};
}
export async function checkGroupStop(c:pg.PoolClient,a:Actor,v:Assignment,stopId:string){const group=await groupFor(c,a.carrierId,v.id);if(!group)return;const completed=(await c.query('SELECT assignment_id,stop_id FROM stop_completions WHERE carrier_id=$1 AND assignment_id IN (SELECT assignment_id FROM trip_members WHERE carrier_id=$1 AND group_id=$2)',[a.carrierId,group.id])).rows;const next=group.body.stops.find((stop:any)=>!completed.some(x=>x.assignment_id===stop.assignmentId&&x.stop_id===stop.stopId));demand(next?.assignmentId===v.id&&next.stopId===stopId,'STOP_ORDER','Complete the next stop in the consolidated manifest.');}
export async function releaseCompletedGroup(c:pg.PoolClient,a:Actor,v:Assignment){const group=await groupFor(c,a.carrierId,v.id);if(!group){await c.query('UPDATE reservations SET active=false WHERE carrier_id=$1 AND assignment_id=$2',[a.carrierId,v.id]);return;}
 const incomplete=(await c.query("SELECT 1 FROM assignments a JOIN trip_members m ON m.carrier_id=a.carrier_id AND m.assignment_id=a.id WHERE m.carrier_id=$1 AND m.group_id=$2 AND a.status<>'completed'",[a.carrierId,group.id])).rows.length;if(!incomplete){await c.query('UPDATE reservations SET active=false WHERE carrier_id=$1 AND assignment_id IN (SELECT assignment_id FROM trip_members WHERE carrier_id=$1 AND group_id=$2)',[a.carrierId,group.id]);await c.query("UPDATE trip_groups SET status='completed',version=version+1 WHERE carrier_id=$1 AND id=$2",[a.carrierId,group.id]);}}
